/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_QAPI_COMMANDS_MISC_I386_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_MISC_I386_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_RTC_RESET_REINJECTION_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_RTC_RESET_REINJECTION_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_SGX_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_SGX_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_XEN_EVENT_LIST_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_XEN_EVENT_LIST_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_XEN_EVENT_INJECT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_XEN_EVENT_INJECT_EVENT;
extern uint16_t _TRACE_QMP_ENTER_RTC_RESET_REINJECTION_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_RTC_RESET_REINJECTION_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_SEV_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_SEV_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_SGX_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_SGX_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_XEN_EVENT_LIST_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_XEN_EVENT_LIST_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_XEN_EVENT_INJECT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_XEN_EVENT_INJECT_DSTATE;
#define TRACE_QMP_ENTER_RTC_RESET_REINJECTION_ENABLED 1
#define TRACE_QMP_EXIT_RTC_RESET_REINJECTION_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_SEV_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_SEV_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_ENABLED 1
#define TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_ENABLED 1
#define TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_SGX_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_SGX_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_ENABLED 1
#define TRACE_QMP_ENTER_XEN_EVENT_LIST_ENABLED 1
#define TRACE_QMP_EXIT_XEN_EVENT_LIST_ENABLED 1
#define TRACE_QMP_ENTER_XEN_EVENT_INJECT_ENABLED 1
#define TRACE_QMP_EXIT_XEN_EVENT_INJECT_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_RTC_RESET_REINJECTION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_RTC_RESET_REINJECTION) || \
    false)

static inline void trace_qmp_enter_rtc_reset_reinjection(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_RTC_RESET_REINJECTION)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_rtc_reset_reinjection " "%s" "\n", json);
#line 83 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_RTC_RESET_REINJECTION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_RTC_RESET_REINJECTION) || \
    false)

static inline void trace_qmp_exit_rtc_reset_reinjection(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_RTC_RESET_REINJECTION)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_rtc_reset_reinjection " "%s %d" "\n", result, succeeded);
#line 98 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_SEV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_SEV) || \
    false)

static inline void trace_qmp_enter_query_sev(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_SEV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_query_sev " "%s" "\n", json);
#line 113 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_SEV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_SEV) || \
    false)

static inline void trace_qmp_exit_query_sev(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_SEV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_query_sev " "%s %d" "\n", result, succeeded);
#line 128 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE) || \
    false)

static inline void trace_qmp_enter_query_sev_launch_measure(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_query_sev_launch_measure " "%s" "\n", json);
#line 143 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE) || \
    false)

static inline void trace_qmp_exit_query_sev_launch_measure(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_query_sev_launch_measure " "%s %d" "\n", result, succeeded);
#line 158 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES) || \
    false)

static inline void trace_qmp_enter_query_sev_capabilities(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_query_sev_capabilities " "%s" "\n", json);
#line 173 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES) || \
    false)

static inline void trace_qmp_exit_query_sev_capabilities(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_query_sev_capabilities " "%s %d" "\n", result, succeeded);
#line 188 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET) || \
    false)

static inline void trace_qmp_enter_sev_inject_launch_secret(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_sev_inject_launch_secret " "%s" "\n", json);
#line 203 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET) || \
    false)

static inline void trace_qmp_exit_sev_inject_launch_secret(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_sev_inject_launch_secret " "%s %d" "\n", result, succeeded);
#line 218 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT) || \
    false)

static inline void trace_qmp_enter_query_sev_attestation_report(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_query_sev_attestation_report " "%s" "\n", json);
#line 233 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT) || \
    false)

static inline void trace_qmp_exit_query_sev_attestation_report(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_query_sev_attestation_report " "%s %d" "\n", result, succeeded);
#line 248 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_SGX_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_SGX) || \
    false)

static inline void trace_qmp_enter_query_sgx(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_SGX)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_query_sgx " "%s" "\n", json);
#line 263 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_SGX_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_SGX) || \
    false)

static inline void trace_qmp_exit_query_sgx(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_SGX)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_query_sgx " "%s %d" "\n", result, succeeded);
#line 278 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES) || \
    false)

static inline void trace_qmp_enter_query_sgx_capabilities(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_query_sgx_capabilities " "%s" "\n", json);
#line 293 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES) || \
    false)

static inline void trace_qmp_exit_query_sgx_capabilities(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_query_sgx_capabilities " "%s %d" "\n", result, succeeded);
#line 308 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_XEN_EVENT_LIST_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_XEN_EVENT_LIST) || \
    false)

static inline void trace_qmp_enter_xen_event_list(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_XEN_EVENT_LIST)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_xen_event_list " "%s" "\n", json);
#line 323 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_XEN_EVENT_LIST_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_XEN_EVENT_LIST) || \
    false)

static inline void trace_qmp_exit_xen_event_list(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_XEN_EVENT_LIST)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 20 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_xen_event_list " "%s %d" "\n", result, succeeded);
#line 338 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_XEN_EVENT_INJECT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_XEN_EVENT_INJECT) || \
    false)

static inline void trace_qmp_enter_xen_event_inject(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_XEN_EVENT_INJECT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 21 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_enter_xen_event_inject " "%s" "\n", json);
#line 353 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_XEN_EVENT_INJECT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_XEN_EVENT_INJECT) || \
    false)

static inline void trace_qmp_exit_xen_event_inject(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_XEN_EVENT_INJECT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "qapi/qapi-commands-misc-i386.trace-events"
            qemu_log("qmp_exit_xen_event_inject " "%s %d" "\n", result, succeeded);
#line 368 "trace/trace-qapi_commands_misc_i386_trace_events.h"
        }
    }
}
#endif /* TRACE_QAPI_COMMANDS_MISC_I386_TRACE_EVENTS_GENERATED_TRACERS_H */
