/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_ACPI_GENERATED_TRACERS_H
#define TRACE_HW_ACPI_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_ADDR_LO_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_ADDR_HI_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_SIZE_LO_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_SIZE_HI_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_PXM_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_FLAGS_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_WRITE_SLOT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_WRITE_OST_EV_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_WRITE_OST_STATUS_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_CLEAR_INSERT_EVT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_PC_DIMM_DELETED_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_EVENT;
extern TraceEvent _TRACE_ACPI_GPE_EN_IOPORT_READB_EVENT;
extern TraceEvent _TRACE_ACPI_GPE_EN_IOPORT_WRITEB_EVENT;
extern TraceEvent _TRACE_ACPI_GPE_STS_IOPORT_READB_EVENT;
extern TraceEvent _TRACE_ACPI_GPE_STS_IOPORT_WRITEB_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_READ_FLAGS_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_IDX_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_CMD_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_READ_CMD_DATA_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_READ_CMD_DATA2_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_EJECTING_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_FW_REMOVE_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_OST_EV_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_OST_STATUS_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_EJECT_SLOT_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_UNPLUG_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_UNPLUG_REQUEST_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_UP_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_DOWN_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_FEATURES_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_ACPI_INDEX_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_ACPI_INDEX_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_RMV_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_SEL_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_EJ_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_SEL_WRITE_EVENT;
extern TraceEvent _TRACE_TCO_TIMER_RELOAD_EVENT;
extern TraceEvent _TRACE_TCO_TIMER_EXPIRED_EVENT;
extern TraceEvent _TRACE_TCO_IO_WRITE_EVENT;
extern TraceEvent _TRACE_TCO_IO_READ_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REG_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REG_READ_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_MEM_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_MEM_READ_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_PCI_BAR_0_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_PCI_BAR_1_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REALIZEFN_IN_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REALIZEFN_OUT_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_RESET_IN_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_RESET_OUT_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_POST_LOAD_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_CLASS_INIT_IN_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_CLASS_INIT_OUT_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_READ_FIT_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_LABEL_INFO_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_LABEL_OVERFLOW_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_LABEL_OVERSIZE_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_LABEL_XFER_EXCEED_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_READ_LABEL_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_WRITE_LABEL_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_READ_IO_PORT_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_DSM_MEM_ADDR_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_DSM_INFO_EVENT;
extern TraceEvent _TRACE_ACPI_NVDIMM_INVALID_REVISION_EVENT;
extern uint16_t _TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_ADDR_LO_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_ADDR_HI_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_SIZE_LO_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_SIZE_HI_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_PXM_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_FLAGS_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_WRITE_SLOT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_WRITE_OST_EV_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_WRITE_OST_STATUS_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_CLEAR_INSERT_EVT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_PC_DIMM_DELETED_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_DSTATE;
extern uint16_t _TRACE_ACPI_GPE_EN_IOPORT_READB_DSTATE;
extern uint16_t _TRACE_ACPI_GPE_EN_IOPORT_WRITEB_DSTATE;
extern uint16_t _TRACE_ACPI_GPE_STS_IOPORT_READB_DSTATE;
extern uint16_t _TRACE_ACPI_GPE_STS_IOPORT_WRITEB_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_READ_FLAGS_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_IDX_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_CMD_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_READ_CMD_DATA_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_READ_CMD_DATA2_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_EJECTING_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_FW_REMOVE_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_OST_EV_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_OST_STATUS_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_EJECT_SLOT_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_UNPLUG_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_UNPLUG_REQUEST_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_UP_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_DOWN_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_FEATURES_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_ACPI_INDEX_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_ACPI_INDEX_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_RMV_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_SEL_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_EJ_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_SEL_WRITE_DSTATE;
extern uint16_t _TRACE_TCO_TIMER_RELOAD_DSTATE;
extern uint16_t _TRACE_TCO_TIMER_EXPIRED_DSTATE;
extern uint16_t _TRACE_TCO_IO_WRITE_DSTATE;
extern uint16_t _TRACE_TCO_IO_READ_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REG_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REG_READ_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_MEM_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_MEM_READ_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_PCI_BAR_0_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_PCI_BAR_1_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REALIZEFN_IN_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REALIZEFN_OUT_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_RESET_IN_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_RESET_OUT_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_POST_LOAD_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_CLASS_INIT_IN_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_CLASS_INIT_OUT_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_READ_FIT_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_LABEL_INFO_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_LABEL_OVERFLOW_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_LABEL_OVERSIZE_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_LABEL_XFER_EXCEED_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_READ_LABEL_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_WRITE_LABEL_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_READ_IO_PORT_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_DSM_MEM_ADDR_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_DSM_INFO_DSTATE;
extern uint16_t _TRACE_ACPI_NVDIMM_INVALID_REVISION_DSTATE;
#define TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_ENABLED 1
#define TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_ENABLED 1
#define TRACE_MHP_ACPI_READ_ADDR_LO_ENABLED 1
#define TRACE_MHP_ACPI_READ_ADDR_HI_ENABLED 1
#define TRACE_MHP_ACPI_READ_SIZE_LO_ENABLED 1
#define TRACE_MHP_ACPI_READ_SIZE_HI_ENABLED 1
#define TRACE_MHP_ACPI_READ_PXM_ENABLED 1
#define TRACE_MHP_ACPI_READ_FLAGS_ENABLED 1
#define TRACE_MHP_ACPI_WRITE_SLOT_ENABLED 1
#define TRACE_MHP_ACPI_WRITE_OST_EV_ENABLED 1
#define TRACE_MHP_ACPI_WRITE_OST_STATUS_ENABLED 1
#define TRACE_MHP_ACPI_CLEAR_INSERT_EVT_ENABLED 1
#define TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_ENABLED 1
#define TRACE_MHP_ACPI_PC_DIMM_DELETED_ENABLED 1
#define TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_ENABLED 1
#define TRACE_ACPI_GPE_EN_IOPORT_READB_ENABLED 1
#define TRACE_ACPI_GPE_EN_IOPORT_WRITEB_ENABLED 1
#define TRACE_ACPI_GPE_STS_IOPORT_READB_ENABLED 1
#define TRACE_ACPI_GPE_STS_IOPORT_WRITEB_ENABLED 1
#define TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_ENABLED 1
#define TRACE_CPUHP_ACPI_READ_FLAGS_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_IDX_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_CMD_ENABLED 1
#define TRACE_CPUHP_ACPI_READ_CMD_DATA_ENABLED 1
#define TRACE_CPUHP_ACPI_READ_CMD_DATA2_ENABLED 1
#define TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_ENABLED 1
#define TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_ENABLED 1
#define TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_ENABLED 1
#define TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_EJECTING_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_FW_REMOVE_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_OST_EV_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_OST_STATUS_ENABLED 1
#define TRACE_ACPI_PCI_EJECT_SLOT_ENABLED 1
#define TRACE_ACPI_PCI_UNPLUG_ENABLED 1
#define TRACE_ACPI_PCI_UNPLUG_REQUEST_ENABLED 1
#define TRACE_ACPI_PCI_UP_READ_ENABLED 1
#define TRACE_ACPI_PCI_DOWN_READ_ENABLED 1
#define TRACE_ACPI_PCI_FEATURES_READ_ENABLED 1
#define TRACE_ACPI_PCI_ACPI_INDEX_READ_ENABLED 1
#define TRACE_ACPI_PCI_ACPI_INDEX_WRITE_ENABLED 1
#define TRACE_ACPI_PCI_RMV_READ_ENABLED 1
#define TRACE_ACPI_PCI_SEL_READ_ENABLED 1
#define TRACE_ACPI_PCI_EJ_WRITE_ENABLED 1
#define TRACE_ACPI_PCI_SEL_WRITE_ENABLED 1
#define TRACE_TCO_TIMER_RELOAD_ENABLED 1
#define TRACE_TCO_TIMER_EXPIRED_ENABLED 1
#define TRACE_TCO_IO_WRITE_ENABLED 1
#define TRACE_TCO_IO_READ_ENABLED 1
#define TRACE_ACPI_ERST_REG_WRITE_ENABLED 1
#define TRACE_ACPI_ERST_REG_READ_ENABLED 1
#define TRACE_ACPI_ERST_MEM_WRITE_ENABLED 1
#define TRACE_ACPI_ERST_MEM_READ_ENABLED 1
#define TRACE_ACPI_ERST_PCI_BAR_0_ENABLED 1
#define TRACE_ACPI_ERST_PCI_BAR_1_ENABLED 1
#define TRACE_ACPI_ERST_REALIZEFN_IN_ENABLED 1
#define TRACE_ACPI_ERST_REALIZEFN_OUT_ENABLED 1
#define TRACE_ACPI_ERST_RESET_IN_ENABLED 1
#define TRACE_ACPI_ERST_RESET_OUT_ENABLED 1
#define TRACE_ACPI_ERST_POST_LOAD_ENABLED 1
#define TRACE_ACPI_ERST_CLASS_INIT_IN_ENABLED 1
#define TRACE_ACPI_ERST_CLASS_INIT_OUT_ENABLED 1
#define TRACE_ACPI_NVDIMM_READ_FIT_ENABLED 1
#define TRACE_ACPI_NVDIMM_LABEL_INFO_ENABLED 1
#define TRACE_ACPI_NVDIMM_LABEL_OVERFLOW_ENABLED 1
#define TRACE_ACPI_NVDIMM_LABEL_OVERSIZE_ENABLED 1
#define TRACE_ACPI_NVDIMM_LABEL_XFER_EXCEED_ENABLED 1
#define TRACE_ACPI_NVDIMM_READ_LABEL_ENABLED 1
#define TRACE_ACPI_NVDIMM_WRITE_LABEL_ENABLED 1
#define TRACE_ACPI_NVDIMM_READ_IO_PORT_ENABLED 1
#define TRACE_ACPI_NVDIMM_DSM_MEM_ADDR_ENABLED 1
#define TRACE_ACPI_NVDIMM_DSM_INFO_ENABLED 1
#define TRACE_ACPI_NVDIMM_INVALID_REVISION_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_INVALID_SLOT_SELECTED) || \
    false)

static inline void trace_mhp_acpi_invalid_slot_selected(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_INVALID_SLOT_SELECTED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_invalid_slot_selected " "0x%"PRIx32 "\n", slot);
#line 245 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_EJECTING_INVALID_SLOT) || \
    false)

static inline void trace_mhp_acpi_ejecting_invalid_slot(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_EJECTING_INVALID_SLOT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_ejecting_invalid_slot " "0x%"PRIx32 "\n", slot);
#line 260 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_READ_ADDR_LO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_ADDR_LO) || \
    false)

static inline void trace_mhp_acpi_read_addr_lo(uint32_t slot, uint32_t addr)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_ADDR_LO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_addr_lo " "slot[0x%"PRIx32"] addr lo: 0x%"PRIx32 "\n", slot, addr);
#line 275 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_READ_ADDR_HI_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_ADDR_HI) || \
    false)

static inline void trace_mhp_acpi_read_addr_hi(uint32_t slot, uint32_t addr)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_ADDR_HI)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_addr_hi " "slot[0x%"PRIx32"] addr hi: 0x%"PRIx32 "\n", slot, addr);
#line 290 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_READ_SIZE_LO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_SIZE_LO) || \
    false)

static inline void trace_mhp_acpi_read_size_lo(uint32_t slot, uint32_t size)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_SIZE_LO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_size_lo " "slot[0x%"PRIx32"] size lo: 0x%"PRIx32 "\n", slot, size);
#line 305 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_READ_SIZE_HI_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_SIZE_HI) || \
    false)

static inline void trace_mhp_acpi_read_size_hi(uint32_t slot, uint32_t size)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_SIZE_HI)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_size_hi " "slot[0x%"PRIx32"] size hi: 0x%"PRIx32 "\n", slot, size);
#line 320 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_READ_PXM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_PXM) || \
    false)

static inline void trace_mhp_acpi_read_pxm(uint32_t slot, uint32_t pxm)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_PXM)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_pxm " "slot[0x%"PRIx32"] proximity: 0x%"PRIx32 "\n", slot, pxm);
#line 335 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_READ_FLAGS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_FLAGS) || \
    false)

static inline void trace_mhp_acpi_read_flags(uint32_t slot, uint32_t flags)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_FLAGS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_flags " "slot[0x%"PRIx32"] flags: 0x%"PRIx32 "\n", slot, flags);
#line 350 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_WRITE_SLOT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_WRITE_SLOT) || \
    false)

static inline void trace_mhp_acpi_write_slot(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_WRITE_SLOT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_write_slot " "set active slot: 0x%"PRIx32 "\n", slot);
#line 365 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_WRITE_OST_EV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_WRITE_OST_EV) || \
    false)

static inline void trace_mhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_WRITE_OST_EV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_write_ost_ev " "slot[0x%"PRIx32"] OST EVENT: 0x%"PRIx32 "\n", slot, ev);
#line 380 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_WRITE_OST_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_WRITE_OST_STATUS) || \
    false)

static inline void trace_mhp_acpi_write_ost_status(uint32_t slot, uint32_t st)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_WRITE_OST_STATUS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_write_ost_status " "slot[0x%"PRIx32"] OST STATUS: 0x%"PRIx32 "\n", slot, st);
#line 395 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_CLEAR_INSERT_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_CLEAR_INSERT_EVT) || \
    false)

static inline void trace_mhp_acpi_clear_insert_evt(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_CLEAR_INSERT_EVT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_clear_insert_evt " "slot[0x%"PRIx32"] clear insert event" "\n", slot);
#line 410 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_CLEAR_REMOVE_EVT) || \
    false)

static inline void trace_mhp_acpi_clear_remove_evt(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_CLEAR_REMOVE_EVT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_clear_remove_evt " "slot[0x%"PRIx32"] clear remove event" "\n", slot);
#line 425 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_PC_DIMM_DELETED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_PC_DIMM_DELETED) || \
    false)

static inline void trace_mhp_acpi_pc_dimm_deleted(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_PC_DIMM_DELETED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_pc_dimm_deleted " "slot[0x%"PRIx32"] pc-dimm deleted" "\n", slot);
#line 440 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED) || \
    false)

static inline void trace_mhp_acpi_pc_dimm_delete_failed(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../hw/acpi/trace-events"
            qemu_log("mhp_acpi_pc_dimm_delete_failed " "slot[0x%"PRIx32"] pc-dimm delete failed" "\n", slot);
#line 455 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_GPE_EN_IOPORT_READB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_GPE_EN_IOPORT_READB) || \
    false)

static inline void trace_acpi_gpe_en_ioport_readb(uint32_t addr, uint8_t val)
{
    if (trace_event_get_state(TRACE_ACPI_GPE_EN_IOPORT_READB)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 21 "../hw/acpi/trace-events"
            qemu_log("acpi_gpe_en_ioport_readb " "addr: 0x%" PRIx32 " ==> 0x%02" PRIx8 "\n", addr, val);
#line 470 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_GPE_EN_IOPORT_WRITEB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_GPE_EN_IOPORT_WRITEB) || \
    false)

static inline void trace_acpi_gpe_en_ioport_writeb(uint32_t addr, uint8_t val)
{
    if (trace_event_get_state(TRACE_ACPI_GPE_EN_IOPORT_WRITEB)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "../hw/acpi/trace-events"
            qemu_log("acpi_gpe_en_ioport_writeb " "addr: 0x%" PRIx32 " <== 0x%02" PRIx8 "\n", addr, val);
#line 485 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_GPE_STS_IOPORT_READB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_GPE_STS_IOPORT_READB) || \
    false)

static inline void trace_acpi_gpe_sts_ioport_readb(uint32_t addr, uint8_t val)
{
    if (trace_event_get_state(TRACE_ACPI_GPE_STS_IOPORT_READB)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 23 "../hw/acpi/trace-events"
            qemu_log("acpi_gpe_sts_ioport_readb " "addr: 0x%" PRIx32 " ==> 0x%02" PRIx8 "\n", addr, val);
#line 500 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_GPE_STS_IOPORT_WRITEB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_GPE_STS_IOPORT_WRITEB) || \
    false)

static inline void trace_acpi_gpe_sts_ioport_writeb(uint32_t addr, uint8_t val)
{
    if (trace_event_get_state(TRACE_ACPI_GPE_STS_IOPORT_WRITEB)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 24 "../hw/acpi/trace-events"
            qemu_log("acpi_gpe_sts_ioport_writeb " "addr: 0x%" PRIx32 " <== 0x%02" PRIx8 "\n", addr, val);
#line 515 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED) || \
    false)

static inline void trace_cpuhp_acpi_invalid_idx_selected(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 27 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_invalid_idx_selected " "0x%"PRIx32 "\n", idx);
#line 530 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_READ_FLAGS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_READ_FLAGS) || \
    false)

static inline void trace_cpuhp_acpi_read_flags(uint32_t idx, uint8_t flags)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_READ_FLAGS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 28 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_read_flags " "idx[0x%"PRIx32"] flags: 0x%"PRIx8 "\n", idx, flags);
#line 545 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_WRITE_IDX_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_IDX) || \
    false)

static inline void trace_cpuhp_acpi_write_idx(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_IDX)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 29 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_idx " "set active cpu idx: 0x%"PRIx32 "\n", idx);
#line 560 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_WRITE_CMD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_CMD) || \
    false)

static inline void trace_cpuhp_acpi_write_cmd(uint32_t idx, uint8_t cmd)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_CMD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 30 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_cmd " "idx[0x%"PRIx32"] cmd: 0x%"PRIx8 "\n", idx, cmd);
#line 575 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_READ_CMD_DATA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_READ_CMD_DATA) || \
    false)

static inline void trace_cpuhp_acpi_read_cmd_data(uint32_t idx, uint32_t data)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_READ_CMD_DATA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 31 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_read_cmd_data " "idx[0x%"PRIx32"] data: 0x%"PRIx32 "\n", idx, data);
#line 590 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_READ_CMD_DATA2_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_READ_CMD_DATA2) || \
    false)

static inline void trace_cpuhp_acpi_read_cmd_data2(uint32_t idx, uint32_t data)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_READ_CMD_DATA2)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 32 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_read_cmd_data2 " "idx[0x%"PRIx32"] data: 0x%"PRIx32 "\n", idx, data);
#line 605 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_CPU_HAS_EVENTS) || \
    false)

static inline void trace_cpuhp_acpi_cpu_has_events(uint32_t idx, bool ins, bool rm)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_CPU_HAS_EVENTS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 33 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_cpu_has_events " "idx[0x%"PRIx32"] inserting: %d, removing: %d" "\n", idx, ins, rm);
#line 620 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT) || \
    false)

static inline void trace_cpuhp_acpi_clear_inserting_evt(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 34 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_clear_inserting_evt " "idx[0x%"PRIx32"]" "\n", idx);
#line 635 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT) || \
    false)

static inline void trace_cpuhp_acpi_clear_remove_evt(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 35 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_clear_remove_evt " "idx[0x%"PRIx32"]" "\n", idx);
#line 650 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU) || \
    false)

static inline void trace_cpuhp_acpi_ejecting_invalid_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 36 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_ejecting_invalid_cpu " "0x%"PRIx32 "\n", idx);
#line 665 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_EJECTING_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_EJECTING_CPU) || \
    false)

static inline void trace_cpuhp_acpi_ejecting_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_EJECTING_CPU)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 37 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_ejecting_cpu " "0x%"PRIx32 "\n", idx);
#line 680 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU) || \
    false)

static inline void trace_cpuhp_acpi_fw_remove_invalid_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 38 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_fw_remove_invalid_cpu " "0x%"PRIx32 "\n", idx);
#line 695 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_FW_REMOVE_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_FW_REMOVE_CPU) || \
    false)

static inline void trace_cpuhp_acpi_fw_remove_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_FW_REMOVE_CPU)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 39 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_fw_remove_cpu " "0x%"PRIx32 "\n", idx);
#line 710 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_WRITE_OST_EV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_OST_EV) || \
    false)

static inline void trace_cpuhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_OST_EV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 40 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_ost_ev " "idx[0x%"PRIx32"] OST EVENT: 0x%"PRIx32 "\n", slot, ev);
#line 725 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_CPUHP_ACPI_WRITE_OST_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_OST_STATUS) || \
    false)

static inline void trace_cpuhp_acpi_write_ost_status(uint32_t slot, uint32_t st)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_OST_STATUS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 41 "../hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_ost_status " "idx[0x%"PRIx32"] OST STATUS: 0x%"PRIx32 "\n", slot, st);
#line 740 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_EJECT_SLOT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_EJECT_SLOT) || \
    false)

static inline void trace_acpi_pci_eject_slot(unsigned bsel, unsigned slot)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_EJECT_SLOT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 44 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_eject_slot " "bsel: %u slot: %u" "\n", bsel, slot);
#line 755 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_UNPLUG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_UNPLUG) || \
    false)

static inline void trace_acpi_pci_unplug(int bsel, int slot)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_UNPLUG)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 45 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_unplug " "bsel: %d slot: %d" "\n", bsel, slot);
#line 770 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_UNPLUG_REQUEST_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_UNPLUG_REQUEST) || \
    false)

static inline void trace_acpi_pci_unplug_request(int bsel, int slot)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_UNPLUG_REQUEST)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 46 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_unplug_request " "bsel: %d slot: %d" "\n", bsel, slot);
#line 785 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_UP_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_UP_READ) || \
    false)

static inline void trace_acpi_pci_up_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_UP_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 47 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_up_read " "%" PRIu32 "\n", val);
#line 800 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_DOWN_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_DOWN_READ) || \
    false)

static inline void trace_acpi_pci_down_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_DOWN_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 48 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_down_read " "%" PRIu32 "\n", val);
#line 815 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_FEATURES_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_FEATURES_READ) || \
    false)

static inline void trace_acpi_pci_features_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_FEATURES_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 49 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_features_read " "%" PRIu32 "\n", val);
#line 830 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_ACPI_INDEX_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_ACPI_INDEX_READ) || \
    false)

static inline void trace_acpi_pci_acpi_index_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_ACPI_INDEX_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 50 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_acpi_index_read " "%" PRIu32 "\n", val);
#line 845 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_ACPI_INDEX_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_ACPI_INDEX_WRITE) || \
    false)

static inline void trace_acpi_pci_acpi_index_write(unsigned bsel, unsigned slot, uint32_t aidx)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_ACPI_INDEX_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 51 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_acpi_index_write " "bsel: %u slot: %u aidx: %" PRIu32 "\n", bsel, slot, aidx);
#line 860 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_RMV_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_RMV_READ) || \
    false)

static inline void trace_acpi_pci_rmv_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_RMV_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 52 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_rmv_read " "%" PRIu32 "\n", val);
#line 875 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_SEL_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_SEL_READ) || \
    false)

static inline void trace_acpi_pci_sel_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_SEL_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 53 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_sel_read " "%" PRIu32 "\n", val);
#line 890 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_EJ_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_EJ_WRITE) || \
    false)

static inline void trace_acpi_pci_ej_write(uint64_t addr, uint64_t data)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_EJ_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 54 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_ej_write " "0x%" PRIx64 " <== %" PRIu64 "\n", addr, data);
#line 905 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_PCI_SEL_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_SEL_WRITE) || \
    false)

static inline void trace_acpi_pci_sel_write(uint64_t addr, uint64_t data)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_SEL_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 55 "../hw/acpi/trace-events"
            qemu_log("acpi_pci_sel_write " "0x%" PRIx64 " <== %" PRIu64 "\n", addr, data);
#line 920 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_TCO_TIMER_RELOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TCO_TIMER_RELOAD) || \
    false)

static inline void trace_tco_timer_reload(int ticks, int msec)
{
    if (trace_event_get_state(TRACE_TCO_TIMER_RELOAD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 58 "../hw/acpi/trace-events"
            qemu_log("tco_timer_reload " "ticks=%d (%d ms)" "\n", ticks, msec);
#line 935 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_TCO_TIMER_EXPIRED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TCO_TIMER_EXPIRED) || \
    false)

static inline void trace_tco_timer_expired(int timeouts_no, bool strap, bool no_reboot)
{
    if (trace_event_get_state(TRACE_TCO_TIMER_EXPIRED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 59 "../hw/acpi/trace-events"
            qemu_log("tco_timer_expired " "timeouts_no=%d no_reboot=%d/%d" "\n", timeouts_no, strap, no_reboot);
#line 950 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_TCO_IO_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TCO_IO_WRITE) || \
    false)

static inline void trace_tco_io_write(uint64_t addr, uint32_t val)
{
    if (trace_event_get_state(TRACE_TCO_IO_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 60 "../hw/acpi/trace-events"
            qemu_log("tco_io_write " "addr=0x%" PRIx64 " val=0x%" PRIx32 "\n", addr, val);
#line 965 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_TCO_IO_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TCO_IO_READ) || \
    false)

static inline void trace_tco_io_read(uint64_t addr, uint32_t val)
{
    if (trace_event_get_state(TRACE_TCO_IO_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 61 "../hw/acpi/trace-events"
            qemu_log("tco_io_read " "addr=0x%" PRIx64 " val=0x%" PRIx32 "\n", addr, val);
#line 980 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_REG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REG_WRITE) || \
    false)

static inline void trace_acpi_erst_reg_write(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REG_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 64 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_reg_write " "addr: 0x%04" PRIx64 " <== 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 995 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_REG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REG_READ) || \
    false)

static inline void trace_acpi_erst_reg_read(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REG_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 65 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_reg_read " " addr: 0x%04" PRIx64 " ==> 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 1010 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_MEM_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_MEM_WRITE) || \
    false)

static inline void trace_acpi_erst_mem_write(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_MEM_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 66 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_mem_write " "addr: 0x%06" PRIx64 " <== 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 1025 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_MEM_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_MEM_READ) || \
    false)

static inline void trace_acpi_erst_mem_read(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_MEM_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 67 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_mem_read " " addr: 0x%06" PRIx64 " ==> 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 1040 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_PCI_BAR_0_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_PCI_BAR_0) || \
    false)

static inline void trace_acpi_erst_pci_bar_0(uint64_t addr)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_PCI_BAR_0)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 68 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_pci_bar_0 " "BAR0: 0x%016" PRIx64 "\n", addr);
#line 1055 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_PCI_BAR_1_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_PCI_BAR_1) || \
    false)

static inline void trace_acpi_erst_pci_bar_1(uint64_t addr)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_PCI_BAR_1)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 69 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_pci_bar_1 " "BAR1: 0x%016" PRIx64 "\n", addr);
#line 1070 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_REALIZEFN_IN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REALIZEFN_IN) || \
    false)

static inline void trace_acpi_erst_realizefn_in(void)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REALIZEFN_IN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 70 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_realizefn_in "  "\n");
#line 1085 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_REALIZEFN_OUT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REALIZEFN_OUT) || \
    false)

static inline void trace_acpi_erst_realizefn_out(unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REALIZEFN_OUT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 71 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_realizefn_out " "total nvram size %u bytes" "\n", size);
#line 1100 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_RESET_IN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_RESET_IN) || \
    false)

static inline void trace_acpi_erst_reset_in(unsigned record_count)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_RESET_IN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 72 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_reset_in " "record_count %u" "\n", record_count);
#line 1115 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_RESET_OUT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_RESET_OUT) || \
    false)

static inline void trace_acpi_erst_reset_out(unsigned record_count)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_RESET_OUT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 73 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_reset_out " "record_count %u" "\n", record_count);
#line 1130 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_POST_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_POST_LOAD) || \
    false)

static inline void trace_acpi_erst_post_load(void *header, unsigned slot_size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_POST_LOAD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 74 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_post_load " "header: 0x%p slot_size %u" "\n", header, slot_size);
#line 1145 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_CLASS_INIT_IN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_CLASS_INIT_IN) || \
    false)

static inline void trace_acpi_erst_class_init_in(void)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_CLASS_INIT_IN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 75 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_class_init_in "  "\n");
#line 1160 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_ERST_CLASS_INIT_OUT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_CLASS_INIT_OUT) || \
    false)

static inline void trace_acpi_erst_class_init_out(void)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_CLASS_INIT_OUT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 76 "../hw/acpi/trace-events"
            qemu_log("acpi_erst_class_init_out "  "\n");
#line 1175 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_READ_FIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_READ_FIT) || \
    false)

static inline void trace_acpi_nvdimm_read_fit(uint32_t offset, uint32_t len, const char *dirty)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_READ_FIT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 79 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_read_fit " "Read FIT: offset 0x%" PRIx32 " FIT size 0x%" PRIx32 " Dirty %s" "\n", offset, len, dirty);
#line 1190 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_LABEL_INFO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_LABEL_INFO) || \
    false)

static inline void trace_acpi_nvdimm_label_info(uint32_t label_size, uint32_t mxfer)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_LABEL_INFO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 80 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_label_info " "label_size 0x%" PRIx32 ", max_xfer 0x%" PRIx32 "\n", label_size, mxfer);
#line 1205 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_LABEL_OVERFLOW_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_LABEL_OVERFLOW) || \
    false)

static inline void trace_acpi_nvdimm_label_overflow(uint32_t offset, uint32_t length)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_LABEL_OVERFLOW)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 81 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_label_overflow " "offset 0x%" PRIx32 " + length 0x%" PRIx32 " is overflow" "\n", offset, length);
#line 1220 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_LABEL_OVERSIZE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_LABEL_OVERSIZE) || \
    false)

static inline void trace_acpi_nvdimm_label_oversize(uint32_t pos, uint64_t size)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_LABEL_OVERSIZE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 82 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_label_oversize " "position 0x%" PRIx32 " is beyond label data (len = %" PRIu64 ")" "\n", pos, size);
#line 1235 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_LABEL_XFER_EXCEED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_LABEL_XFER_EXCEED) || \
    false)

static inline void trace_acpi_nvdimm_label_xfer_exceed(uint32_t length, uint32_t max_xfer)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_LABEL_XFER_EXCEED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 83 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_label_xfer_exceed " "length (0x%" PRIx32 ") is larger than max_xfer (0x%" PRIx32 ")" "\n", length, max_xfer);
#line 1250 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_READ_LABEL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_READ_LABEL) || \
    false)

static inline void trace_acpi_nvdimm_read_label(uint32_t offset, uint32_t length)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_READ_LABEL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 84 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_read_label " "Read Label Data: offset 0x%" PRIx32 " length 0x%" PRIx32 "\n", offset, length);
#line 1265 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_WRITE_LABEL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_WRITE_LABEL) || \
    false)

static inline void trace_acpi_nvdimm_write_label(uint32_t offset, uint32_t length)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_WRITE_LABEL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 85 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_write_label " "Write Label Data: offset 0x%" PRIx32 " length 0x%" PRIx32 "\n", offset, length);
#line 1280 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_READ_IO_PORT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_READ_IO_PORT) || \
    false)

static inline void trace_acpi_nvdimm_read_io_port(void)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_READ_IO_PORT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 86 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_read_io_port " "Alert: we never read _DSM IO Port" "\n");
#line 1295 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_DSM_MEM_ADDR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_DSM_MEM_ADDR) || \
    false)

static inline void trace_acpi_nvdimm_dsm_mem_addr(uint64_t dsm_mem_addr)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_DSM_MEM_ADDR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 87 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_dsm_mem_addr " "dsm memory address 0x%" PRIx64 "\n", dsm_mem_addr);
#line 1310 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_DSM_INFO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_DSM_INFO) || \
    false)

static inline void trace_acpi_nvdimm_dsm_info(uint32_t revision, uint32_t handle, uint32_t function)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_DSM_INFO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 88 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_dsm_info " "Revision 0x%" PRIx32 " Handle 0x%" PRIx32 " Function 0x%" PRIx32 "\n", revision, handle, function);
#line 1325 "trace/trace-hw_acpi.h"
        }
    }
}

#define TRACE_ACPI_NVDIMM_INVALID_REVISION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_NVDIMM_INVALID_REVISION) || \
    false)

static inline void trace_acpi_nvdimm_invalid_revision(uint32_t revision)
{
    if (trace_event_get_state(TRACE_ACPI_NVDIMM_INVALID_REVISION)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 89 "../hw/acpi/trace-events"
            qemu_log("acpi_nvdimm_invalid_revision " "Revision 0x%" PRIx32 " is not supported, expect 0x1" "\n", revision);
#line 1340 "trace/trace-hw_acpi.h"
        }
    }
}
#endif /* TRACE_HW_ACPI_GENERATED_TRACERS_H */
