/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_QAPI_COMMANDS_BLOCK_EXPORT_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_BLOCK_EXPORT_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_NBD_SERVER_START_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_NBD_SERVER_START_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_NBD_SERVER_ADD_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_NBD_SERVER_ADD_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_NBD_SERVER_REMOVE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_NBD_SERVER_REMOVE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_NBD_SERVER_STOP_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_NBD_SERVER_STOP_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_BLOCK_EXPORT_ADD_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_BLOCK_EXPORT_ADD_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_BLOCK_EXPORT_DEL_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_BLOCK_EXPORT_DEL_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_BLOCK_EXPORTS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_BLOCK_EXPORTS_EVENT;
extern uint16_t _TRACE_QMP_ENTER_NBD_SERVER_START_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_NBD_SERVER_START_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_NBD_SERVER_ADD_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_NBD_SERVER_ADD_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_NBD_SERVER_REMOVE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_NBD_SERVER_REMOVE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_NBD_SERVER_STOP_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_NBD_SERVER_STOP_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_BLOCK_EXPORT_ADD_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_BLOCK_EXPORT_ADD_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_BLOCK_EXPORT_DEL_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_BLOCK_EXPORT_DEL_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_BLOCK_EXPORTS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_BLOCK_EXPORTS_DSTATE;
#define TRACE_QMP_ENTER_NBD_SERVER_START_ENABLED 1
#define TRACE_QMP_EXIT_NBD_SERVER_START_ENABLED 1
#define TRACE_QMP_ENTER_NBD_SERVER_ADD_ENABLED 1
#define TRACE_QMP_EXIT_NBD_SERVER_ADD_ENABLED 1
#define TRACE_QMP_ENTER_NBD_SERVER_REMOVE_ENABLED 1
#define TRACE_QMP_EXIT_NBD_SERVER_REMOVE_ENABLED 1
#define TRACE_QMP_ENTER_NBD_SERVER_STOP_ENABLED 1
#define TRACE_QMP_EXIT_NBD_SERVER_STOP_ENABLED 1
#define TRACE_QMP_ENTER_BLOCK_EXPORT_ADD_ENABLED 1
#define TRACE_QMP_EXIT_BLOCK_EXPORT_ADD_ENABLED 1
#define TRACE_QMP_ENTER_BLOCK_EXPORT_DEL_ENABLED 1
#define TRACE_QMP_EXIT_BLOCK_EXPORT_DEL_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_BLOCK_EXPORTS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_BLOCK_EXPORTS_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_NBD_SERVER_START_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_NBD_SERVER_START) || \
    false)

static inline void trace_qmp_enter_nbd_server_start(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_NBD_SERVER_START)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_enter_nbd_server_start " "%s" "\n", json);
#line 65 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_NBD_SERVER_START_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_NBD_SERVER_START) || \
    false)

static inline void trace_qmp_exit_nbd_server_start(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_NBD_SERVER_START)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_exit_nbd_server_start " "%s %d" "\n", result, succeeded);
#line 80 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_NBD_SERVER_ADD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_NBD_SERVER_ADD) || \
    false)

static inline void trace_qmp_enter_nbd_server_add(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_NBD_SERVER_ADD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_enter_nbd_server_add " "%s" "\n", json);
#line 95 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_NBD_SERVER_ADD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_NBD_SERVER_ADD) || \
    false)

static inline void trace_qmp_exit_nbd_server_add(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_NBD_SERVER_ADD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_exit_nbd_server_add " "%s %d" "\n", result, succeeded);
#line 110 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_NBD_SERVER_REMOVE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_NBD_SERVER_REMOVE) || \
    false)

static inline void trace_qmp_enter_nbd_server_remove(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_NBD_SERVER_REMOVE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_enter_nbd_server_remove " "%s" "\n", json);
#line 125 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_NBD_SERVER_REMOVE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_NBD_SERVER_REMOVE) || \
    false)

static inline void trace_qmp_exit_nbd_server_remove(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_NBD_SERVER_REMOVE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_exit_nbd_server_remove " "%s %d" "\n", result, succeeded);
#line 140 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_NBD_SERVER_STOP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_NBD_SERVER_STOP) || \
    false)

static inline void trace_qmp_enter_nbd_server_stop(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_NBD_SERVER_STOP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_enter_nbd_server_stop " "%s" "\n", json);
#line 155 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_NBD_SERVER_STOP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_NBD_SERVER_STOP) || \
    false)

static inline void trace_qmp_exit_nbd_server_stop(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_NBD_SERVER_STOP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_exit_nbd_server_stop " "%s %d" "\n", result, succeeded);
#line 170 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_BLOCK_EXPORT_ADD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_BLOCK_EXPORT_ADD) || \
    false)

static inline void trace_qmp_enter_block_export_add(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_BLOCK_EXPORT_ADD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_enter_block_export_add " "%s" "\n", json);
#line 185 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_BLOCK_EXPORT_ADD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_BLOCK_EXPORT_ADD) || \
    false)

static inline void trace_qmp_exit_block_export_add(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_BLOCK_EXPORT_ADD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_exit_block_export_add " "%s %d" "\n", result, succeeded);
#line 200 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_BLOCK_EXPORT_DEL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_BLOCK_EXPORT_DEL) || \
    false)

static inline void trace_qmp_enter_block_export_del(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_BLOCK_EXPORT_DEL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_enter_block_export_del " "%s" "\n", json);
#line 215 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_BLOCK_EXPORT_DEL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_BLOCK_EXPORT_DEL) || \
    false)

static inline void trace_qmp_exit_block_export_del(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_BLOCK_EXPORT_DEL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_exit_block_export_del " "%s %d" "\n", result, succeeded);
#line 230 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_BLOCK_EXPORTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_BLOCK_EXPORTS) || \
    false)

static inline void trace_qmp_enter_query_block_exports(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_BLOCK_EXPORTS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_enter_query_block_exports " "%s" "\n", json);
#line 245 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_BLOCK_EXPORTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_BLOCK_EXPORTS) || \
    false)

static inline void trace_qmp_exit_query_block_exports(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_BLOCK_EXPORTS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "qapi/qapi-commands-block-export.trace-events"
            qemu_log("qmp_exit_query_block_exports " "%s %d" "\n", result, succeeded);
#line 260 "trace/trace-qapi_commands_block_export_trace_events.h"
        }
    }
}
#endif /* TRACE_QAPI_COMMANDS_BLOCK_EXPORT_TRACE_EVENTS_GENERATED_TRACERS_H */
