/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_QAPI_COMMANDS_ROCKER_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_ROCKER_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_EVENT;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE;
#define TRACE_QMP_ENTER_QUERY_ROCKER_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_QUERY_ROCKER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER) || \
    false)

static inline void trace_qmp_enter_query_rocker(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker " "%s" "\n", json);
#line 47 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER) || \
    false)

static inline void trace_qmp_exit_query_rocker(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker " "%s %d" "\n", result, succeeded);
#line 62 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER_PORTS) || \
    false)

static inline void trace_qmp_enter_query_rocker_ports(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER_PORTS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker_ports " "%s" "\n", json);
#line 77 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER_PORTS) || \
    false)

static inline void trace_qmp_exit_query_rocker_ports(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER_PORTS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker_ports " "%s %d" "\n", result, succeeded);
#line 92 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS) || \
    false)

static inline void trace_qmp_enter_query_rocker_of_dpa_flows(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker_of_dpa_flows " "%s" "\n", json);
#line 107 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS) || \
    false)

static inline void trace_qmp_exit_query_rocker_of_dpa_flows(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker_of_dpa_flows " "%s %d" "\n", result, succeeded);
#line 122 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS) || \
    false)

static inline void trace_qmp_enter_query_rocker_of_dpa_groups(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker_of_dpa_groups " "%s" "\n", json);
#line 137 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS) || \
    false)

static inline void trace_qmp_exit_query_rocker_of_dpa_groups(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker_of_dpa_groups " "%s %d" "\n", result, succeeded);
#line 152 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}
#endif /* TRACE_QAPI_COMMANDS_ROCKER_TRACE_EVENTS_GENERATED_TRACERS_H */
