/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_QAPI_COMMANDS_MACHINE_S390X_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_MACHINE_S390X_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_SET_CPU_TOPOLOGY_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_SET_CPU_TOPOLOGY_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_S390X_CPU_POLARIZATION_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_S390X_CPU_POLARIZATION_EVENT;
extern uint16_t _TRACE_QMP_ENTER_SET_CPU_TOPOLOGY_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_SET_CPU_TOPOLOGY_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_S390X_CPU_POLARIZATION_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_S390X_CPU_POLARIZATION_DSTATE;
#define TRACE_QMP_ENTER_SET_CPU_TOPOLOGY_ENABLED 1
#define TRACE_QMP_EXIT_SET_CPU_TOPOLOGY_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_S390X_CPU_POLARIZATION_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_S390X_CPU_POLARIZATION_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_SET_CPU_TOPOLOGY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_SET_CPU_TOPOLOGY) || \
    false)

static inline void trace_qmp_enter_set_cpu_topology(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_SET_CPU_TOPOLOGY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-machine-s390x.trace-events"
            qemu_log("qmp_enter_set_cpu_topology " "%s" "\n", json);
#line 35 "trace/trace-qapi_commands_machine_s390x_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_SET_CPU_TOPOLOGY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_SET_CPU_TOPOLOGY) || \
    false)

static inline void trace_qmp_exit_set_cpu_topology(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_SET_CPU_TOPOLOGY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-machine-s390x.trace-events"
            qemu_log("qmp_exit_set_cpu_topology " "%s %d" "\n", result, succeeded);
#line 50 "trace/trace-qapi_commands_machine_s390x_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_QUERY_S390X_CPU_POLARIZATION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_S390X_CPU_POLARIZATION) || \
    false)

static inline void trace_qmp_enter_query_s390x_cpu_polarization(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_S390X_CPU_POLARIZATION)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-machine-s390x.trace-events"
            qemu_log("qmp_enter_query_s390x_cpu_polarization " "%s" "\n", json);
#line 65 "trace/trace-qapi_commands_machine_s390x_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_S390X_CPU_POLARIZATION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_S390X_CPU_POLARIZATION) || \
    false)

static inline void trace_qmp_exit_query_s390x_cpu_polarization(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_S390X_CPU_POLARIZATION)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-machine-s390x.trace-events"
            qemu_log("qmp_exit_query_s390x_cpu_polarization " "%s %d" "\n", result, succeeded);
#line 80 "trace/trace-qapi_commands_machine_s390x_trace_events.h"
        }
    }
}
#endif /* TRACE_QAPI_COMMANDS_MACHINE_S390X_TRACE_EVENTS_GENERATED_TRACERS_H */
