/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-hw_uefi.h"

uint16_t _TRACE_UEFI_REG_READ_DSTATE;
uint16_t _TRACE_UEFI_REG_WRITE_DSTATE;
uint16_t _TRACE_UEFI_HARD_RESET_DSTATE;
uint16_t _TRACE_UEFI_VARIABLE_DSTATE;
uint16_t _TRACE_UEFI_STATUS_DSTATE;
uint16_t _TRACE_UEFI_EVENT_DSTATE;
uint16_t _TRACE_UEFI_VARS_PROTO_CMD_DSTATE;
uint16_t _TRACE_UEFI_VARS_SECURITY_VIOLATION_DSTATE;
uint16_t _TRACE_UEFI_VARS_POLICY_CMD_DSTATE;
uint16_t _TRACE_UEFI_VARS_POLICY_DENY_DSTATE;
TraceEvent _TRACE_UEFI_REG_READ_EVENT = {
    .id = 0,
    .name = "uefi_reg_read",
    .sstate = TRACE_UEFI_REG_READ_ENABLED,
    .dstate = &_TRACE_UEFI_REG_READ_DSTATE
};
TraceEvent _TRACE_UEFI_REG_WRITE_EVENT = {
    .id = 0,
    .name = "uefi_reg_write",
    .sstate = TRACE_UEFI_REG_WRITE_ENABLED,
    .dstate = &_TRACE_UEFI_REG_WRITE_DSTATE
};
TraceEvent _TRACE_UEFI_HARD_RESET_EVENT = {
    .id = 0,
    .name = "uefi_hard_reset",
    .sstate = TRACE_UEFI_HARD_RESET_ENABLED,
    .dstate = &_TRACE_UEFI_HARD_RESET_DSTATE
};
TraceEvent _TRACE_UEFI_VARIABLE_EVENT = {
    .id = 0,
    .name = "uefi_variable",
    .sstate = TRACE_UEFI_VARIABLE_ENABLED,
    .dstate = &_TRACE_UEFI_VARIABLE_DSTATE
};
TraceEvent _TRACE_UEFI_STATUS_EVENT = {
    .id = 0,
    .name = "uefi_status",
    .sstate = TRACE_UEFI_STATUS_ENABLED,
    .dstate = &_TRACE_UEFI_STATUS_DSTATE
};
TraceEvent _TRACE_UEFI_EVENT_EVENT = {
    .id = 0,
    .name = "uefi_event",
    .sstate = TRACE_UEFI_EVENT_ENABLED,
    .dstate = &_TRACE_UEFI_EVENT_DSTATE
};
TraceEvent _TRACE_UEFI_VARS_PROTO_CMD_EVENT = {
    .id = 0,
    .name = "uefi_vars_proto_cmd",
    .sstate = TRACE_UEFI_VARS_PROTO_CMD_ENABLED,
    .dstate = &_TRACE_UEFI_VARS_PROTO_CMD_DSTATE
};
TraceEvent _TRACE_UEFI_VARS_SECURITY_VIOLATION_EVENT = {
    .id = 0,
    .name = "uefi_vars_security_violation",
    .sstate = TRACE_UEFI_VARS_SECURITY_VIOLATION_ENABLED,
    .dstate = &_TRACE_UEFI_VARS_SECURITY_VIOLATION_DSTATE
};
TraceEvent _TRACE_UEFI_VARS_POLICY_CMD_EVENT = {
    .id = 0,
    .name = "uefi_vars_policy_cmd",
    .sstate = TRACE_UEFI_VARS_POLICY_CMD_ENABLED,
    .dstate = &_TRACE_UEFI_VARS_POLICY_CMD_DSTATE
};
TraceEvent _TRACE_UEFI_VARS_POLICY_DENY_EVENT = {
    .id = 0,
    .name = "uefi_vars_policy_deny",
    .sstate = TRACE_UEFI_VARS_POLICY_DENY_ENABLED,
    .dstate = &_TRACE_UEFI_VARS_POLICY_DENY_DSTATE
};
TraceEvent *hw_uefi_trace_events[] = {
    &_TRACE_UEFI_REG_READ_EVENT,
    &_TRACE_UEFI_REG_WRITE_EVENT,
    &_TRACE_UEFI_HARD_RESET_EVENT,
    &_TRACE_UEFI_VARIABLE_EVENT,
    &_TRACE_UEFI_STATUS_EVENT,
    &_TRACE_UEFI_EVENT_EVENT,
    &_TRACE_UEFI_VARS_PROTO_CMD_EVENT,
    &_TRACE_UEFI_VARS_SECURITY_VIOLATION_EVENT,
    &_TRACE_UEFI_VARS_POLICY_CMD_EVENT,
    &_TRACE_UEFI_VARS_POLICY_DENY_EVENT,
  NULL,
};

static void trace_hw_uefi_register_events(void)
{
    trace_event_register_group(hw_uefi_trace_events);
}
trace_init(trace_hw_uefi_register_events)
