/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-hw_sensor.h"

uint16_t _TRACE_TMP105_READ_DSTATE;
uint16_t _TRACE_TMP105_WRITE_DSTATE;
uint16_t _TRACE_TMP105_WRITE_SHUTDOWN_DSTATE;
TraceEvent _TRACE_TMP105_READ_EVENT = {
    .id = 0,
    .name = "tmp105_read",
    .sstate = TRACE_TMP105_READ_ENABLED,
    .dstate = &_TRACE_TMP105_READ_DSTATE
};
TraceEvent _TRACE_TMP105_WRITE_EVENT = {
    .id = 0,
    .name = "tmp105_write",
    .sstate = TRACE_TMP105_WRITE_ENABLED,
    .dstate = &_TRACE_TMP105_WRITE_DSTATE
};
TraceEvent _TRACE_TMP105_WRITE_SHUTDOWN_EVENT = {
    .id = 0,
    .name = "tmp105_write_shutdown",
    .sstate = TRACE_TMP105_WRITE_SHUTDOWN_ENABLED,
    .dstate = &_TRACE_TMP105_WRITE_SHUTDOWN_DSTATE
};
TraceEvent *hw_sensor_trace_events[] = {
    &_TRACE_TMP105_READ_EVENT,
    &_TRACE_TMP105_WRITE_EVENT,
    &_TRACE_TMP105_WRITE_SHUTDOWN_EVENT,
  NULL,
};

static void trace_hw_sensor_register_events(void)
{
    trace_event_register_group(hw_sensor_trace_events);
}
trace_init(trace_hw_sensor_register_events)
