/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_SD_GENERATED_TRACERS_H
#define TRACE_HW_SD_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_ALLWINNER_SDHOST_SET_INSERTED_EVENT;
extern TraceEvent _TRACE_ALLWINNER_SDHOST_PROCESS_DESC_EVENT;
extern TraceEvent _TRACE_ALLWINNER_SDHOST_READ_EVENT;
extern TraceEvent _TRACE_ALLWINNER_SDHOST_WRITE_EVENT;
extern TraceEvent _TRACE_ALLWINNER_SDHOST_UPDATE_IRQ_EVENT;
extern TraceEvent _TRACE_BCM2835_SDHOST_READ_EVENT;
extern TraceEvent _TRACE_BCM2835_SDHOST_WRITE_EVENT;
extern TraceEvent _TRACE_BCM2835_SDHOST_EDM_CHANGE_EVENT;
extern TraceEvent _TRACE_BCM2835_SDHOST_UPDATE_IRQ_EVENT;
extern TraceEvent _TRACE_SDBUS_COMMAND_EVENT;
extern TraceEvent _TRACE_SDBUS_READ_EVENT;
extern TraceEvent _TRACE_SDBUS_WRITE_EVENT;
extern TraceEvent _TRACE_SDBUS_SET_VOLTAGE_EVENT;
extern TraceEvent _TRACE_SDBUS_GET_DAT_LINES_EVENT;
extern TraceEvent _TRACE_SDBUS_GET_CMD_LINE_EVENT;
extern TraceEvent _TRACE_SDHCI_SET_INSERTED_EVENT;
extern TraceEvent _TRACE_SDHCI_SEND_COMMAND_EVENT;
extern TraceEvent _TRACE_SDHCI_ERROR_EVENT;
extern TraceEvent _TRACE_SDHCI_RESPONSE4_EVENT;
extern TraceEvent _TRACE_SDHCI_RESPONSE16_EVENT;
extern TraceEvent _TRACE_SDHCI_END_TRANSFER_EVENT;
extern TraceEvent _TRACE_SDHCI_ADMA_EVENT;
extern TraceEvent _TRACE_SDHCI_ADMA_LOOP_EVENT;
extern TraceEvent _TRACE_SDHCI_ADMA_TRANSFER_COMPLETED_EVENT;
extern TraceEvent _TRACE_SDHCI_ACCESS_EVENT;
extern TraceEvent _TRACE_SDHCI_READ_DATAPORT_EVENT;
extern TraceEvent _TRACE_SDHCI_WRITE_DATAPORT_EVENT;
extern TraceEvent _TRACE_SDHCI_CAPAREG_EVENT;
extern TraceEvent _TRACE_SDCARD_NORMAL_COMMAND_EVENT;
extern TraceEvent _TRACE_SDCARD_APP_COMMAND_EVENT;
extern TraceEvent _TRACE_SDCARD_RESPONSE_EVENT;
extern TraceEvent _TRACE_SDCARD_POWERUP_EVENT;
extern TraceEvent _TRACE_SDCARD_INQUIRY_CMD41_EVENT;
extern TraceEvent _TRACE_SDCARD_RESET_EVENT;
extern TraceEvent _TRACE_SDCARD_SET_RCA_EVENT;
extern TraceEvent _TRACE_SDCARD_SET_BLOCKLEN_EVENT;
extern TraceEvent _TRACE_SDCARD_SET_BLOCK_COUNT_EVENT;
extern TraceEvent _TRACE_SDCARD_INSERTED_EVENT;
extern TraceEvent _TRACE_SDCARD_EJECTED_EVENT;
extern TraceEvent _TRACE_SDCARD_ERASE_EVENT;
extern TraceEvent _TRACE_SDCARD_LOCK_EVENT;
extern TraceEvent _TRACE_SDCARD_UNLOCK_EVENT;
extern TraceEvent _TRACE_SDCARD_REQ_ADDR_EVENT;
extern TraceEvent _TRACE_SDCARD_READ_BLOCK_EVENT;
extern TraceEvent _TRACE_SDCARD_WRITE_BLOCK_EVENT;
extern TraceEvent _TRACE_SDCARD_WRITE_DATA_EVENT;
extern TraceEvent _TRACE_SDCARD_READ_DATA_EVENT;
extern TraceEvent _TRACE_SDCARD_SET_VOLTAGE_EVENT;
extern TraceEvent _TRACE_SDCARD_EXT_CSD_UPDATE_EVENT;
extern TraceEvent _TRACE_SDCARD_SWITCH_EVENT;
extern TraceEvent _TRACE_SDCARD_RPMB_READ_BLOCK_EVENT;
extern TraceEvent _TRACE_SDCARD_RPMB_WRITE_BLOCK_EVENT;
extern TraceEvent _TRACE_PL181_COMMAND_SEND_EVENT;
extern TraceEvent _TRACE_PL181_COMMAND_SENT_EVENT;
extern TraceEvent _TRACE_PL181_COMMAND_RESPONSE_PENDING_EVENT;
extern TraceEvent _TRACE_PL181_COMMAND_TIMEOUT_EVENT;
extern TraceEvent _TRACE_PL181_FIFO_PUSH_EVENT;
extern TraceEvent _TRACE_PL181_FIFO_POP_EVENT;
extern TraceEvent _TRACE_PL181_FIFO_TRANSFER_COMPLETE_EVENT;
extern TraceEvent _TRACE_PL181_DATA_ENGINE_IDLE_EVENT;
extern TraceEvent _TRACE_ASPEED_SDHCI_READ_EVENT;
extern TraceEvent _TRACE_ASPEED_SDHCI_WRITE_EVENT;
extern uint16_t _TRACE_ALLWINNER_SDHOST_SET_INSERTED_DSTATE;
extern uint16_t _TRACE_ALLWINNER_SDHOST_PROCESS_DESC_DSTATE;
extern uint16_t _TRACE_ALLWINNER_SDHOST_READ_DSTATE;
extern uint16_t _TRACE_ALLWINNER_SDHOST_WRITE_DSTATE;
extern uint16_t _TRACE_ALLWINNER_SDHOST_UPDATE_IRQ_DSTATE;
extern uint16_t _TRACE_BCM2835_SDHOST_READ_DSTATE;
extern uint16_t _TRACE_BCM2835_SDHOST_WRITE_DSTATE;
extern uint16_t _TRACE_BCM2835_SDHOST_EDM_CHANGE_DSTATE;
extern uint16_t _TRACE_BCM2835_SDHOST_UPDATE_IRQ_DSTATE;
extern uint16_t _TRACE_SDBUS_COMMAND_DSTATE;
extern uint16_t _TRACE_SDBUS_READ_DSTATE;
extern uint16_t _TRACE_SDBUS_WRITE_DSTATE;
extern uint16_t _TRACE_SDBUS_SET_VOLTAGE_DSTATE;
extern uint16_t _TRACE_SDBUS_GET_DAT_LINES_DSTATE;
extern uint16_t _TRACE_SDBUS_GET_CMD_LINE_DSTATE;
extern uint16_t _TRACE_SDHCI_SET_INSERTED_DSTATE;
extern uint16_t _TRACE_SDHCI_SEND_COMMAND_DSTATE;
extern uint16_t _TRACE_SDHCI_ERROR_DSTATE;
extern uint16_t _TRACE_SDHCI_RESPONSE4_DSTATE;
extern uint16_t _TRACE_SDHCI_RESPONSE16_DSTATE;
extern uint16_t _TRACE_SDHCI_END_TRANSFER_DSTATE;
extern uint16_t _TRACE_SDHCI_ADMA_DSTATE;
extern uint16_t _TRACE_SDHCI_ADMA_LOOP_DSTATE;
extern uint16_t _TRACE_SDHCI_ADMA_TRANSFER_COMPLETED_DSTATE;
extern uint16_t _TRACE_SDHCI_ACCESS_DSTATE;
extern uint16_t _TRACE_SDHCI_READ_DATAPORT_DSTATE;
extern uint16_t _TRACE_SDHCI_WRITE_DATAPORT_DSTATE;
extern uint16_t _TRACE_SDHCI_CAPAREG_DSTATE;
extern uint16_t _TRACE_SDCARD_NORMAL_COMMAND_DSTATE;
extern uint16_t _TRACE_SDCARD_APP_COMMAND_DSTATE;
extern uint16_t _TRACE_SDCARD_RESPONSE_DSTATE;
extern uint16_t _TRACE_SDCARD_POWERUP_DSTATE;
extern uint16_t _TRACE_SDCARD_INQUIRY_CMD41_DSTATE;
extern uint16_t _TRACE_SDCARD_RESET_DSTATE;
extern uint16_t _TRACE_SDCARD_SET_RCA_DSTATE;
extern uint16_t _TRACE_SDCARD_SET_BLOCKLEN_DSTATE;
extern uint16_t _TRACE_SDCARD_SET_BLOCK_COUNT_DSTATE;
extern uint16_t _TRACE_SDCARD_INSERTED_DSTATE;
extern uint16_t _TRACE_SDCARD_EJECTED_DSTATE;
extern uint16_t _TRACE_SDCARD_ERASE_DSTATE;
extern uint16_t _TRACE_SDCARD_LOCK_DSTATE;
extern uint16_t _TRACE_SDCARD_UNLOCK_DSTATE;
extern uint16_t _TRACE_SDCARD_REQ_ADDR_DSTATE;
extern uint16_t _TRACE_SDCARD_READ_BLOCK_DSTATE;
extern uint16_t _TRACE_SDCARD_WRITE_BLOCK_DSTATE;
extern uint16_t _TRACE_SDCARD_WRITE_DATA_DSTATE;
extern uint16_t _TRACE_SDCARD_READ_DATA_DSTATE;
extern uint16_t _TRACE_SDCARD_SET_VOLTAGE_DSTATE;
extern uint16_t _TRACE_SDCARD_EXT_CSD_UPDATE_DSTATE;
extern uint16_t _TRACE_SDCARD_SWITCH_DSTATE;
extern uint16_t _TRACE_SDCARD_RPMB_READ_BLOCK_DSTATE;
extern uint16_t _TRACE_SDCARD_RPMB_WRITE_BLOCK_DSTATE;
extern uint16_t _TRACE_PL181_COMMAND_SEND_DSTATE;
extern uint16_t _TRACE_PL181_COMMAND_SENT_DSTATE;
extern uint16_t _TRACE_PL181_COMMAND_RESPONSE_PENDING_DSTATE;
extern uint16_t _TRACE_PL181_COMMAND_TIMEOUT_DSTATE;
extern uint16_t _TRACE_PL181_FIFO_PUSH_DSTATE;
extern uint16_t _TRACE_PL181_FIFO_POP_DSTATE;
extern uint16_t _TRACE_PL181_FIFO_TRANSFER_COMPLETE_DSTATE;
extern uint16_t _TRACE_PL181_DATA_ENGINE_IDLE_DSTATE;
extern uint16_t _TRACE_ASPEED_SDHCI_READ_DSTATE;
extern uint16_t _TRACE_ASPEED_SDHCI_WRITE_DSTATE;
#define TRACE_ALLWINNER_SDHOST_SET_INSERTED_ENABLED 1
#define TRACE_ALLWINNER_SDHOST_PROCESS_DESC_ENABLED 1
#define TRACE_ALLWINNER_SDHOST_READ_ENABLED 1
#define TRACE_ALLWINNER_SDHOST_WRITE_ENABLED 1
#define TRACE_ALLWINNER_SDHOST_UPDATE_IRQ_ENABLED 1
#define TRACE_BCM2835_SDHOST_READ_ENABLED 1
#define TRACE_BCM2835_SDHOST_WRITE_ENABLED 1
#define TRACE_BCM2835_SDHOST_EDM_CHANGE_ENABLED 1
#define TRACE_BCM2835_SDHOST_UPDATE_IRQ_ENABLED 1
#define TRACE_SDBUS_COMMAND_ENABLED 1
#define TRACE_SDBUS_READ_ENABLED 1
#define TRACE_SDBUS_WRITE_ENABLED 1
#define TRACE_SDBUS_SET_VOLTAGE_ENABLED 1
#define TRACE_SDBUS_GET_DAT_LINES_ENABLED 1
#define TRACE_SDBUS_GET_CMD_LINE_ENABLED 1
#define TRACE_SDHCI_SET_INSERTED_ENABLED 1
#define TRACE_SDHCI_SEND_COMMAND_ENABLED 1
#define TRACE_SDHCI_ERROR_ENABLED 1
#define TRACE_SDHCI_RESPONSE4_ENABLED 1
#define TRACE_SDHCI_RESPONSE16_ENABLED 1
#define TRACE_SDHCI_END_TRANSFER_ENABLED 1
#define TRACE_SDHCI_ADMA_ENABLED 1
#define TRACE_SDHCI_ADMA_LOOP_ENABLED 1
#define TRACE_SDHCI_ADMA_TRANSFER_COMPLETED_ENABLED 1
#define TRACE_SDHCI_ACCESS_ENABLED 1
#define TRACE_SDHCI_READ_DATAPORT_ENABLED 1
#define TRACE_SDHCI_WRITE_DATAPORT_ENABLED 1
#define TRACE_SDHCI_CAPAREG_ENABLED 1
#define TRACE_SDCARD_NORMAL_COMMAND_ENABLED 1
#define TRACE_SDCARD_APP_COMMAND_ENABLED 1
#define TRACE_SDCARD_RESPONSE_ENABLED 1
#define TRACE_SDCARD_POWERUP_ENABLED 1
#define TRACE_SDCARD_INQUIRY_CMD41_ENABLED 1
#define TRACE_SDCARD_RESET_ENABLED 1
#define TRACE_SDCARD_SET_RCA_ENABLED 1
#define TRACE_SDCARD_SET_BLOCKLEN_ENABLED 1
#define TRACE_SDCARD_SET_BLOCK_COUNT_ENABLED 1
#define TRACE_SDCARD_INSERTED_ENABLED 1
#define TRACE_SDCARD_EJECTED_ENABLED 1
#define TRACE_SDCARD_ERASE_ENABLED 1
#define TRACE_SDCARD_LOCK_ENABLED 1
#define TRACE_SDCARD_UNLOCK_ENABLED 1
#define TRACE_SDCARD_REQ_ADDR_ENABLED 1
#define TRACE_SDCARD_READ_BLOCK_ENABLED 1
#define TRACE_SDCARD_WRITE_BLOCK_ENABLED 1
#define TRACE_SDCARD_WRITE_DATA_ENABLED 1
#define TRACE_SDCARD_READ_DATA_ENABLED 1
#define TRACE_SDCARD_SET_VOLTAGE_ENABLED 1
#define TRACE_SDCARD_EXT_CSD_UPDATE_ENABLED 1
#define TRACE_SDCARD_SWITCH_ENABLED 1
#define TRACE_SDCARD_RPMB_READ_BLOCK_ENABLED 1
#define TRACE_SDCARD_RPMB_WRITE_BLOCK_ENABLED 1
#define TRACE_PL181_COMMAND_SEND_ENABLED 1
#define TRACE_PL181_COMMAND_SENT_ENABLED 1
#define TRACE_PL181_COMMAND_RESPONSE_PENDING_ENABLED 1
#define TRACE_PL181_COMMAND_TIMEOUT_ENABLED 1
#define TRACE_PL181_FIFO_PUSH_ENABLED 1
#define TRACE_PL181_FIFO_POP_ENABLED 1
#define TRACE_PL181_FIFO_TRANSFER_COMPLETE_ENABLED 1
#define TRACE_PL181_DATA_ENGINE_IDLE_ENABLED 1
#define TRACE_ASPEED_SDHCI_READ_ENABLED 1
#define TRACE_ASPEED_SDHCI_WRITE_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_ALLWINNER_SDHOST_SET_INSERTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ALLWINNER_SDHOST_SET_INSERTED) || \
    false)

static inline void trace_allwinner_sdhost_set_inserted(bool inserted)
{
    if (trace_event_get_state(TRACE_ALLWINNER_SDHOST_SET_INSERTED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/sd/trace-events"
            qemu_log("allwinner_sdhost_set_inserted " "inserted %u" "\n", inserted);
#line 209 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_ALLWINNER_SDHOST_PROCESS_DESC_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ALLWINNER_SDHOST_PROCESS_DESC) || \
    false)

static inline void trace_allwinner_sdhost_process_desc(uint64_t desc_addr, uint32_t desc_size, bool is_write, uint32_t max_bytes)
{
    if (trace_event_get_state(TRACE_ALLWINNER_SDHOST_PROCESS_DESC)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../hw/sd/trace-events"
            qemu_log("allwinner_sdhost_process_desc " "desc_addr 0x%" PRIx64 " desc_size %" PRIu32 " is_write %u max_bytes %" PRIu32 "\n", desc_addr, desc_size, is_write, max_bytes);
#line 224 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_ALLWINNER_SDHOST_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ALLWINNER_SDHOST_READ) || \
    false)

static inline void trace_allwinner_sdhost_read(uint64_t offset, uint64_t data, unsigned size)
{
    if (trace_event_get_state(TRACE_ALLWINNER_SDHOST_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../hw/sd/trace-events"
            qemu_log("allwinner_sdhost_read " "offset 0x%" PRIx64 " data 0x%" PRIx64 " size %" PRIu32 "\n", offset, data, size);
#line 239 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_ALLWINNER_SDHOST_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ALLWINNER_SDHOST_WRITE) || \
    false)

static inline void trace_allwinner_sdhost_write(uint64_t offset, uint64_t data, unsigned size)
{
    if (trace_event_get_state(TRACE_ALLWINNER_SDHOST_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../hw/sd/trace-events"
            qemu_log("allwinner_sdhost_write " "offset 0x%" PRIx64 " data 0x%" PRIx64 " size %" PRIu32 "\n", offset, data, size);
#line 254 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_ALLWINNER_SDHOST_UPDATE_IRQ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ALLWINNER_SDHOST_UPDATE_IRQ) || \
    false)

static inline void trace_allwinner_sdhost_update_irq(uint32_t irq)
{
    if (trace_event_get_state(TRACE_ALLWINNER_SDHOST_UPDATE_IRQ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../hw/sd/trace-events"
            qemu_log("allwinner_sdhost_update_irq " "IRQ bits 0x%" PRIx32 "\n", irq);
#line 269 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_BCM2835_SDHOST_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BCM2835_SDHOST_READ) || \
    false)

static inline void trace_bcm2835_sdhost_read(uint64_t offset, uint64_t data, unsigned size)
{
    if (trace_event_get_state(TRACE_BCM2835_SDHOST_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "../hw/sd/trace-events"
            qemu_log("bcm2835_sdhost_read " "offset 0x%" PRIx64 " data 0x%" PRIx64 " size %u" "\n", offset, data, size);
#line 284 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_BCM2835_SDHOST_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BCM2835_SDHOST_WRITE) || \
    false)

static inline void trace_bcm2835_sdhost_write(uint64_t offset, uint64_t data, unsigned size)
{
    if (trace_event_get_state(TRACE_BCM2835_SDHOST_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../hw/sd/trace-events"
            qemu_log("bcm2835_sdhost_write " "offset 0x%" PRIx64 " data 0x%" PRIx64 " size %u" "\n", offset, data, size);
#line 299 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_BCM2835_SDHOST_EDM_CHANGE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BCM2835_SDHOST_EDM_CHANGE) || \
    false)

static inline void trace_bcm2835_sdhost_edm_change(const char *why, uint32_t edm)
{
    if (trace_event_get_state(TRACE_BCM2835_SDHOST_EDM_CHANGE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../hw/sd/trace-events"
            qemu_log("bcm2835_sdhost_edm_change " "(%s) EDM now 0x%x" "\n", why, edm);
#line 314 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_BCM2835_SDHOST_UPDATE_IRQ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BCM2835_SDHOST_UPDATE_IRQ) || \
    false)

static inline void trace_bcm2835_sdhost_update_irq(uint32_t irq)
{
    if (trace_event_get_state(TRACE_BCM2835_SDHOST_UPDATE_IRQ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../hw/sd/trace-events"
            qemu_log("bcm2835_sdhost_update_irq " "IRQ bits 0x%x" "\n", irq);
#line 329 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDBUS_COMMAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDBUS_COMMAND) || \
    false)

static inline void trace_sdbus_command(const char *bus_name, uint8_t cmd, uint32_t arg)
{
    if (trace_event_get_state(TRACE_SDBUS_COMMAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../hw/sd/trace-events"
            qemu_log("sdbus_command " "@%s CMD%02d arg 0x%08x" "\n", bus_name, cmd, arg);
#line 344 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDBUS_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDBUS_READ) || \
    false)

static inline void trace_sdbus_read(const char *bus_name, uint8_t value)
{
    if (trace_event_get_state(TRACE_SDBUS_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../hw/sd/trace-events"
            qemu_log("sdbus_read " "@%s value 0x%02x" "\n", bus_name, value);
#line 359 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDBUS_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDBUS_WRITE) || \
    false)

static inline void trace_sdbus_write(const char *bus_name, uint8_t value)
{
    if (trace_event_get_state(TRACE_SDBUS_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "../hw/sd/trace-events"
            qemu_log("sdbus_write " "@%s value 0x%02x" "\n", bus_name, value);
#line 374 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDBUS_SET_VOLTAGE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDBUS_SET_VOLTAGE) || \
    false)

static inline void trace_sdbus_set_voltage(const char *bus_name, uint16_t millivolts)
{
    if (trace_event_get_state(TRACE_SDBUS_SET_VOLTAGE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 20 "../hw/sd/trace-events"
            qemu_log("sdbus_set_voltage " "@%s %u (mV)" "\n", bus_name, millivolts);
#line 389 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDBUS_GET_DAT_LINES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDBUS_GET_DAT_LINES) || \
    false)

static inline void trace_sdbus_get_dat_lines(const char *bus_name, uint8_t dat_lines)
{
    if (trace_event_get_state(TRACE_SDBUS_GET_DAT_LINES)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 21 "../hw/sd/trace-events"
            qemu_log("sdbus_get_dat_lines " "@%s dat_lines: %u" "\n", bus_name, dat_lines);
#line 404 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDBUS_GET_CMD_LINE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDBUS_GET_CMD_LINE) || \
    false)

static inline void trace_sdbus_get_cmd_line(const char *bus_name, bool cmd_line)
{
    if (trace_event_get_state(TRACE_SDBUS_GET_CMD_LINE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "../hw/sd/trace-events"
            qemu_log("sdbus_get_cmd_line " "@%s cmd_line: %u" "\n", bus_name, cmd_line);
#line 419 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_SET_INSERTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_SET_INSERTED) || \
    false)

static inline void trace_sdhci_set_inserted(const char *level)
{
    if (trace_event_get_state(TRACE_SDHCI_SET_INSERTED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 25 "../hw/sd/trace-events"
            qemu_log("sdhci_set_inserted " "card state changed: %s" "\n", level);
#line 434 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_SEND_COMMAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_SEND_COMMAND) || \
    false)

static inline void trace_sdhci_send_command(uint8_t cmd, uint32_t arg)
{
    if (trace_event_get_state(TRACE_SDHCI_SEND_COMMAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 26 "../hw/sd/trace-events"
            qemu_log("sdhci_send_command " "CMD%02u ARG[0x%08x]" "\n", cmd, arg);
#line 449 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_ERROR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_ERROR) || \
    false)

static inline void trace_sdhci_error(const char *msg)
{
    if (trace_event_get_state(TRACE_SDHCI_ERROR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 27 "../hw/sd/trace-events"
            qemu_log("sdhci_error " "%s" "\n", msg);
#line 464 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_RESPONSE4_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_RESPONSE4) || \
    false)

static inline void trace_sdhci_response4(uint32_t r0)
{
    if (trace_event_get_state(TRACE_SDHCI_RESPONSE4)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 28 "../hw/sd/trace-events"
            qemu_log("sdhci_response4 " "RSPREG[31..0]=0x%08x" "\n", r0);
#line 479 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_RESPONSE16_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_RESPONSE16) || \
    false)

static inline void trace_sdhci_response16(uint32_t r3, uint32_t r2, uint32_t r1, uint32_t r0)
{
    if (trace_event_get_state(TRACE_SDHCI_RESPONSE16)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 29 "../hw/sd/trace-events"
            qemu_log("sdhci_response16 " "RSPREG[127..96]=0x%08x, RSPREG[95..64]=0x%08x, RSPREG[63..32]=0x%08x, RSPREG[31..0]=0x%08x" "\n", r3, r2, r1, r0);
#line 494 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_END_TRANSFER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_END_TRANSFER) || \
    false)

static inline void trace_sdhci_end_transfer(uint8_t cmd, uint32_t arg)
{
    if (trace_event_get_state(TRACE_SDHCI_END_TRANSFER)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 30 "../hw/sd/trace-events"
            qemu_log("sdhci_end_transfer " "Automatically issue CMD%02u 0x%08x" "\n", cmd, arg);
#line 509 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_ADMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_ADMA) || \
    false)

static inline void trace_sdhci_adma(const char *desc, uint32_t sysad)
{
    if (trace_event_get_state(TRACE_SDHCI_ADMA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 31 "../hw/sd/trace-events"
            qemu_log("sdhci_adma " "%s: admasysaddr=0x%" PRIx32 "\n", desc, sysad);
#line 524 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_ADMA_LOOP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_ADMA_LOOP) || \
    false)

static inline void trace_sdhci_adma_loop(uint64_t addr, uint16_t length, uint8_t attr)
{
    if (trace_event_get_state(TRACE_SDHCI_ADMA_LOOP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 32 "../hw/sd/trace-events"
            qemu_log("sdhci_adma_loop " "addr=0x%08" PRIx64 ", len=%d, attr=0x%x" "\n", addr, length, attr);
#line 539 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_ADMA_TRANSFER_COMPLETED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_ADMA_TRANSFER_COMPLETED) || \
    false)

static inline void trace_sdhci_adma_transfer_completed(void)
{
    if (trace_event_get_state(TRACE_SDHCI_ADMA_TRANSFER_COMPLETED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 33 "../hw/sd/trace-events"
            qemu_log("sdhci_adma_transfer_completed " "" "\n");
#line 554 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_ACCESS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_ACCESS) || \
    false)

static inline void trace_sdhci_access(const char *access, unsigned int size, uint64_t offset, const char *dir, uint64_t val, uint64_t val2)
{
    if (trace_event_get_state(TRACE_SDHCI_ACCESS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 34 "../hw/sd/trace-events"
            qemu_log("sdhci_access " "%s%u: addr[0x%04" PRIx64 "] %s 0x%08" PRIx64 " (%" PRIu64 ")" "\n", access, size, offset, dir, val, val2);
#line 569 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_READ_DATAPORT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_READ_DATAPORT) || \
    false)

static inline void trace_sdhci_read_dataport(uint16_t data_count)
{
    if (trace_event_get_state(TRACE_SDHCI_READ_DATAPORT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 35 "../hw/sd/trace-events"
            qemu_log("sdhci_read_dataport " "all %u bytes of data have been read from input buffer" "\n", data_count);
#line 584 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_WRITE_DATAPORT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_WRITE_DATAPORT) || \
    false)

static inline void trace_sdhci_write_dataport(uint16_t data_count)
{
    if (trace_event_get_state(TRACE_SDHCI_WRITE_DATAPORT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 36 "../hw/sd/trace-events"
            qemu_log("sdhci_write_dataport " "write buffer filled with %u bytes of data" "\n", data_count);
#line 599 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDHCI_CAPAREG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDHCI_CAPAREG) || \
    false)

static inline void trace_sdhci_capareg(const char *desc, uint16_t val)
{
    if (trace_event_get_state(TRACE_SDHCI_CAPAREG)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 37 "../hw/sd/trace-events"
            qemu_log("sdhci_capareg " "%s: %u" "\n", desc, val);
#line 614 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_NORMAL_COMMAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_NORMAL_COMMAND) || \
    false)

static inline void trace_sdcard_normal_command(const char *proto, const char *cmd_desc, uint8_t cmd, uint32_t arg, const char *mode, const char *state)
{
    if (trace_event_get_state(TRACE_SDCARD_NORMAL_COMMAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 40 "../hw/sd/trace-events"
            qemu_log("sdcard_normal_command " "%s %20s/ CMD%02d arg 0x%08x (mode %s, state %s)" "\n", proto, cmd_desc, cmd, arg, mode, state);
#line 629 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_APP_COMMAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_APP_COMMAND) || \
    false)

static inline void trace_sdcard_app_command(const char *proto, const char *acmd_desc, uint8_t acmd, uint32_t arg, const char *mode, const char *state)
{
    if (trace_event_get_state(TRACE_SDCARD_APP_COMMAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 41 "../hw/sd/trace-events"
            qemu_log("sdcard_app_command " "%s %23s/ACMD%02d arg 0x%08x (mode %s, state %s)" "\n", proto, acmd_desc, acmd, arg, mode, state);
#line 644 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_RESPONSE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_RESPONSE) || \
    false)

static inline void trace_sdcard_response(const char *rspdesc, int rsplen)
{
    if (trace_event_get_state(TRACE_SDCARD_RESPONSE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 42 "../hw/sd/trace-events"
            qemu_log("sdcard_response " "%s (sz:%d)" "\n", rspdesc, rsplen);
#line 659 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_POWERUP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_POWERUP) || \
    false)

static inline void trace_sdcard_powerup(void)
{
    if (trace_event_get_state(TRACE_SDCARD_POWERUP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 43 "../hw/sd/trace-events"
            qemu_log("sdcard_powerup " "" "\n");
#line 674 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_INQUIRY_CMD41_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_INQUIRY_CMD41) || \
    false)

static inline void trace_sdcard_inquiry_cmd41(void)
{
    if (trace_event_get_state(TRACE_SDCARD_INQUIRY_CMD41)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 44 "../hw/sd/trace-events"
            qemu_log("sdcard_inquiry_cmd41 " "" "\n");
#line 689 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_RESET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_RESET) || \
    false)

static inline void trace_sdcard_reset(void)
{
    if (trace_event_get_state(TRACE_SDCARD_RESET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 45 "../hw/sd/trace-events"
            qemu_log("sdcard_reset " "" "\n");
#line 704 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_SET_RCA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_SET_RCA) || \
    false)

static inline void trace_sdcard_set_rca(uint16_t value)
{
    if (trace_event_get_state(TRACE_SDCARD_SET_RCA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 46 "../hw/sd/trace-events"
            qemu_log("sdcard_set_rca " "new RCA: 0x%04x" "\n", value);
#line 719 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_SET_BLOCKLEN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_SET_BLOCKLEN) || \
    false)

static inline void trace_sdcard_set_blocklen(uint16_t length)
{
    if (trace_event_get_state(TRACE_SDCARD_SET_BLOCKLEN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 47 "../hw/sd/trace-events"
            qemu_log("sdcard_set_blocklen " "block len 0x%03x" "\n", length);
#line 734 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_SET_BLOCK_COUNT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_SET_BLOCK_COUNT) || \
    false)

static inline void trace_sdcard_set_block_count(uint32_t cnt)
{
    if (trace_event_get_state(TRACE_SDCARD_SET_BLOCK_COUNT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 48 "../hw/sd/trace-events"
            qemu_log("sdcard_set_block_count " "block cnt 0x%"PRIx32 "\n", cnt);
#line 749 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_INSERTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_INSERTED) || \
    false)

static inline void trace_sdcard_inserted(bool readonly)
{
    if (trace_event_get_state(TRACE_SDCARD_INSERTED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 49 "../hw/sd/trace-events"
            qemu_log("sdcard_inserted " "read_only: %u" "\n", readonly);
#line 764 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_EJECTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_EJECTED) || \
    false)

static inline void trace_sdcard_ejected(void)
{
    if (trace_event_get_state(TRACE_SDCARD_EJECTED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 50 "../hw/sd/trace-events"
            qemu_log("sdcard_ejected " "" "\n");
#line 779 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_ERASE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_ERASE) || \
    false)

static inline void trace_sdcard_erase(uint32_t first, uint32_t last)
{
    if (trace_event_get_state(TRACE_SDCARD_ERASE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 51 "../hw/sd/trace-events"
            qemu_log("sdcard_erase " "addr first 0x%" PRIx32" last 0x%" PRIx32 "\n", first, last);
#line 794 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_LOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_LOCK) || \
    false)

static inline void trace_sdcard_lock(void)
{
    if (trace_event_get_state(TRACE_SDCARD_LOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 52 "../hw/sd/trace-events"
            qemu_log("sdcard_lock " "" "\n");
#line 809 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_UNLOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_UNLOCK) || \
    false)

static inline void trace_sdcard_unlock(void)
{
    if (trace_event_get_state(TRACE_SDCARD_UNLOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 53 "../hw/sd/trace-events"
            qemu_log("sdcard_unlock " "" "\n");
#line 824 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_REQ_ADDR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_REQ_ADDR) || \
    false)

static inline void trace_sdcard_req_addr(uint32_t req_arg, uint64_t addr)
{
    if (trace_event_get_state(TRACE_SDCARD_REQ_ADDR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 54 "../hw/sd/trace-events"
            qemu_log("sdcard_req_addr " "req 0x%" PRIx32 " addr 0x%" PRIx64 "\n", req_arg, addr);
#line 839 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_READ_BLOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_READ_BLOCK) || \
    false)

static inline void trace_sdcard_read_block(uint64_t addr, uint32_t len)
{
    if (trace_event_get_state(TRACE_SDCARD_READ_BLOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 55 "../hw/sd/trace-events"
            qemu_log("sdcard_read_block " "addr 0x%" PRIx64 " size 0x%x" "\n", addr, len);
#line 854 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_WRITE_BLOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_WRITE_BLOCK) || \
    false)

static inline void trace_sdcard_write_block(uint64_t addr, uint32_t len)
{
    if (trace_event_get_state(TRACE_SDCARD_WRITE_BLOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 56 "../hw/sd/trace-events"
            qemu_log("sdcard_write_block " "addr 0x%" PRIx64 " size 0x%x" "\n", addr, len);
#line 869 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_WRITE_DATA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_WRITE_DATA) || \
    false)

static inline void trace_sdcard_write_data(const char *proto, const char *cmd_desc, uint8_t cmd, uint32_t offset, uint8_t value)
{
    if (trace_event_get_state(TRACE_SDCARD_WRITE_DATA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 57 "../hw/sd/trace-events"
            qemu_log("sdcard_write_data " "%s %20s/ CMD%02d ofs %"PRIu32" value 0x%02x" "\n", proto, cmd_desc, cmd, offset, value);
#line 884 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_READ_DATA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_READ_DATA) || \
    false)

static inline void trace_sdcard_read_data(const char *proto, const char *cmd_desc, uint8_t cmd, uint32_t offset, uint64_t size, uint32_t blklen)
{
    if (trace_event_get_state(TRACE_SDCARD_READ_DATA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 58 "../hw/sd/trace-events"
            qemu_log("sdcard_read_data " "%s %20s/ CMD%02d ofs %"PRIu32" size %"PRIu64" blklen %" PRIu32 "\n", proto, cmd_desc, cmd, offset, size, blklen);
#line 899 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_SET_VOLTAGE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_SET_VOLTAGE) || \
    false)

static inline void trace_sdcard_set_voltage(uint16_t millivolts)
{
    if (trace_event_get_state(TRACE_SDCARD_SET_VOLTAGE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 59 "../hw/sd/trace-events"
            qemu_log("sdcard_set_voltage " "%u mV" "\n", millivolts);
#line 914 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_EXT_CSD_UPDATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_EXT_CSD_UPDATE) || \
    false)

static inline void trace_sdcard_ext_csd_update(unsigned index, uint8_t oval, uint8_t nval)
{
    if (trace_event_get_state(TRACE_SDCARD_EXT_CSD_UPDATE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 60 "../hw/sd/trace-events"
            qemu_log("sdcard_ext_csd_update " "index %u: 0x%02x -> 0x%02x" "\n", index, oval, nval);
#line 929 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_SWITCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_SWITCH) || \
    false)

static inline void trace_sdcard_switch(unsigned access, unsigned index, unsigned value, unsigned set)
{
    if (trace_event_get_state(TRACE_SDCARD_SWITCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 61 "../hw/sd/trace-events"
            qemu_log("sdcard_switch " "acc:%u idx:%u val:%u set:%u" "\n", access, index, value, set);
#line 944 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_RPMB_READ_BLOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_RPMB_READ_BLOCK) || \
    false)

static inline void trace_sdcard_rpmb_read_block(uint16_t resp, uint16_t read_addr, uint16_t result)
{
    if (trace_event_get_state(TRACE_SDCARD_RPMB_READ_BLOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 62 "../hw/sd/trace-events"
            qemu_log("sdcard_rpmb_read_block " "resp 0x%x read_addr 0x%x result 0x%x" "\n", resp, read_addr, result);
#line 959 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_SDCARD_RPMB_WRITE_BLOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SDCARD_RPMB_WRITE_BLOCK) || \
    false)

static inline void trace_sdcard_rpmb_write_block(uint16_t req, uint16_t result)
{
    if (trace_event_get_state(TRACE_SDCARD_RPMB_WRITE_BLOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 63 "../hw/sd/trace-events"
            qemu_log("sdcard_rpmb_write_block " "req 0x%x result 0x%x" "\n", req, result);
#line 974 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_COMMAND_SEND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_COMMAND_SEND) || \
    false)

static inline void trace_pl181_command_send(uint8_t cmd, uint32_t arg)
{
    if (trace_event_get_state(TRACE_PL181_COMMAND_SEND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 66 "../hw/sd/trace-events"
            qemu_log("pl181_command_send " "sending CMD%02d arg 0x%08" PRIx32 "\n", cmd, arg);
#line 989 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_COMMAND_SENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_COMMAND_SENT) || \
    false)

static inline void trace_pl181_command_sent(void)
{
    if (trace_event_get_state(TRACE_PL181_COMMAND_SENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 67 "../hw/sd/trace-events"
            qemu_log("pl181_command_sent " "command sent" "\n");
#line 1004 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_COMMAND_RESPONSE_PENDING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_COMMAND_RESPONSE_PENDING) || \
    false)

static inline void trace_pl181_command_response_pending(void)
{
    if (trace_event_get_state(TRACE_PL181_COMMAND_RESPONSE_PENDING)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 68 "../hw/sd/trace-events"
            qemu_log("pl181_command_response_pending " "response received" "\n");
#line 1019 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_COMMAND_TIMEOUT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_COMMAND_TIMEOUT) || \
    false)

static inline void trace_pl181_command_timeout(void)
{
    if (trace_event_get_state(TRACE_PL181_COMMAND_TIMEOUT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 69 "../hw/sd/trace-events"
            qemu_log("pl181_command_timeout " "command timeouted" "\n");
#line 1034 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_FIFO_PUSH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_FIFO_PUSH) || \
    false)

static inline void trace_pl181_fifo_push(uint32_t data)
{
    if (trace_event_get_state(TRACE_PL181_FIFO_PUSH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 70 "../hw/sd/trace-events"
            qemu_log("pl181_fifo_push " "FIFO push 0x%08" PRIx32 "\n", data);
#line 1049 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_FIFO_POP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_FIFO_POP) || \
    false)

static inline void trace_pl181_fifo_pop(uint32_t data)
{
    if (trace_event_get_state(TRACE_PL181_FIFO_POP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 71 "../hw/sd/trace-events"
            qemu_log("pl181_fifo_pop " "FIFO pop 0x%08" PRIx32 "\n", data);
#line 1064 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_FIFO_TRANSFER_COMPLETE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_FIFO_TRANSFER_COMPLETE) || \
    false)

static inline void trace_pl181_fifo_transfer_complete(void)
{
    if (trace_event_get_state(TRACE_PL181_FIFO_TRANSFER_COMPLETE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 72 "../hw/sd/trace-events"
            qemu_log("pl181_fifo_transfer_complete " "FIFO transfer complete" "\n");
#line 1079 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_PL181_DATA_ENGINE_IDLE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PL181_DATA_ENGINE_IDLE) || \
    false)

static inline void trace_pl181_data_engine_idle(void)
{
    if (trace_event_get_state(TRACE_PL181_DATA_ENGINE_IDLE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 73 "../hw/sd/trace-events"
            qemu_log("pl181_data_engine_idle " "data engine idle" "\n");
#line 1094 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_ASPEED_SDHCI_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_SDHCI_READ) || \
    false)

static inline void trace_aspeed_sdhci_read(uint64_t addr, uint32_t size, uint64_t data)
{
    if (trace_event_get_state(TRACE_ASPEED_SDHCI_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 76 "../hw/sd/trace-events"
            qemu_log("aspeed_sdhci_read " "@0x%" PRIx64 " size %u: 0x%" PRIx64 "\n", addr, size, data);
#line 1109 "trace/trace-hw_sd.h"
        }
    }
}

#define TRACE_ASPEED_SDHCI_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_SDHCI_WRITE) || \
    false)

static inline void trace_aspeed_sdhci_write(uint64_t addr, uint32_t size, uint64_t data)
{
    if (trace_event_get_state(TRACE_ASPEED_SDHCI_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 77 "../hw/sd/trace-events"
            qemu_log("aspeed_sdhci_write " "@0x%" PRIx64 " size %u: 0x%" PRIx64 "\n", addr, size, data);
#line 1124 "trace/trace-hw_sd.h"
        }
    }
}
#endif /* TRACE_HW_SD_GENERATED_TRACERS_H */
