/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_UEFI_GENERATED_TRACERS_H
#define TRACE_HW_UEFI_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_UEFI_REG_READ_EVENT;
extern TraceEvent _TRACE_UEFI_REG_WRITE_EVENT;
extern TraceEvent _TRACE_UEFI_HARD_RESET_EVENT;
extern TraceEvent _TRACE_UEFI_VARIABLE_EVENT;
extern TraceEvent _TRACE_UEFI_STATUS_EVENT;
extern TraceEvent _TRACE_UEFI_EVENT_EVENT;
extern TraceEvent _TRACE_UEFI_VARS_PROTO_CMD_EVENT;
extern TraceEvent _TRACE_UEFI_VARS_SECURITY_VIOLATION_EVENT;
extern TraceEvent _TRACE_UEFI_VARS_POLICY_CMD_EVENT;
extern TraceEvent _TRACE_UEFI_VARS_POLICY_DENY_EVENT;
extern uint16_t _TRACE_UEFI_REG_READ_DSTATE;
extern uint16_t _TRACE_UEFI_REG_WRITE_DSTATE;
extern uint16_t _TRACE_UEFI_HARD_RESET_DSTATE;
extern uint16_t _TRACE_UEFI_VARIABLE_DSTATE;
extern uint16_t _TRACE_UEFI_STATUS_DSTATE;
extern uint16_t _TRACE_UEFI_EVENT_DSTATE;
extern uint16_t _TRACE_UEFI_VARS_PROTO_CMD_DSTATE;
extern uint16_t _TRACE_UEFI_VARS_SECURITY_VIOLATION_DSTATE;
extern uint16_t _TRACE_UEFI_VARS_POLICY_CMD_DSTATE;
extern uint16_t _TRACE_UEFI_VARS_POLICY_DENY_DSTATE;
#define TRACE_UEFI_REG_READ_ENABLED 1
#define TRACE_UEFI_REG_WRITE_ENABLED 1
#define TRACE_UEFI_HARD_RESET_ENABLED 1
#define TRACE_UEFI_VARIABLE_ENABLED 1
#define TRACE_UEFI_STATUS_ENABLED 1
#define TRACE_UEFI_EVENT_ENABLED 1
#define TRACE_UEFI_VARS_PROTO_CMD_ENABLED 1
#define TRACE_UEFI_VARS_SECURITY_VIOLATION_ENABLED 1
#define TRACE_UEFI_VARS_POLICY_CMD_ENABLED 1
#define TRACE_UEFI_VARS_POLICY_DENY_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_UEFI_REG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_REG_READ) || \
    false)

static inline void trace_uefi_reg_read(uint64_t addr, unsigned size)
{
    if (trace_event_get_state(TRACE_UEFI_REG_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 2 "../hw/uefi/trace-events"
            qemu_log("uefi_reg_read " "addr 0x%" PRIx64 ", size %u" "\n", addr, size);
#line 53 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_REG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_REG_WRITE) || \
    false)

static inline void trace_uefi_reg_write(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_UEFI_REG_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "../hw/uefi/trace-events"
            qemu_log("uefi_reg_write " "addr 0x%" PRIx64 ", val 0x%" PRIx64 ", size %d" "\n", addr, val, size);
#line 68 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_HARD_RESET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_HARD_RESET) || \
    false)

static inline void trace_uefi_hard_reset(void)
{
    if (trace_event_get_state(TRACE_UEFI_HARD_RESET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/uefi/trace-events"
            qemu_log("uefi_hard_reset " "" "\n");
#line 83 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_VARIABLE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_VARIABLE) || \
    false)

static inline void trace_uefi_variable(const char *context, const char *name, uint64_t size, const char *uuid)
{
    if (trace_event_get_state(TRACE_UEFI_VARIABLE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../hw/uefi/trace-events"
            qemu_log("uefi_variable " "context %s, name %s, size %" PRIu64 ", uuid %s" "\n", context, name, size, uuid);
#line 98 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_STATUS) || \
    false)

static inline void trace_uefi_status(const char *context, const char *name)
{
    if (trace_event_get_state(TRACE_UEFI_STATUS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../hw/uefi/trace-events"
            qemu_log("uefi_status " "context %s, status %s" "\n", context, name);
#line 113 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_EVENT) || \
    false)

static inline void trace_uefi_event(const char *name)
{
    if (trace_event_get_state(TRACE_UEFI_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "../hw/uefi/trace-events"
            qemu_log("uefi_event " "event %s" "\n", name);
#line 128 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_VARS_PROTO_CMD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_VARS_PROTO_CMD) || \
    false)

static inline void trace_uefi_vars_proto_cmd(const char *cmd)
{
    if (trace_event_get_state(TRACE_UEFI_VARS_PROTO_CMD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../hw/uefi/trace-events"
            qemu_log("uefi_vars_proto_cmd " "cmd %s" "\n", cmd);
#line 143 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_VARS_SECURITY_VIOLATION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_VARS_SECURITY_VIOLATION) || \
    false)

static inline void trace_uefi_vars_security_violation(const char *reason)
{
    if (trace_event_get_state(TRACE_UEFI_VARS_SECURITY_VIOLATION)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../hw/uefi/trace-events"
            qemu_log("uefi_vars_security_violation " "reason %s" "\n", reason);
#line 158 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_VARS_POLICY_CMD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_VARS_POLICY_CMD) || \
    false)

static inline void trace_uefi_vars_policy_cmd(const char *cmd)
{
    if (trace_event_get_state(TRACE_UEFI_VARS_POLICY_CMD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "../hw/uefi/trace-events"
            qemu_log("uefi_vars_policy_cmd " "cmd %s" "\n", cmd);
#line 173 "trace/trace-hw_uefi.h"
        }
    }
}

#define TRACE_UEFI_VARS_POLICY_DENY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UEFI_VARS_POLICY_DENY) || \
    false)

static inline void trace_uefi_vars_policy_deny(const char *reason)
{
    if (trace_event_get_state(TRACE_UEFI_VARS_POLICY_DENY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../hw/uefi/trace-events"
            qemu_log("uefi_vars_policy_deny " "reason %s" "\n", reason);
#line 188 "trace/trace-hw_uefi.h"
        }
    }
}
#endif /* TRACE_HW_UEFI_GENERATED_TRACERS_H */
