/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_QAPI_COMMANDS_CXL_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_CXL_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_CXL_INJECT_GENERAL_MEDIA_EVENT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_INJECT_GENERAL_MEDIA_EVENT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CXL_INJECT_DRAM_EVENT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_INJECT_DRAM_EVENT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CXL_INJECT_MEMORY_MODULE_EVENT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_INJECT_MEMORY_MODULE_EVENT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CXL_INJECT_POISON_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_INJECT_POISON_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CXL_INJECT_UNCORRECTABLE_ERRORS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_INJECT_UNCORRECTABLE_ERRORS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CXL_INJECT_CORRECTABLE_ERROR_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_INJECT_CORRECTABLE_ERROR_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CXL_ADD_DYNAMIC_CAPACITY_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_ADD_DYNAMIC_CAPACITY_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CXL_RELEASE_DYNAMIC_CAPACITY_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CXL_RELEASE_DYNAMIC_CAPACITY_EVENT;
extern uint16_t _TRACE_QMP_ENTER_CXL_INJECT_GENERAL_MEDIA_EVENT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_INJECT_GENERAL_MEDIA_EVENT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CXL_INJECT_DRAM_EVENT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_INJECT_DRAM_EVENT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CXL_INJECT_MEMORY_MODULE_EVENT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_INJECT_MEMORY_MODULE_EVENT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CXL_INJECT_POISON_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_INJECT_POISON_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CXL_INJECT_UNCORRECTABLE_ERRORS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_INJECT_UNCORRECTABLE_ERRORS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CXL_INJECT_CORRECTABLE_ERROR_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_INJECT_CORRECTABLE_ERROR_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CXL_ADD_DYNAMIC_CAPACITY_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_ADD_DYNAMIC_CAPACITY_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CXL_RELEASE_DYNAMIC_CAPACITY_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CXL_RELEASE_DYNAMIC_CAPACITY_DSTATE;
#define TRACE_QMP_ENTER_CXL_INJECT_GENERAL_MEDIA_EVENT_ENABLED 1
#define TRACE_QMP_EXIT_CXL_INJECT_GENERAL_MEDIA_EVENT_ENABLED 1
#define TRACE_QMP_ENTER_CXL_INJECT_DRAM_EVENT_ENABLED 1
#define TRACE_QMP_EXIT_CXL_INJECT_DRAM_EVENT_ENABLED 1
#define TRACE_QMP_ENTER_CXL_INJECT_MEMORY_MODULE_EVENT_ENABLED 1
#define TRACE_QMP_EXIT_CXL_INJECT_MEMORY_MODULE_EVENT_ENABLED 1
#define TRACE_QMP_ENTER_CXL_INJECT_POISON_ENABLED 1
#define TRACE_QMP_EXIT_CXL_INJECT_POISON_ENABLED 1
#define TRACE_QMP_ENTER_CXL_INJECT_UNCORRECTABLE_ERRORS_ENABLED 1
#define TRACE_QMP_EXIT_CXL_INJECT_UNCORRECTABLE_ERRORS_ENABLED 1
#define TRACE_QMP_ENTER_CXL_INJECT_CORRECTABLE_ERROR_ENABLED 1
#define TRACE_QMP_EXIT_CXL_INJECT_CORRECTABLE_ERROR_ENABLED 1
#define TRACE_QMP_ENTER_CXL_ADD_DYNAMIC_CAPACITY_ENABLED 1
#define TRACE_QMP_EXIT_CXL_ADD_DYNAMIC_CAPACITY_ENABLED 1
#define TRACE_QMP_ENTER_CXL_RELEASE_DYNAMIC_CAPACITY_ENABLED 1
#define TRACE_QMP_EXIT_CXL_RELEASE_DYNAMIC_CAPACITY_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_CXL_INJECT_GENERAL_MEDIA_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_INJECT_GENERAL_MEDIA_EVENT) || \
    false)

static inline void trace_qmp_enter_cxl_inject_general_media_event(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_INJECT_GENERAL_MEDIA_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_inject_general_media_event " "%s" "\n", json);
#line 71 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_INJECT_GENERAL_MEDIA_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_INJECT_GENERAL_MEDIA_EVENT) || \
    false)

static inline void trace_qmp_exit_cxl_inject_general_media_event(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_INJECT_GENERAL_MEDIA_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_inject_general_media_event " "%s %d" "\n", result, succeeded);
#line 86 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_CXL_INJECT_DRAM_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_INJECT_DRAM_EVENT) || \
    false)

static inline void trace_qmp_enter_cxl_inject_dram_event(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_INJECT_DRAM_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_inject_dram_event " "%s" "\n", json);
#line 101 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_INJECT_DRAM_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_INJECT_DRAM_EVENT) || \
    false)

static inline void trace_qmp_exit_cxl_inject_dram_event(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_INJECT_DRAM_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_inject_dram_event " "%s %d" "\n", result, succeeded);
#line 116 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_CXL_INJECT_MEMORY_MODULE_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_INJECT_MEMORY_MODULE_EVENT) || \
    false)

static inline void trace_qmp_enter_cxl_inject_memory_module_event(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_INJECT_MEMORY_MODULE_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_inject_memory_module_event " "%s" "\n", json);
#line 131 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_INJECT_MEMORY_MODULE_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_INJECT_MEMORY_MODULE_EVENT) || \
    false)

static inline void trace_qmp_exit_cxl_inject_memory_module_event(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_INJECT_MEMORY_MODULE_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_inject_memory_module_event " "%s %d" "\n", result, succeeded);
#line 146 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_CXL_INJECT_POISON_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_INJECT_POISON) || \
    false)

static inline void trace_qmp_enter_cxl_inject_poison(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_INJECT_POISON)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_inject_poison " "%s" "\n", json);
#line 161 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_INJECT_POISON_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_INJECT_POISON) || \
    false)

static inline void trace_qmp_exit_cxl_inject_poison(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_INJECT_POISON)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_inject_poison " "%s %d" "\n", result, succeeded);
#line 176 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_CXL_INJECT_UNCORRECTABLE_ERRORS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_INJECT_UNCORRECTABLE_ERRORS) || \
    false)

static inline void trace_qmp_enter_cxl_inject_uncorrectable_errors(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_INJECT_UNCORRECTABLE_ERRORS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_inject_uncorrectable_errors " "%s" "\n", json);
#line 191 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_INJECT_UNCORRECTABLE_ERRORS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_INJECT_UNCORRECTABLE_ERRORS) || \
    false)

static inline void trace_qmp_exit_cxl_inject_uncorrectable_errors(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_INJECT_UNCORRECTABLE_ERRORS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_inject_uncorrectable_errors " "%s %d" "\n", result, succeeded);
#line 206 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_CXL_INJECT_CORRECTABLE_ERROR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_INJECT_CORRECTABLE_ERROR) || \
    false)

static inline void trace_qmp_enter_cxl_inject_correctable_error(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_INJECT_CORRECTABLE_ERROR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_inject_correctable_error " "%s" "\n", json);
#line 221 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_INJECT_CORRECTABLE_ERROR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_INJECT_CORRECTABLE_ERROR) || \
    false)

static inline void trace_qmp_exit_cxl_inject_correctable_error(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_INJECT_CORRECTABLE_ERROR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_inject_correctable_error " "%s %d" "\n", result, succeeded);
#line 236 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_CXL_ADD_DYNAMIC_CAPACITY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_ADD_DYNAMIC_CAPACITY) || \
    false)

static inline void trace_qmp_enter_cxl_add_dynamic_capacity(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_ADD_DYNAMIC_CAPACITY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_add_dynamic_capacity " "%s" "\n", json);
#line 251 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_ADD_DYNAMIC_CAPACITY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_ADD_DYNAMIC_CAPACITY) || \
    false)

static inline void trace_qmp_exit_cxl_add_dynamic_capacity(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_ADD_DYNAMIC_CAPACITY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_add_dynamic_capacity " "%s %d" "\n", result, succeeded);
#line 266 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_ENTER_CXL_RELEASE_DYNAMIC_CAPACITY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CXL_RELEASE_DYNAMIC_CAPACITY) || \
    false)

static inline void trace_qmp_enter_cxl_release_dynamic_capacity(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CXL_RELEASE_DYNAMIC_CAPACITY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_enter_cxl_release_dynamic_capacity " "%s" "\n", json);
#line 281 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_CXL_RELEASE_DYNAMIC_CAPACITY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CXL_RELEASE_DYNAMIC_CAPACITY) || \
    false)

static inline void trace_qmp_exit_cxl_release_dynamic_capacity(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CXL_RELEASE_DYNAMIC_CAPACITY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "qapi/qapi-commands-cxl.trace-events"
            qemu_log("qmp_exit_cxl_release_dynamic_capacity " "%s %d" "\n", result, succeeded);
#line 296 "trace/trace-qapi_commands_cxl_trace_events.h"
        }
    }
}
#endif /* TRACE_QAPI_COMMANDS_CXL_TRACE_EVENTS_GENERATED_TRACERS_H */
