/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_TARGET_I386_WHPX_GENERATED_TRACERS_H
#define TRACE_TARGET_I386_WHPX_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_WHPX_UNSUPPORTED_MSR_ACCESS_EVENT;
extern uint16_t _TRACE_WHPX_UNSUPPORTED_MSR_ACCESS_DSTATE;
#define TRACE_WHPX_UNSUPPORTED_MSR_ACCESS_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_WHPX_UNSUPPORTED_MSR_ACCESS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_WHPX_UNSUPPORTED_MSR_ACCESS) || \
    false)

static inline void trace_whpx_unsupported_msr_access(uint32_t msr, int is_write)
{
    if (trace_event_get_state(TRACE_WHPX_UNSUPPORTED_MSR_ACCESS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 1 "../target/i386/whpx/trace-events"
            qemu_log("whpx_unsupported_msr_access " "WHPX: Unsupported MSR access (0x%x), IsWrite=%i" "\n", msr, is_write);
#line 26 "trace/trace-target_i386_whpx.h"
        }
    }
}
#endif /* TRACE_TARGET_I386_WHPX_GENERATED_TRACERS_H */
