/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI features
 *
 * Copyright 2024 Red Hat
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef TEST_QAPI_FEATURES_H
#define TEST_QAPI_FEATURES_H

#include "qapi/util.h"

typedef enum {
    QAPI_FEATURE_DEPRECATED = QAPI_DEPRECATED,
    QAPI_FEATURE_UNSTABLE = QAPI_UNSTABLE,
    QAPI_FEATURE_FEATURE1,
    QAPI_FEATURE_FEATURE2,
    QAPI_FEATURE_NAMESPACE_TEST,
    QAPI_FEATURE_INT,
    QAPI_FEATURE_NAME,
    QAPI_FEATURE_IF,
} QapiFeature;

#endif /* TEST_QAPI_FEATURES_H */
