/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI features
 *
 * Copyright 2024 Red Hat
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef QAPI_FEATURES_H
#define QAPI_FEATURES_H

#include "qapi/util.h"

typedef enum {
    QAPI_FEATURE_DEPRECATED = QAPI_DEPRECATED,
    QAPI_FEATURE_UNSTABLE = QAPI_UNSTABLE,
    QAPI_FEATURE_ALLOW_WRITE_ONLY_OVERLAY,
    QAPI_FEATURE_DYNAMIC_AUTO_READ_ONLY,
    QAPI_FEATURE_FDSET,
    QAPI_FEATURE_CONFIDENTIAL_GUEST_RESET,
    QAPI_FEATURE_JSON_CLI,
    QAPI_FEATURE_JSON_CLI_HOTPLUG,
    QAPI_FEATURE_SAVEVM_MONITOR_NODES,
} QapiFeature;

#endif /* QAPI_FEATURES_H */
