/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_SENSOR_GENERATED_TRACERS_H
#define TRACE_HW_SENSOR_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_TMP105_READ_EVENT;
extern TraceEvent _TRACE_TMP105_WRITE_EVENT;
extern TraceEvent _TRACE_TMP105_WRITE_SHUTDOWN_EVENT;
extern uint16_t _TRACE_TMP105_READ_DSTATE;
extern uint16_t _TRACE_TMP105_WRITE_DSTATE;
extern uint16_t _TRACE_TMP105_WRITE_SHUTDOWN_DSTATE;
#define TRACE_TMP105_READ_ENABLED 1
#define TRACE_TMP105_WRITE_ENABLED 1
#define TRACE_TMP105_WRITE_SHUTDOWN_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_TMP105_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TMP105_READ) || \
    false)

static inline void trace_tmp105_read(uint8_t dev, uint8_t addr)
{
    if (trace_event_get_state(TRACE_TMP105_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/sensor/trace-events"
            qemu_log("tmp105_read " "device: 0x%02x, addr: 0x%02x" "\n", dev, addr);
#line 32 "trace/trace-hw_sensor.h"
        }
    }
}

#define TRACE_TMP105_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TMP105_WRITE) || \
    false)

static inline void trace_tmp105_write(uint8_t dev, uint8_t addr)
{
    if (trace_event_get_state(TRACE_TMP105_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../hw/sensor/trace-events"
            qemu_log("tmp105_write " "device: 0x%02x, addr 0x%02x" "\n", dev, addr);
#line 47 "trace/trace-hw_sensor.h"
        }
    }
}

#define TRACE_TMP105_WRITE_SHUTDOWN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TMP105_WRITE_SHUTDOWN) || \
    false)

static inline void trace_tmp105_write_shutdown(uint8_t dev)
{
    if (trace_event_get_state(TRACE_TMP105_WRITE_SHUTDOWN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../hw/sensor/trace-events"
            qemu_log("tmp105_write_shutdown " "device: 0x%02x" "\n", dev);
#line 62 "trace/trace-hw_sensor.h"
        }
    }
}
#endif /* TRACE_HW_SENSOR_GENERATED_TRACERS_H */
