/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_QAPI_COMMANDS_CRYPTODEV_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_CRYPTODEV_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_QUERY_CRYPTODEV_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_CRYPTODEV_EVENT;
extern uint16_t _TRACE_QMP_ENTER_QUERY_CRYPTODEV_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_CRYPTODEV_DSTATE;
#define TRACE_QMP_ENTER_QUERY_CRYPTODEV_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_CRYPTODEV_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_QUERY_CRYPTODEV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_CRYPTODEV) || \
    false)

static inline void trace_qmp_enter_query_cryptodev(const char *json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_CRYPTODEV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-cryptodev.trace-events"
            qemu_log("qmp_enter_query_cryptodev " "%s" "\n", json);
#line 29 "trace/trace-qapi_commands_cryptodev_trace_events.h"
        }
    }
}

#define TRACE_QMP_EXIT_QUERY_CRYPTODEV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_CRYPTODEV) || \
    false)

static inline void trace_qmp_exit_query_cryptodev(const char *result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_CRYPTODEV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-cryptodev.trace-events"
            qemu_log("qmp_exit_query_cryptodev " "%s %d" "\n", result, succeeded);
#line 44 "trace/trace-qapi_commands_cryptodev_trace_events.h"
        }
    }
}
#endif /* TRACE_QAPI_COMMANDS_CRYPTODEV_TRACE_EVENTS_GENERATED_TRACERS_H */
