/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-hw_nitro.h"

uint16_t _TRACE_NITRO_SERIAL_VSOCK_EVENT_DSTATE;
uint16_t _TRACE_NITRO_HEARTBEAT_EVENT_DSTATE;
uint16_t _TRACE_NITRO_HEARTBEAT_DONE_DSTATE;
TraceEvent _TRACE_NITRO_SERIAL_VSOCK_EVENT_EVENT = {
    .id = 0,
    .name = "nitro_serial_vsock_event",
    .sstate = TRACE_NITRO_SERIAL_VSOCK_EVENT_ENABLED,
    .dstate = &_TRACE_NITRO_SERIAL_VSOCK_EVENT_DSTATE
};
TraceEvent _TRACE_NITRO_HEARTBEAT_EVENT_EVENT = {
    .id = 0,
    .name = "nitro_heartbeat_event",
    .sstate = TRACE_NITRO_HEARTBEAT_EVENT_ENABLED,
    .dstate = &_TRACE_NITRO_HEARTBEAT_EVENT_DSTATE
};
TraceEvent _TRACE_NITRO_HEARTBEAT_DONE_EVENT = {
    .id = 0,
    .name = "nitro_heartbeat_done",
    .sstate = TRACE_NITRO_HEARTBEAT_DONE_ENABLED,
    .dstate = &_TRACE_NITRO_HEARTBEAT_DONE_DSTATE
};
TraceEvent *hw_nitro_trace_events[] = {
    &_TRACE_NITRO_SERIAL_VSOCK_EVENT_EVENT,
    &_TRACE_NITRO_HEARTBEAT_EVENT_EVENT,
    &_TRACE_NITRO_HEARTBEAT_DONE_EVENT,
  NULL,
};

static void trace_hw_nitro_register_events(void)
{
    trace_event_register_group(hw_nitro_trace_events);
}
trace_init(trace_hw_nitro_register_events)
