/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-target_arm.h"

uint16_t _TRACE_ARM_GT_RECALC_DSTATE;
uint16_t _TRACE_ARM_GT_RECALC_DISABLED_DSTATE;
uint16_t _TRACE_ARM_GT_CVAL_WRITE_DSTATE;
uint16_t _TRACE_ARM_GT_TVAL_WRITE_DSTATE;
uint16_t _TRACE_ARM_GT_CTL_WRITE_DSTATE;
uint16_t _TRACE_ARM_GT_IMASK_TOGGLE_DSTATE;
uint16_t _TRACE_ARM_GT_CNTVOFF_WRITE_DSTATE;
uint16_t _TRACE_ARM_GT_CNTPOFF_WRITE_DSTATE;
uint16_t _TRACE_ARM_GT_UPDATE_IRQ_DSTATE;
uint16_t _TRACE_KVM_ARM_FIXUP_MSI_ROUTE_DSTATE;
uint16_t _TRACE_ARM_CPU_RESET_DSTATE;
uint16_t _TRACE_ARM_EMULATE_FIRMWARE_RESET_DSTATE;
uint16_t _TRACE_ARM_POWERCTL_SET_CPU_ON_DSTATE;
uint16_t _TRACE_ARM_POWERCTL_SET_CPU_ON_AND_RESET_DSTATE;
uint16_t _TRACE_ARM_POWERCTL_SET_CPU_OFF_DSTATE;
uint16_t _TRACE_ARM_POWERCTL_RESET_CPU_DSTATE;
uint16_t _TRACE_ARM_PSCI_CALL_DSTATE;
uint16_t _TRACE_CPU_POST_LOAD_DSTATE;
TraceEvent _TRACE_ARM_GT_RECALC_EVENT = {
    .id = 0,
    .name = "arm_gt_recalc",
    .sstate = TRACE_ARM_GT_RECALC_ENABLED,
    .dstate = &_TRACE_ARM_GT_RECALC_DSTATE
};
TraceEvent _TRACE_ARM_GT_RECALC_DISABLED_EVENT = {
    .id = 0,
    .name = "arm_gt_recalc_disabled",
    .sstate = TRACE_ARM_GT_RECALC_DISABLED_ENABLED,
    .dstate = &_TRACE_ARM_GT_RECALC_DISABLED_DSTATE
};
TraceEvent _TRACE_ARM_GT_CVAL_WRITE_EVENT = {
    .id = 0,
    .name = "arm_gt_cval_write",
    .sstate = TRACE_ARM_GT_CVAL_WRITE_ENABLED,
    .dstate = &_TRACE_ARM_GT_CVAL_WRITE_DSTATE
};
TraceEvent _TRACE_ARM_GT_TVAL_WRITE_EVENT = {
    .id = 0,
    .name = "arm_gt_tval_write",
    .sstate = TRACE_ARM_GT_TVAL_WRITE_ENABLED,
    .dstate = &_TRACE_ARM_GT_TVAL_WRITE_DSTATE
};
TraceEvent _TRACE_ARM_GT_CTL_WRITE_EVENT = {
    .id = 0,
    .name = "arm_gt_ctl_write",
    .sstate = TRACE_ARM_GT_CTL_WRITE_ENABLED,
    .dstate = &_TRACE_ARM_GT_CTL_WRITE_DSTATE
};
TraceEvent _TRACE_ARM_GT_IMASK_TOGGLE_EVENT = {
    .id = 0,
    .name = "arm_gt_imask_toggle",
    .sstate = TRACE_ARM_GT_IMASK_TOGGLE_ENABLED,
    .dstate = &_TRACE_ARM_GT_IMASK_TOGGLE_DSTATE
};
TraceEvent _TRACE_ARM_GT_CNTVOFF_WRITE_EVENT = {
    .id = 0,
    .name = "arm_gt_cntvoff_write",
    .sstate = TRACE_ARM_GT_CNTVOFF_WRITE_ENABLED,
    .dstate = &_TRACE_ARM_GT_CNTVOFF_WRITE_DSTATE
};
TraceEvent _TRACE_ARM_GT_CNTPOFF_WRITE_EVENT = {
    .id = 0,
    .name = "arm_gt_cntpoff_write",
    .sstate = TRACE_ARM_GT_CNTPOFF_WRITE_ENABLED,
    .dstate = &_TRACE_ARM_GT_CNTPOFF_WRITE_DSTATE
};
TraceEvent _TRACE_ARM_GT_UPDATE_IRQ_EVENT = {
    .id = 0,
    .name = "arm_gt_update_irq",
    .sstate = TRACE_ARM_GT_UPDATE_IRQ_ENABLED,
    .dstate = &_TRACE_ARM_GT_UPDATE_IRQ_DSTATE
};
TraceEvent _TRACE_KVM_ARM_FIXUP_MSI_ROUTE_EVENT = {
    .id = 0,
    .name = "kvm_arm_fixup_msi_route",
    .sstate = TRACE_KVM_ARM_FIXUP_MSI_ROUTE_ENABLED,
    .dstate = &_TRACE_KVM_ARM_FIXUP_MSI_ROUTE_DSTATE
};
TraceEvent _TRACE_ARM_CPU_RESET_EVENT = {
    .id = 0,
    .name = "arm_cpu_reset",
    .sstate = TRACE_ARM_CPU_RESET_ENABLED,
    .dstate = &_TRACE_ARM_CPU_RESET_DSTATE
};
TraceEvent _TRACE_ARM_EMULATE_FIRMWARE_RESET_EVENT = {
    .id = 0,
    .name = "arm_emulate_firmware_reset",
    .sstate = TRACE_ARM_EMULATE_FIRMWARE_RESET_ENABLED,
    .dstate = &_TRACE_ARM_EMULATE_FIRMWARE_RESET_DSTATE
};
TraceEvent _TRACE_ARM_POWERCTL_SET_CPU_ON_EVENT = {
    .id = 0,
    .name = "arm_powerctl_set_cpu_on",
    .sstate = TRACE_ARM_POWERCTL_SET_CPU_ON_ENABLED,
    .dstate = &_TRACE_ARM_POWERCTL_SET_CPU_ON_DSTATE
};
TraceEvent _TRACE_ARM_POWERCTL_SET_CPU_ON_AND_RESET_EVENT = {
    .id = 0,
    .name = "arm_powerctl_set_cpu_on_and_reset",
    .sstate = TRACE_ARM_POWERCTL_SET_CPU_ON_AND_RESET_ENABLED,
    .dstate = &_TRACE_ARM_POWERCTL_SET_CPU_ON_AND_RESET_DSTATE
};
TraceEvent _TRACE_ARM_POWERCTL_SET_CPU_OFF_EVENT = {
    .id = 0,
    .name = "arm_powerctl_set_cpu_off",
    .sstate = TRACE_ARM_POWERCTL_SET_CPU_OFF_ENABLED,
    .dstate = &_TRACE_ARM_POWERCTL_SET_CPU_OFF_DSTATE
};
TraceEvent _TRACE_ARM_POWERCTL_RESET_CPU_EVENT = {
    .id = 0,
    .name = "arm_powerctl_reset_cpu",
    .sstate = TRACE_ARM_POWERCTL_RESET_CPU_ENABLED,
    .dstate = &_TRACE_ARM_POWERCTL_RESET_CPU_DSTATE
};
TraceEvent _TRACE_ARM_PSCI_CALL_EVENT = {
    .id = 0,
    .name = "arm_psci_call",
    .sstate = TRACE_ARM_PSCI_CALL_ENABLED,
    .dstate = &_TRACE_ARM_PSCI_CALL_DSTATE
};
TraceEvent _TRACE_CPU_POST_LOAD_EVENT = {
    .id = 0,
    .name = "cpu_post_load",
    .sstate = TRACE_CPU_POST_LOAD_ENABLED,
    .dstate = &_TRACE_CPU_POST_LOAD_DSTATE
};
TraceEvent *target_arm_trace_events[] = {
    &_TRACE_ARM_GT_RECALC_EVENT,
    &_TRACE_ARM_GT_RECALC_DISABLED_EVENT,
    &_TRACE_ARM_GT_CVAL_WRITE_EVENT,
    &_TRACE_ARM_GT_TVAL_WRITE_EVENT,
    &_TRACE_ARM_GT_CTL_WRITE_EVENT,
    &_TRACE_ARM_GT_IMASK_TOGGLE_EVENT,
    &_TRACE_ARM_GT_CNTVOFF_WRITE_EVENT,
    &_TRACE_ARM_GT_CNTPOFF_WRITE_EVENT,
    &_TRACE_ARM_GT_UPDATE_IRQ_EVENT,
    &_TRACE_KVM_ARM_FIXUP_MSI_ROUTE_EVENT,
    &_TRACE_ARM_CPU_RESET_EVENT,
    &_TRACE_ARM_EMULATE_FIRMWARE_RESET_EVENT,
    &_TRACE_ARM_POWERCTL_SET_CPU_ON_EVENT,
    &_TRACE_ARM_POWERCTL_SET_CPU_ON_AND_RESET_EVENT,
    &_TRACE_ARM_POWERCTL_SET_CPU_OFF_EVENT,
    &_TRACE_ARM_POWERCTL_RESET_CPU_EVENT,
    &_TRACE_ARM_PSCI_CALL_EVENT,
    &_TRACE_CPU_POST_LOAD_EVENT,
  NULL,
};

static void trace_target_arm_register_events(void)
{
    trace_event_register_group(target_arm_trace_events);
}
trace_init(trace_target_arm_register_events)
