/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_CRYPTO_GENERATED_TRACERS_H
#define TRACE_CRYPTO_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_LOAD_DH_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_GET_PATH_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_ANON_LOAD_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_PSK_LOAD_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_BASIC_CONSTRAINTS_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_USAGE_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_PURPOSE_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_LIST_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_SESSION_NEW_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_SESSION_CHECK_CREDS_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_SESSION_CHECK_X509_DN_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_SESSION_PARAMETERS_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_SESSION_BUG1717_WORKAROUND_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CIPHER_SUITE_PRIORITY_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CIPHER_SUITE_INFO_EVENT;
extern TraceEvent _TRACE_QCRYPTO_TLS_CIPHER_SUITE_COUNT_EVENT;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_LOAD_DH_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_GET_PATH_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_ANON_LOAD_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_PSK_LOAD_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_BASIC_CONSTRAINTS_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_USAGE_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_PURPOSE_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_LIST_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_SESSION_NEW_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_SESSION_CHECK_CREDS_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_SESSION_CHECK_X509_DN_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_SESSION_PARAMETERS_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_SESSION_BUG1717_WORKAROUND_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CIPHER_SUITE_PRIORITY_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CIPHER_SUITE_INFO_DSTATE;
extern uint16_t _TRACE_QCRYPTO_TLS_CIPHER_SUITE_COUNT_DSTATE;
#define TRACE_QCRYPTO_TLS_CREDS_LOAD_DH_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_GET_PATH_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_ANON_LOAD_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_PSK_LOAD_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_BASIC_CONSTRAINTS_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_USAGE_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_PURPOSE_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_ENABLED 1
#define TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_LIST_ENABLED 1
#define TRACE_QCRYPTO_TLS_SESSION_NEW_ENABLED 1
#define TRACE_QCRYPTO_TLS_SESSION_CHECK_CREDS_ENABLED 1
#define TRACE_QCRYPTO_TLS_SESSION_CHECK_X509_DN_ENABLED 1
#define TRACE_QCRYPTO_TLS_SESSION_PARAMETERS_ENABLED 1
#define TRACE_QCRYPTO_TLS_SESSION_BUG1717_WORKAROUND_ENABLED 1
#define TRACE_QCRYPTO_TLS_CIPHER_SUITE_PRIORITY_ENABLED 1
#define TRACE_QCRYPTO_TLS_CIPHER_SUITE_INFO_ENABLED 1
#define TRACE_QCRYPTO_TLS_CIPHER_SUITE_COUNT_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QCRYPTO_TLS_CREDS_LOAD_DH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_LOAD_DH) || \
    false)

static inline void trace_qcrypto_tls_creds_load_dh(void *creds, const char *filename)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_LOAD_DH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_load_dh " "TLS creds load DH creds=%p filename=%s" "\n", creds, filename);
#line 77 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_GET_PATH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_GET_PATH) || \
    false)

static inline void trace_qcrypto_tls_creds_get_path(void *creds, const char *filename, const char *path)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_GET_PATH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_get_path " "TLS creds path creds=%p filename=%s path=%s" "\n", creds, filename, path);
#line 92 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_ANON_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_ANON_LOAD) || \
    false)

static inline void trace_qcrypto_tls_creds_anon_load(void *creds, const char *dir)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_ANON_LOAD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_anon_load " "TLS creds anon load creds=%p dir=%s" "\n", creds, dir);
#line 107 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_PSK_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_PSK_LOAD) || \
    false)

static inline void trace_qcrypto_tls_creds_psk_load(void *creds, const char *dir)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_PSK_LOAD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_psk_load " "TLS creds psk load creds=%p dir=%s" "\n", creds, dir);
#line 122 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_X509_LOAD) || \
    false)

static inline void trace_qcrypto_tls_creds_x509_load(void *creds, const char *dir)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_X509_LOAD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_x509_load " "TLS creds x509 load creds=%p dir=%s" "\n", creds, dir);
#line 137 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_BASIC_CONSTRAINTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_BASIC_CONSTRAINTS) || \
    false)

static inline void trace_qcrypto_tls_creds_x509_check_basic_constraints(void *creds, const char *file, int status)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_BASIC_CONSTRAINTS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_x509_check_basic_constraints " "TLS creds x509 check basic constraints creds=%p file=%s status=%d" "\n", creds, file, status);
#line 152 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_USAGE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_USAGE) || \
    false)

static inline void trace_qcrypto_tls_creds_x509_check_key_usage(void *creds, const char *file, int status, int usage, int critical)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_USAGE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_x509_check_key_usage " "TLS creds x509 check key usage creds=%p file=%s status=%d usage=%d critical=%d" "\n", creds, file, status, usage, critical);
#line 167 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_PURPOSE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_PURPOSE) || \
    false)

static inline void trace_qcrypto_tls_creds_x509_check_key_purpose(void *creds, const char *file, int status, const char *usage, int critical)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_X509_CHECK_KEY_PURPOSE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_x509_check_key_purpose " "TLS creds x509 check key usage creds=%p file=%s status=%d usage=%s critical=%d" "\n", creds, file, status, usage, critical);
#line 182 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT) || \
    false)

static inline void trace_qcrypto_tls_creds_x509_load_cert(void *creds, int isServer, const char *file)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_x509_load_cert " "TLS creds x509 load cert creds=%p isServer=%d file=%s" "\n", creds, isServer, file);
#line 197 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_LIST_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_LIST) || \
    false)

static inline void trace_qcrypto_tls_creds_x509_load_cert_list(void *creds, const char *file)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CREDS_X509_LOAD_CERT_LIST)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "../crypto/trace-events"
            qemu_log("qcrypto_tls_creds_x509_load_cert_list " "TLS creds x509 load cert list creds=%p file=%s" "\n", creds, file);
#line 212 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_SESSION_NEW_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_SESSION_NEW) || \
    false)

static inline void trace_qcrypto_tls_session_new(void *session, void *creds, const char *hostname, const char *authzid, int endpoint)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_SESSION_NEW)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "../crypto/trace-events"
            qemu_log("qcrypto_tls_session_new " "TLS session new session=%p creds=%p hostname=%s authzid=%s endpoint=%d" "\n", session, creds, hostname, authzid, endpoint);
#line 227 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_SESSION_CHECK_CREDS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_SESSION_CHECK_CREDS) || \
    false)

static inline void trace_qcrypto_tls_session_check_creds(void *session, const char *status)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_SESSION_CHECK_CREDS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 23 "../crypto/trace-events"
            qemu_log("qcrypto_tls_session_check_creds " "TLS session check creds session=%p status=%s" "\n", session, status);
#line 242 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_SESSION_CHECK_X509_DN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_SESSION_CHECK_X509_DN) || \
    false)

static inline void trace_qcrypto_tls_session_check_x509_dn(void *session, const char *dname)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_SESSION_CHECK_X509_DN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 24 "../crypto/trace-events"
            qemu_log("qcrypto_tls_session_check_x509_dn " "TLS session check x509 distinguished name session=%p dname=%s" "\n", session, dname);
#line 257 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_SESSION_PARAMETERS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_SESSION_PARAMETERS) || \
    false)

static inline void trace_qcrypto_tls_session_parameters(void *session, int threadSafety, int protocol, int cipher)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_SESSION_PARAMETERS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 25 "../crypto/trace-events"
            qemu_log("qcrypto_tls_session_parameters " "TLS session parameters session=%p threadSafety=%d protocol=%d cipher=%d" "\n", session, threadSafety, protocol, cipher);
#line 272 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_SESSION_BUG1717_WORKAROUND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_SESSION_BUG1717_WORKAROUND) || \
    false)

static inline void trace_qcrypto_tls_session_bug1717_workaround(void *session)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_SESSION_BUG1717_WORKAROUND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 26 "../crypto/trace-events"
            qemu_log("qcrypto_tls_session_bug1717_workaround " "TLS session bug1717 workaround session=%p" "\n", session);
#line 287 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CIPHER_SUITE_PRIORITY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CIPHER_SUITE_PRIORITY) || \
    false)

static inline void trace_qcrypto_tls_cipher_suite_priority(const char *name)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CIPHER_SUITE_PRIORITY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 29 "../crypto/trace-events"
            qemu_log("qcrypto_tls_cipher_suite_priority " "priority: %s" "\n", name);
#line 302 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CIPHER_SUITE_INFO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CIPHER_SUITE_INFO) || \
    false)

static inline void trace_qcrypto_tls_cipher_suite_info(uint8_t data0, uint8_t data1, const char *version, const char *name)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CIPHER_SUITE_INFO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 30 "../crypto/trace-events"
            qemu_log("qcrypto_tls_cipher_suite_info " "data=[0x%02x,0x%02x] version=%s name=%s" "\n", data0, data1, version, name);
#line 317 "trace/trace-crypto.h"
        }
    }
}

#define TRACE_QCRYPTO_TLS_CIPHER_SUITE_COUNT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QCRYPTO_TLS_CIPHER_SUITE_COUNT) || \
    false)

static inline void trace_qcrypto_tls_cipher_suite_count(unsigned count)
{
    if (trace_event_get_state(TRACE_QCRYPTO_TLS_CIPHER_SUITE_COUNT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 31 "../crypto/trace-events"
            qemu_log("qcrypto_tls_cipher_suite_count " "count: %u" "\n", count);
#line 332 "trace/trace-crypto.h"
        }
    }
}
#endif /* TRACE_CRYPTO_GENERATED_TRACERS_H */
