/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_MONITOR_GENERATED_TRACERS_H
#define TRACE_MONITOR_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_HANDLE_HMP_COMMAND_EVENT;
extern TraceEvent _TRACE_MONITOR_PROTOCOL_EVENT_HANDLER_EVENT;
extern TraceEvent _TRACE_MONITOR_PROTOCOL_EVENT_EMIT_EVENT;
extern TraceEvent _TRACE_MONITOR_PROTOCOL_EVENT_QUEUE_EVENT;
extern TraceEvent _TRACE_MONITOR_SUSPEND_EVENT;
extern TraceEvent _TRACE_MONITOR_QMP_IN_BAND_ENQUEUE_EVENT;
extern TraceEvent _TRACE_MONITOR_QMP_IN_BAND_DEQUEUE_EVENT;
extern TraceEvent _TRACE_MONITOR_QMP_CMD_IN_BAND_EVENT;
extern TraceEvent _TRACE_MONITOR_QMP_ERR_IN_BAND_EVENT;
extern TraceEvent _TRACE_MONITOR_QMP_CMD_OUT_OF_BAND_EVENT;
extern TraceEvent _TRACE_MONITOR_QMP_RESPOND_EVENT;
extern TraceEvent _TRACE_HANDLE_QMP_COMMAND_EVENT;
extern uint16_t _TRACE_HANDLE_HMP_COMMAND_DSTATE;
extern uint16_t _TRACE_MONITOR_PROTOCOL_EVENT_HANDLER_DSTATE;
extern uint16_t _TRACE_MONITOR_PROTOCOL_EVENT_EMIT_DSTATE;
extern uint16_t _TRACE_MONITOR_PROTOCOL_EVENT_QUEUE_DSTATE;
extern uint16_t _TRACE_MONITOR_SUSPEND_DSTATE;
extern uint16_t _TRACE_MONITOR_QMP_IN_BAND_ENQUEUE_DSTATE;
extern uint16_t _TRACE_MONITOR_QMP_IN_BAND_DEQUEUE_DSTATE;
extern uint16_t _TRACE_MONITOR_QMP_CMD_IN_BAND_DSTATE;
extern uint16_t _TRACE_MONITOR_QMP_ERR_IN_BAND_DSTATE;
extern uint16_t _TRACE_MONITOR_QMP_CMD_OUT_OF_BAND_DSTATE;
extern uint16_t _TRACE_MONITOR_QMP_RESPOND_DSTATE;
extern uint16_t _TRACE_HANDLE_QMP_COMMAND_DSTATE;
#define TRACE_HANDLE_HMP_COMMAND_ENABLED 1
#define TRACE_MONITOR_PROTOCOL_EVENT_HANDLER_ENABLED 1
#define TRACE_MONITOR_PROTOCOL_EVENT_EMIT_ENABLED 1
#define TRACE_MONITOR_PROTOCOL_EVENT_QUEUE_ENABLED 1
#define TRACE_MONITOR_SUSPEND_ENABLED 1
#define TRACE_MONITOR_QMP_IN_BAND_ENQUEUE_ENABLED 1
#define TRACE_MONITOR_QMP_IN_BAND_DEQUEUE_ENABLED 1
#define TRACE_MONITOR_QMP_CMD_IN_BAND_ENABLED 1
#define TRACE_MONITOR_QMP_ERR_IN_BAND_ENABLED 1
#define TRACE_MONITOR_QMP_CMD_OUT_OF_BAND_ENABLED 1
#define TRACE_MONITOR_QMP_RESPOND_ENABLED 1
#define TRACE_HANDLE_QMP_COMMAND_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_HANDLE_HMP_COMMAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HANDLE_HMP_COMMAND) || \
    false)

static inline void trace_handle_hmp_command(void *mon, const char *cmdline)
{
    if (trace_event_get_state(TRACE_HANDLE_HMP_COMMAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../monitor/trace-events"
            qemu_log("handle_hmp_command " "mon %p cmdline: %s" "\n", mon, cmdline);
#line 59 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_PROTOCOL_EVENT_HANDLER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_PROTOCOL_EVENT_HANDLER) || \
    false)

static inline void trace_monitor_protocol_event_handler(uint32_t event, void *qdict)
{
    if (trace_event_get_state(TRACE_MONITOR_PROTOCOL_EVENT_HANDLER)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../monitor/trace-events"
            qemu_log("monitor_protocol_event_handler " "event=%d data=%p" "\n", event, qdict);
#line 74 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_PROTOCOL_EVENT_EMIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_PROTOCOL_EVENT_EMIT) || \
    false)

static inline void trace_monitor_protocol_event_emit(uint32_t event, void *data)
{
    if (trace_event_get_state(TRACE_MONITOR_PROTOCOL_EVENT_EMIT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../monitor/trace-events"
            qemu_log("monitor_protocol_event_emit " "event=%d data=%p" "\n", event, data);
#line 89 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_PROTOCOL_EVENT_QUEUE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_PROTOCOL_EVENT_QUEUE) || \
    false)

static inline void trace_monitor_protocol_event_queue(uint32_t event, void *qdict, uint64_t rate)
{
    if (trace_event_get_state(TRACE_MONITOR_PROTOCOL_EVENT_QUEUE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "../monitor/trace-events"
            qemu_log("monitor_protocol_event_queue " "event=%d data=%p rate=%" PRId64 "\n", event, qdict, rate);
#line 104 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_SUSPEND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_SUSPEND) || \
    false)

static inline void trace_monitor_suspend(void *ptr, int cnt)
{
    if (trace_event_get_state(TRACE_MONITOR_SUSPEND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "../monitor/trace-events"
            qemu_log("monitor_suspend " "mon %p: %d" "\n", ptr, cnt);
#line 119 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_QMP_IN_BAND_ENQUEUE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_QMP_IN_BAND_ENQUEUE) || \
    false)

static inline void trace_monitor_qmp_in_band_enqueue(void *req, void *mon, unsigned len)
{
    if (trace_event_get_state(TRACE_MONITOR_QMP_IN_BAND_ENQUEUE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../monitor/trace-events"
            qemu_log("monitor_qmp_in_band_enqueue " "%p mon %p len %u" "\n", req, mon, len);
#line 134 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_QMP_IN_BAND_DEQUEUE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_QMP_IN_BAND_DEQUEUE) || \
    false)

static inline void trace_monitor_qmp_in_band_dequeue(void *req, unsigned len)
{
    if (trace_event_get_state(TRACE_MONITOR_QMP_IN_BAND_DEQUEUE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../monitor/trace-events"
            qemu_log("monitor_qmp_in_band_dequeue " "%p len %u" "\n", req, len);
#line 149 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_QMP_CMD_IN_BAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_QMP_CMD_IN_BAND) || \
    false)

static inline void trace_monitor_qmp_cmd_in_band(const char *id)
{
    if (trace_event_get_state(TRACE_MONITOR_QMP_CMD_IN_BAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "../monitor/trace-events"
            qemu_log("monitor_qmp_cmd_in_band " "%s" "\n", id);
#line 164 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_QMP_ERR_IN_BAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_QMP_ERR_IN_BAND) || \
    false)

static inline void trace_monitor_qmp_err_in_band(const char *desc)
{
    if (trace_event_get_state(TRACE_MONITOR_QMP_ERR_IN_BAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "../monitor/trace-events"
            qemu_log("monitor_qmp_err_in_band " "%s" "\n", desc);
#line 179 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_QMP_CMD_OUT_OF_BAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_QMP_CMD_OUT_OF_BAND) || \
    false)

static inline void trace_monitor_qmp_cmd_out_of_band(const char *id)
{
    if (trace_event_get_state(TRACE_MONITOR_QMP_CMD_OUT_OF_BAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../monitor/trace-events"
            qemu_log("monitor_qmp_cmd_out_of_band " "%s" "\n", id);
#line 194 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_MONITOR_QMP_RESPOND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MONITOR_QMP_RESPOND) || \
    false)

static inline void trace_monitor_qmp_respond(void *mon, const char *json)
{
    if (trace_event_get_state(TRACE_MONITOR_QMP_RESPOND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../monitor/trace-events"
            qemu_log("monitor_qmp_respond " "mon %p resp: %s" "\n", mon, json);
#line 209 "trace/trace-monitor.h"
        }
    }
}

#define TRACE_HANDLE_QMP_COMMAND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HANDLE_QMP_COMMAND) || \
    false)

static inline void trace_handle_qmp_command(void *mon, const char *req)
{
    if (trace_event_get_state(TRACE_HANDLE_QMP_COMMAND)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "../monitor/trace-events"
            qemu_log("handle_qmp_command " "mon %p req: %s" "\n", mon, req);
#line 224 "trace/trace-monitor.h"
        }
    }
}
#endif /* TRACE_MONITOR_GENERATED_TRACERS_H */
