/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_SH4_GENERATED_TRACERS_H
#define TRACE_HW_SH4_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_SH7750_PORTA_EVENT;
extern TraceEvent _TRACE_SH7750_PORTB_EVENT;
extern uint16_t _TRACE_SH7750_PORTA_DSTATE;
extern uint16_t _TRACE_SH7750_PORTB_DSTATE;
#define TRACE_SH7750_PORTA_ENABLED 1
#define TRACE_SH7750_PORTB_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_SH7750_PORTA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SH7750_PORTA) || \
    false)

static inline void trace_sh7750_porta(uint16_t prev, uint16_t cur, uint16_t pdtr, uint16_t pctr)
{
    if (trace_event_get_state(TRACE_SH7750_PORTA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 2 "../hw/sh4/trace-events"
            qemu_log("sh7750_porta " "porta changed from 0x%04x to 0x%04x (pdtra=0x%04x, pctra=0x%08x)" "\n", prev, cur, pdtr, pctr);
#line 29 "trace/trace-hw_sh4.h"
        }
    }
}

#define TRACE_SH7750_PORTB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SH7750_PORTB) || \
    false)

static inline void trace_sh7750_portb(uint16_t prev, uint16_t cur, uint16_t pdtr, uint16_t pctr)
{
    if (trace_event_get_state(TRACE_SH7750_PORTB)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "../hw/sh4/trace-events"
            qemu_log("sh7750_portb " "portb changed from 0x%04x to 0x%04x (pdtrb=0x%04x, pctrb=0x%08x)" "\n", prev, cur, pdtr, pctr);
#line 44 "trace/trace-hw_sh4.h"
        }
    }
}
#endif /* TRACE_HW_SH4_GENERATED_TRACERS_H */
