/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_TARGET_S390X_KVM_GENERATED_TRACERS_H
#define TRACE_TARGET_S390X_KVM_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_KVM_ENABLE_CMMA_EVENT;
extern TraceEvent _TRACE_KVM_CLEAR_CMMA_EVENT;
extern TraceEvent _TRACE_KVM_FAILED_CPU_STATE_SET_EVENT;
extern TraceEvent _TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD_EVENT;
extern TraceEvent _TRACE_KVM_SW_BREAKPOINT_EVENT;
extern TraceEvent _TRACE_KVM_INSN_UNHANDLED_PRIV_EVENT;
extern TraceEvent _TRACE_KVM_INSN_DIAG_EVENT;
extern TraceEvent _TRACE_KVM_INSN_EVENT;
extern TraceEvent _TRACE_KVM_INTERCEPT_EVENT;
extern TraceEvent _TRACE_KVM_MSI_ROUTE_FIXUP_EVENT;
extern uint16_t _TRACE_KVM_ENABLE_CMMA_DSTATE;
extern uint16_t _TRACE_KVM_CLEAR_CMMA_DSTATE;
extern uint16_t _TRACE_KVM_FAILED_CPU_STATE_SET_DSTATE;
extern uint16_t _TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD_DSTATE;
extern uint16_t _TRACE_KVM_SW_BREAKPOINT_DSTATE;
extern uint16_t _TRACE_KVM_INSN_UNHANDLED_PRIV_DSTATE;
extern uint16_t _TRACE_KVM_INSN_DIAG_DSTATE;
extern uint16_t _TRACE_KVM_INSN_DSTATE;
extern uint16_t _TRACE_KVM_INTERCEPT_DSTATE;
extern uint16_t _TRACE_KVM_MSI_ROUTE_FIXUP_DSTATE;
#define TRACE_KVM_ENABLE_CMMA_ENABLED 1
#define TRACE_KVM_CLEAR_CMMA_ENABLED 1
#define TRACE_KVM_FAILED_CPU_STATE_SET_ENABLED 1
#define TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD_ENABLED 1
#define TRACE_KVM_SW_BREAKPOINT_ENABLED 1
#define TRACE_KVM_INSN_UNHANDLED_PRIV_ENABLED 1
#define TRACE_KVM_INSN_DIAG_ENABLED 1
#define TRACE_KVM_INSN_ENABLED 1
#define TRACE_KVM_INTERCEPT_ENABLED 1
#define TRACE_KVM_MSI_ROUTE_FIXUP_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_KVM_ENABLE_CMMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_ENABLE_CMMA) || \
    false)

static inline void trace_kvm_enable_cmma(int rc)
{
    if (trace_event_get_state(TRACE_KVM_ENABLE_CMMA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_enable_cmma " "CMMA: enabling with result code %d" "\n", rc);
#line 53 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_CLEAR_CMMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_CLEAR_CMMA) || \
    false)

static inline void trace_kvm_clear_cmma(int rc)
{
    if (trace_event_get_state(TRACE_KVM_CLEAR_CMMA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_clear_cmma " "CMMA: clearing with result code %d" "\n", rc);
#line 68 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_FAILED_CPU_STATE_SET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_FAILED_CPU_STATE_SET) || \
    false)

static inline void trace_kvm_failed_cpu_state_set(int cpu_index, uint8_t state, const char *msg)
{
    if (trace_event_get_state(TRACE_KVM_FAILED_CPU_STATE_SET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_failed_cpu_state_set " "Warning: Unable to set cpu %d state %" PRIu8 " to KVM: %s" "\n", cpu_index, state, msg);
#line 83 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD) || \
    false)

static inline void trace_kvm_assign_subch_ioeventfd(int fd, uint32_t addr, bool assign, int datamatch)
{
    if (trace_event_get_state(TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_assign_subch_ioeventfd " "fd: %d sch: @0x%x assign: %d vq: %d" "\n", fd, addr, assign, datamatch);
#line 98 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_SW_BREAKPOINT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_SW_BREAKPOINT) || \
    false)

static inline void trace_kvm_sw_breakpoint(uint32_t n)
{
    if (trace_event_get_state(TRACE_KVM_SW_BREAKPOINT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_sw_breakpoint " "KVM: will use %d-byte sw breakpoints" "\n", n);
#line 113 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_INSN_UNHANDLED_PRIV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_INSN_UNHANDLED_PRIV) || \
    false)

static inline void trace_kvm_insn_unhandled_priv(uint32_t x)
{
    if (trace_event_get_state(TRACE_KVM_INSN_UNHANDLED_PRIV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_insn_unhandled_priv " "KVM: unhandled PRIV: 0x%x" "\n", x);
#line 128 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_INSN_DIAG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_INSN_DIAG) || \
    false)

static inline void trace_kvm_insn_diag(uint32_t x)
{
    if (trace_event_get_state(TRACE_KVM_INSN_DIAG)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_insn_diag " "KVM: unknown DIAG: 0x%x" "\n", x);
#line 143 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_INSN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_INSN) || \
    false)

static inline void trace_kvm_insn(uint32_t ipa, uint32_t ipb)
{
    if (trace_event_get_state(TRACE_KVM_INSN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_insn " "handle_instruction 0x%x 0x%x" "\n", ipa, ipb);
#line 158 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_INTERCEPT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_INTERCEPT) || \
    false)

static inline void trace_kvm_intercept(uint32_t icpt_code, uint64_t psw_addr)
{
    if (trace_event_get_state(TRACE_KVM_INTERCEPT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_intercept " "intercept: 0x%x (at 0x%"PRIx64"lx)" "\n", icpt_code, psw_addr);
#line 173 "trace/trace-target_s390x_kvm.h"
        }
    }
}

#define TRACE_KVM_MSI_ROUTE_FIXUP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_KVM_MSI_ROUTE_FIXUP) || \
    false)

static inline void trace_kvm_msi_route_fixup(const char*msg)
{
    if (trace_event_get_state(TRACE_KVM_MSI_ROUTE_FIXUP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../target/s390x/kvm/trace-events"
            qemu_log("kvm_msi_route_fixup " "%s" "\n", msg);
#line 188 "trace/trace-target_s390x_kvm.h"
        }
    }
}
#endif /* TRACE_TARGET_S390X_KVM_GENERATED_TRACERS_H */
