/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_UTIL_GENERATED_TRACERS_H
#define TRACE_UTIL_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_RUN_POLL_HANDLERS_BEGIN_EVENT;
extern TraceEvent _TRACE_RUN_POLL_HANDLERS_END_EVENT;
extern TraceEvent _TRACE_POLL_SHRINK_EVENT;
extern TraceEvent _TRACE_POLL_GROW_EVENT;
extern TraceEvent _TRACE_POLL_ADD_EVENT;
extern TraceEvent _TRACE_POLL_REMOVE_EVENT;
extern TraceEvent _TRACE_AIO_CO_SCHEDULE_EVENT;
extern TraceEvent _TRACE_AIO_CO_SCHEDULE_BH_CB_EVENT;
extern TraceEvent _TRACE_REENTRANT_AIO_EVENT;
extern TraceEvent _TRACE_THREAD_POOL_SUBMIT_AIO_EVENT;
extern TraceEvent _TRACE_THREAD_POOL_COMPLETE_AIO_EVENT;
extern TraceEvent _TRACE_THREAD_POOL_CANCEL_AIO_EVENT;
extern TraceEvent _TRACE_BUFFER_RESIZE_EVENT;
extern TraceEvent _TRACE_BUFFER_MOVE_EMPTY_EVENT;
extern TraceEvent _TRACE_BUFFER_MOVE_EVENT;
extern TraceEvent _TRACE_BUFFER_FREE_EVENT;
extern TraceEvent _TRACE_FDMON_IO_URING_ADD_SQE_EVENT;
extern TraceEvent _TRACE_FDMON_IO_URING_CQE_HANDLER_EVENT;
extern TraceEvent _TRACE_QEMU_FILE_MONITOR_ADD_WATCH_EVENT;
extern TraceEvent _TRACE_QEMU_FILE_MONITOR_REMOVE_WATCH_EVENT;
extern TraceEvent _TRACE_QEMU_FILE_MONITOR_NEW_EVENT;
extern TraceEvent _TRACE_QEMU_FILE_MONITOR_ENABLE_WATCH_EVENT;
extern TraceEvent _TRACE_QEMU_FILE_MONITOR_DISABLE_WATCH_EVENT;
extern TraceEvent _TRACE_QEMU_FILE_MONITOR_EVENT_EVENT;
extern TraceEvent _TRACE_QEMU_FILE_MONITOR_DISPATCH_EVENT;
extern TraceEvent _TRACE_QEMU_AIO_COROUTINE_ENTER_EVENT;
extern TraceEvent _TRACE_QEMU_COROUTINE_YIELD_EVENT;
extern TraceEvent _TRACE_QEMU_COROUTINE_TERMINATE_EVENT;
extern TraceEvent _TRACE_QEMU_CO_MUTEX_LOCK_UNCONTENDED_EVENT;
extern TraceEvent _TRACE_QEMU_CO_MUTEX_LOCK_ENTRY_EVENT;
extern TraceEvent _TRACE_QEMU_CO_MUTEX_LOCK_RETURN_EVENT;
extern TraceEvent _TRACE_QEMU_CO_MUTEX_UNLOCK_ENTRY_EVENT;
extern TraceEvent _TRACE_QEMU_CO_MUTEX_UNLOCK_RETURN_EVENT;
extern TraceEvent _TRACE_QEMU_MEMALIGN_EVENT;
extern TraceEvent _TRACE_QEMU_ANON_RAM_ALLOC_EVENT;
extern TraceEvent _TRACE_QEMU_VFREE_EVENT;
extern TraceEvent _TRACE_QEMU_ANON_RAM_FREE_EVENT;
extern TraceEvent _TRACE_WIN32_MAP_ALLOC_EVENT;
extern TraceEvent _TRACE_WIN32_MAP_FREE_EVENT;
extern TraceEvent _TRACE_HBITMAP_ITER_SKIP_WORDS_EVENT;
extern TraceEvent _TRACE_HBITMAP_RESET_EVENT;
extern TraceEvent _TRACE_HBITMAP_SET_EVENT;
extern TraceEvent _TRACE_LOCKCNT_FAST_PATH_ATTEMPT_EVENT;
extern TraceEvent _TRACE_LOCKCNT_FAST_PATH_SUCCESS_EVENT;
extern TraceEvent _TRACE_LOCKCNT_UNLOCK_ATTEMPT_EVENT;
extern TraceEvent _TRACE_LOCKCNT_UNLOCK_SUCCESS_EVENT;
extern TraceEvent _TRACE_LOCKCNT_FUTEX_WAIT_PREPARE_EVENT;
extern TraceEvent _TRACE_LOCKCNT_FUTEX_WAIT_EVENT;
extern TraceEvent _TRACE_LOCKCNT_FUTEX_WAIT_RESUME_EVENT;
extern TraceEvent _TRACE_LOCKCNT_FUTEX_WAKE_EVENT;
extern TraceEvent _TRACE_SOCKET_LISTEN_EVENT;
extern TraceEvent _TRACE_QEMU_MUTEX_LOCK_EVENT;
extern TraceEvent _TRACE_QEMU_MUTEX_LOCKED_EVENT;
extern TraceEvent _TRACE_QEMU_MUTEX_UNLOCK_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_DMA_RESET_TEMPORARY_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_RAM_BLOCK_ADDED_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_RAM_BLOCK_REMOVED_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_DUMP_MAPPING_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_FIND_MAPPING_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_NEW_MAPPING_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_DO_MAPPING_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_DMA_MAP_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_DMA_MAPPED_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_DMA_UNMAP_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_PCI_READ_CONFIG_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_PCI_WRITE_CONFIG_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_REGION_INFO_EVENT;
extern TraceEvent _TRACE_QEMU_VFIO_PCI_MAP_BAR_EVENT;
extern TraceEvent _TRACE_UFFD_DETECT_OPEN_MODE_EVENT;
extern TraceEvent _TRACE_UFFD_QUERY_FEATURES_NOSYS_EVENT;
extern TraceEvent _TRACE_UFFD_QUERY_FEATURES_API_FAILED_EVENT;
extern TraceEvent _TRACE_UFFD_CREATE_FD_NOSYS_EVENT;
extern TraceEvent _TRACE_UFFD_CREATE_FD_API_FAILED_EVENT;
extern TraceEvent _TRACE_UFFD_CREATE_FD_API_NOIOCTL_EVENT;
extern TraceEvent _TRACE_UFFD_REGISTER_MEMORY_FAILED_EVENT;
extern TraceEvent _TRACE_UFFD_UNREGISTER_MEMORY_FAILED_EVENT;
extern TraceEvent _TRACE_MODULE_LOAD_MODULE_EVENT;
extern TraceEvent _TRACE_MODULE_LOOKUP_OBJECT_TYPE_EVENT;
extern uint16_t _TRACE_RUN_POLL_HANDLERS_BEGIN_DSTATE;
extern uint16_t _TRACE_RUN_POLL_HANDLERS_END_DSTATE;
extern uint16_t _TRACE_POLL_SHRINK_DSTATE;
extern uint16_t _TRACE_POLL_GROW_DSTATE;
extern uint16_t _TRACE_POLL_ADD_DSTATE;
extern uint16_t _TRACE_POLL_REMOVE_DSTATE;
extern uint16_t _TRACE_AIO_CO_SCHEDULE_DSTATE;
extern uint16_t _TRACE_AIO_CO_SCHEDULE_BH_CB_DSTATE;
extern uint16_t _TRACE_REENTRANT_AIO_DSTATE;
extern uint16_t _TRACE_THREAD_POOL_SUBMIT_AIO_DSTATE;
extern uint16_t _TRACE_THREAD_POOL_COMPLETE_AIO_DSTATE;
extern uint16_t _TRACE_THREAD_POOL_CANCEL_AIO_DSTATE;
extern uint16_t _TRACE_BUFFER_RESIZE_DSTATE;
extern uint16_t _TRACE_BUFFER_MOVE_EMPTY_DSTATE;
extern uint16_t _TRACE_BUFFER_MOVE_DSTATE;
extern uint16_t _TRACE_BUFFER_FREE_DSTATE;
extern uint16_t _TRACE_FDMON_IO_URING_ADD_SQE_DSTATE;
extern uint16_t _TRACE_FDMON_IO_URING_CQE_HANDLER_DSTATE;
extern uint16_t _TRACE_QEMU_FILE_MONITOR_ADD_WATCH_DSTATE;
extern uint16_t _TRACE_QEMU_FILE_MONITOR_REMOVE_WATCH_DSTATE;
extern uint16_t _TRACE_QEMU_FILE_MONITOR_NEW_DSTATE;
extern uint16_t _TRACE_QEMU_FILE_MONITOR_ENABLE_WATCH_DSTATE;
extern uint16_t _TRACE_QEMU_FILE_MONITOR_DISABLE_WATCH_DSTATE;
extern uint16_t _TRACE_QEMU_FILE_MONITOR_EVENT_DSTATE;
extern uint16_t _TRACE_QEMU_FILE_MONITOR_DISPATCH_DSTATE;
extern uint16_t _TRACE_QEMU_AIO_COROUTINE_ENTER_DSTATE;
extern uint16_t _TRACE_QEMU_COROUTINE_YIELD_DSTATE;
extern uint16_t _TRACE_QEMU_COROUTINE_TERMINATE_DSTATE;
extern uint16_t _TRACE_QEMU_CO_MUTEX_LOCK_UNCONTENDED_DSTATE;
extern uint16_t _TRACE_QEMU_CO_MUTEX_LOCK_ENTRY_DSTATE;
extern uint16_t _TRACE_QEMU_CO_MUTEX_LOCK_RETURN_DSTATE;
extern uint16_t _TRACE_QEMU_CO_MUTEX_UNLOCK_ENTRY_DSTATE;
extern uint16_t _TRACE_QEMU_CO_MUTEX_UNLOCK_RETURN_DSTATE;
extern uint16_t _TRACE_QEMU_MEMALIGN_DSTATE;
extern uint16_t _TRACE_QEMU_ANON_RAM_ALLOC_DSTATE;
extern uint16_t _TRACE_QEMU_VFREE_DSTATE;
extern uint16_t _TRACE_QEMU_ANON_RAM_FREE_DSTATE;
extern uint16_t _TRACE_WIN32_MAP_ALLOC_DSTATE;
extern uint16_t _TRACE_WIN32_MAP_FREE_DSTATE;
extern uint16_t _TRACE_HBITMAP_ITER_SKIP_WORDS_DSTATE;
extern uint16_t _TRACE_HBITMAP_RESET_DSTATE;
extern uint16_t _TRACE_HBITMAP_SET_DSTATE;
extern uint16_t _TRACE_LOCKCNT_FAST_PATH_ATTEMPT_DSTATE;
extern uint16_t _TRACE_LOCKCNT_FAST_PATH_SUCCESS_DSTATE;
extern uint16_t _TRACE_LOCKCNT_UNLOCK_ATTEMPT_DSTATE;
extern uint16_t _TRACE_LOCKCNT_UNLOCK_SUCCESS_DSTATE;
extern uint16_t _TRACE_LOCKCNT_FUTEX_WAIT_PREPARE_DSTATE;
extern uint16_t _TRACE_LOCKCNT_FUTEX_WAIT_DSTATE;
extern uint16_t _TRACE_LOCKCNT_FUTEX_WAIT_RESUME_DSTATE;
extern uint16_t _TRACE_LOCKCNT_FUTEX_WAKE_DSTATE;
extern uint16_t _TRACE_SOCKET_LISTEN_DSTATE;
extern uint16_t _TRACE_QEMU_MUTEX_LOCK_DSTATE;
extern uint16_t _TRACE_QEMU_MUTEX_LOCKED_DSTATE;
extern uint16_t _TRACE_QEMU_MUTEX_UNLOCK_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_DMA_RESET_TEMPORARY_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_RAM_BLOCK_ADDED_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_RAM_BLOCK_REMOVED_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_DUMP_MAPPING_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_FIND_MAPPING_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_NEW_MAPPING_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_DO_MAPPING_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_DMA_MAP_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_DMA_MAPPED_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_DMA_UNMAP_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_PCI_READ_CONFIG_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_PCI_WRITE_CONFIG_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_REGION_INFO_DSTATE;
extern uint16_t _TRACE_QEMU_VFIO_PCI_MAP_BAR_DSTATE;
extern uint16_t _TRACE_UFFD_DETECT_OPEN_MODE_DSTATE;
extern uint16_t _TRACE_UFFD_QUERY_FEATURES_NOSYS_DSTATE;
extern uint16_t _TRACE_UFFD_QUERY_FEATURES_API_FAILED_DSTATE;
extern uint16_t _TRACE_UFFD_CREATE_FD_NOSYS_DSTATE;
extern uint16_t _TRACE_UFFD_CREATE_FD_API_FAILED_DSTATE;
extern uint16_t _TRACE_UFFD_CREATE_FD_API_NOIOCTL_DSTATE;
extern uint16_t _TRACE_UFFD_REGISTER_MEMORY_FAILED_DSTATE;
extern uint16_t _TRACE_UFFD_UNREGISTER_MEMORY_FAILED_DSTATE;
extern uint16_t _TRACE_MODULE_LOAD_MODULE_DSTATE;
extern uint16_t _TRACE_MODULE_LOOKUP_OBJECT_TYPE_DSTATE;
#define TRACE_RUN_POLL_HANDLERS_BEGIN_ENABLED 1
#define TRACE_RUN_POLL_HANDLERS_END_ENABLED 1
#define TRACE_POLL_SHRINK_ENABLED 1
#define TRACE_POLL_GROW_ENABLED 1
#define TRACE_POLL_ADD_ENABLED 1
#define TRACE_POLL_REMOVE_ENABLED 1
#define TRACE_AIO_CO_SCHEDULE_ENABLED 1
#define TRACE_AIO_CO_SCHEDULE_BH_CB_ENABLED 1
#define TRACE_REENTRANT_AIO_ENABLED 1
#define TRACE_THREAD_POOL_SUBMIT_AIO_ENABLED 1
#define TRACE_THREAD_POOL_COMPLETE_AIO_ENABLED 1
#define TRACE_THREAD_POOL_CANCEL_AIO_ENABLED 1
#define TRACE_BUFFER_RESIZE_ENABLED 1
#define TRACE_BUFFER_MOVE_EMPTY_ENABLED 1
#define TRACE_BUFFER_MOVE_ENABLED 1
#define TRACE_BUFFER_FREE_ENABLED 1
#define TRACE_FDMON_IO_URING_ADD_SQE_ENABLED 1
#define TRACE_FDMON_IO_URING_CQE_HANDLER_ENABLED 1
#define TRACE_QEMU_FILE_MONITOR_ADD_WATCH_ENABLED 1
#define TRACE_QEMU_FILE_MONITOR_REMOVE_WATCH_ENABLED 1
#define TRACE_QEMU_FILE_MONITOR_NEW_ENABLED 1
#define TRACE_QEMU_FILE_MONITOR_ENABLE_WATCH_ENABLED 1
#define TRACE_QEMU_FILE_MONITOR_DISABLE_WATCH_ENABLED 1
#define TRACE_QEMU_FILE_MONITOR_EVENT_ENABLED 1
#define TRACE_QEMU_FILE_MONITOR_DISPATCH_ENABLED 1
#define TRACE_QEMU_AIO_COROUTINE_ENTER_ENABLED 1
#define TRACE_QEMU_COROUTINE_YIELD_ENABLED 1
#define TRACE_QEMU_COROUTINE_TERMINATE_ENABLED 1
#define TRACE_QEMU_CO_MUTEX_LOCK_UNCONTENDED_ENABLED 1
#define TRACE_QEMU_CO_MUTEX_LOCK_ENTRY_ENABLED 1
#define TRACE_QEMU_CO_MUTEX_LOCK_RETURN_ENABLED 1
#define TRACE_QEMU_CO_MUTEX_UNLOCK_ENTRY_ENABLED 1
#define TRACE_QEMU_CO_MUTEX_UNLOCK_RETURN_ENABLED 1
#define TRACE_QEMU_MEMALIGN_ENABLED 1
#define TRACE_QEMU_ANON_RAM_ALLOC_ENABLED 1
#define TRACE_QEMU_VFREE_ENABLED 1
#define TRACE_QEMU_ANON_RAM_FREE_ENABLED 1
#define TRACE_WIN32_MAP_ALLOC_ENABLED 1
#define TRACE_WIN32_MAP_FREE_ENABLED 1
#define TRACE_HBITMAP_ITER_SKIP_WORDS_ENABLED 1
#define TRACE_HBITMAP_RESET_ENABLED 1
#define TRACE_HBITMAP_SET_ENABLED 1
#define TRACE_LOCKCNT_FAST_PATH_ATTEMPT_ENABLED 1
#define TRACE_LOCKCNT_FAST_PATH_SUCCESS_ENABLED 1
#define TRACE_LOCKCNT_UNLOCK_ATTEMPT_ENABLED 1
#define TRACE_LOCKCNT_UNLOCK_SUCCESS_ENABLED 1
#define TRACE_LOCKCNT_FUTEX_WAIT_PREPARE_ENABLED 1
#define TRACE_LOCKCNT_FUTEX_WAIT_ENABLED 1
#define TRACE_LOCKCNT_FUTEX_WAIT_RESUME_ENABLED 1
#define TRACE_LOCKCNT_FUTEX_WAKE_ENABLED 1
#define TRACE_SOCKET_LISTEN_ENABLED 1
#define TRACE_QEMU_MUTEX_LOCK_ENABLED 1
#define TRACE_QEMU_MUTEX_LOCKED_ENABLED 1
#define TRACE_QEMU_MUTEX_UNLOCK_ENABLED 1
#define TRACE_QEMU_VFIO_DMA_RESET_TEMPORARY_ENABLED 1
#define TRACE_QEMU_VFIO_RAM_BLOCK_ADDED_ENABLED 1
#define TRACE_QEMU_VFIO_RAM_BLOCK_REMOVED_ENABLED 1
#define TRACE_QEMU_VFIO_DUMP_MAPPING_ENABLED 1
#define TRACE_QEMU_VFIO_FIND_MAPPING_ENABLED 1
#define TRACE_QEMU_VFIO_NEW_MAPPING_ENABLED 1
#define TRACE_QEMU_VFIO_DO_MAPPING_ENABLED 1
#define TRACE_QEMU_VFIO_DMA_MAP_ENABLED 1
#define TRACE_QEMU_VFIO_DMA_MAPPED_ENABLED 1
#define TRACE_QEMU_VFIO_DMA_UNMAP_ENABLED 1
#define TRACE_QEMU_VFIO_PCI_READ_CONFIG_ENABLED 1
#define TRACE_QEMU_VFIO_PCI_WRITE_CONFIG_ENABLED 1
#define TRACE_QEMU_VFIO_REGION_INFO_ENABLED 1
#define TRACE_QEMU_VFIO_PCI_MAP_BAR_ENABLED 1
#define TRACE_UFFD_DETECT_OPEN_MODE_ENABLED 1
#define TRACE_UFFD_QUERY_FEATURES_NOSYS_ENABLED 1
#define TRACE_UFFD_QUERY_FEATURES_API_FAILED_ENABLED 1
#define TRACE_UFFD_CREATE_FD_NOSYS_ENABLED 1
#define TRACE_UFFD_CREATE_FD_API_FAILED_ENABLED 1
#define TRACE_UFFD_CREATE_FD_API_NOIOCTL_ENABLED 1
#define TRACE_UFFD_REGISTER_MEMORY_FAILED_ENABLED 1
#define TRACE_UFFD_UNREGISTER_MEMORY_FAILED_ENABLED 1
#define TRACE_MODULE_LOAD_MODULE_ENABLED 1
#define TRACE_MODULE_LOOKUP_OBJECT_TYPE_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_RUN_POLL_HANDLERS_BEGIN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_RUN_POLL_HANDLERS_BEGIN) || \
    false)

static inline void trace_run_poll_handlers_begin(void *ctx, int64_t max_ns, int64_t timeout)
{
    if (trace_event_get_state(TRACE_RUN_POLL_HANDLERS_BEGIN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../util/trace-events"
            qemu_log("run_poll_handlers_begin " "ctx %p max_ns %"PRId64 " timeout %"PRId64 "\n", ctx, max_ns, timeout);
#line 257 "trace/trace-util.h"
        }
    }
}

#define TRACE_RUN_POLL_HANDLERS_END_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_RUN_POLL_HANDLERS_END) || \
    false)

static inline void trace_run_poll_handlers_end(void *ctx, bool progress, int64_t timeout)
{
    if (trace_event_get_state(TRACE_RUN_POLL_HANDLERS_END)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../util/trace-events"
            qemu_log("run_poll_handlers_end " "ctx %p progress %d new timeout %"PRId64 "\n", ctx, progress, timeout);
#line 272 "trace/trace-util.h"
        }
    }
}

#define TRACE_POLL_SHRINK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_POLL_SHRINK) || \
    false)

static inline void trace_poll_shrink(void *ctx, int64_t old, int64_t new)
{
    if (trace_event_get_state(TRACE_POLL_SHRINK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../util/trace-events"
            qemu_log("poll_shrink " "ctx %p old %"PRId64" new %"PRId64 "\n", ctx, old, new);
#line 287 "trace/trace-util.h"
        }
    }
}

#define TRACE_POLL_GROW_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_POLL_GROW) || \
    false)

static inline void trace_poll_grow(void *ctx, int64_t old, int64_t new)
{
    if (trace_event_get_state(TRACE_POLL_GROW)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../util/trace-events"
            qemu_log("poll_grow " "ctx %p old %"PRId64" new %"PRId64 "\n", ctx, old, new);
#line 302 "trace/trace-util.h"
        }
    }
}

#define TRACE_POLL_ADD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_POLL_ADD) || \
    false)

static inline void trace_poll_add(void *ctx, void *node, int fd, unsigned revents)
{
    if (trace_event_get_state(TRACE_POLL_ADD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../util/trace-events"
            qemu_log("poll_add " "ctx %p node %p fd %d revents 0x%x" "\n", ctx, node, fd, revents);
#line 317 "trace/trace-util.h"
        }
    }
}

#define TRACE_POLL_REMOVE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_POLL_REMOVE) || \
    false)

static inline void trace_poll_remove(void *ctx, void *node, int fd)
{
    if (trace_event_get_state(TRACE_POLL_REMOVE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "../util/trace-events"
            qemu_log("poll_remove " "ctx %p node %p fd %d" "\n", ctx, node, fd);
#line 332 "trace/trace-util.h"
        }
    }
}

#define TRACE_AIO_CO_SCHEDULE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_AIO_CO_SCHEDULE) || \
    false)

static inline void trace_aio_co_schedule(void *ctx, void *co)
{
    if (trace_event_get_state(TRACE_AIO_CO_SCHEDULE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../util/trace-events"
            qemu_log("aio_co_schedule " "ctx %p co %p" "\n", ctx, co);
#line 347 "trace/trace-util.h"
        }
    }
}

#define TRACE_AIO_CO_SCHEDULE_BH_CB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_AIO_CO_SCHEDULE_BH_CB) || \
    false)

static inline void trace_aio_co_schedule_bh_cb(void *ctx, void *co)
{
    if (trace_event_get_state(TRACE_AIO_CO_SCHEDULE_BH_CB)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../util/trace-events"
            qemu_log("aio_co_schedule_bh_cb " "ctx %p co %p" "\n", ctx, co);
#line 362 "trace/trace-util.h"
        }
    }
}

#define TRACE_REENTRANT_AIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_REENTRANT_AIO) || \
    false)

static inline void trace_reentrant_aio(void *ctx, const char *name)
{
    if (trace_event_get_state(TRACE_REENTRANT_AIO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../util/trace-events"
            qemu_log("reentrant_aio " "ctx %p name %s" "\n", ctx, name);
#line 377 "trace/trace-util.h"
        }
    }
}

#define TRACE_THREAD_POOL_SUBMIT_AIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_THREAD_POOL_SUBMIT_AIO) || \
    false)

static inline void trace_thread_pool_submit_aio(void *pool, void *req, void *opaque)
{
    if (trace_event_get_state(TRACE_THREAD_POOL_SUBMIT_AIO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../util/trace-events"
            qemu_log("thread_pool_submit_aio " "pool %p req %p opaque %p" "\n", pool, req, opaque);
#line 392 "trace/trace-util.h"
        }
    }
}

#define TRACE_THREAD_POOL_COMPLETE_AIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_THREAD_POOL_COMPLETE_AIO) || \
    false)

static inline void trace_thread_pool_complete_aio(void *pool, void *req, void *opaque, int ret)
{
    if (trace_event_get_state(TRACE_THREAD_POOL_COMPLETE_AIO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../util/trace-events"
            qemu_log("thread_pool_complete_aio " "pool %p req %p opaque %p ret %d" "\n", pool, req, opaque, ret);
#line 407 "trace/trace-util.h"
        }
    }
}

#define TRACE_THREAD_POOL_CANCEL_AIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_THREAD_POOL_CANCEL_AIO) || \
    false)

static inline void trace_thread_pool_cancel_aio(void *req, void *opaque)
{
    if (trace_event_get_state(TRACE_THREAD_POOL_CANCEL_AIO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "../util/trace-events"
            qemu_log("thread_pool_cancel_aio " "req %p opaque %p" "\n", req, opaque);
#line 422 "trace/trace-util.h"
        }
    }
}

#define TRACE_BUFFER_RESIZE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BUFFER_RESIZE) || \
    false)

static inline void trace_buffer_resize(const char *buf, size_t olen, size_t len)
{
    if (trace_event_get_state(TRACE_BUFFER_RESIZE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "../util/trace-events"
            qemu_log("buffer_resize " "%s: old %zd, new %zd" "\n", buf, olen, len);
#line 437 "trace/trace-util.h"
        }
    }
}

#define TRACE_BUFFER_MOVE_EMPTY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BUFFER_MOVE_EMPTY) || \
    false)

static inline void trace_buffer_move_empty(const char *buf, size_t len, const char *from)
{
    if (trace_event_get_state(TRACE_BUFFER_MOVE_EMPTY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 23 "../util/trace-events"
            qemu_log("buffer_move_empty " "%s: %zd bytes from %s" "\n", buf, len, from);
#line 452 "trace/trace-util.h"
        }
    }
}

#define TRACE_BUFFER_MOVE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BUFFER_MOVE) || \
    false)

static inline void trace_buffer_move(const char *buf, size_t len, const char *from)
{
    if (trace_event_get_state(TRACE_BUFFER_MOVE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 24 "../util/trace-events"
            qemu_log("buffer_move " "%s: %zd bytes from %s" "\n", buf, len, from);
#line 467 "trace/trace-util.h"
        }
    }
}

#define TRACE_BUFFER_FREE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BUFFER_FREE) || \
    false)

static inline void trace_buffer_free(const char *buf, size_t len)
{
    if (trace_event_get_state(TRACE_BUFFER_FREE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 25 "../util/trace-events"
            qemu_log("buffer_free " "%s: capacity %zd" "\n", buf, len);
#line 482 "trace/trace-util.h"
        }
    }
}

#define TRACE_FDMON_IO_URING_ADD_SQE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_FDMON_IO_URING_ADD_SQE) || \
    false)

static inline void trace_fdmon_io_uring_add_sqe(void *ctx, void *opaque, int opcode, int fd, uint64_t off, void *cqe_handler)
{
    if (trace_event_get_state(TRACE_FDMON_IO_URING_ADD_SQE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 28 "../util/trace-events"
            qemu_log("fdmon_io_uring_add_sqe " "ctx %p opaque %p opcode %d fd %d off %"PRId64" cqe_handler %p" "\n", ctx, opaque, opcode, fd, off, cqe_handler);
#line 497 "trace/trace-util.h"
        }
    }
}

#define TRACE_FDMON_IO_URING_CQE_HANDLER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_FDMON_IO_URING_CQE_HANDLER) || \
    false)

static inline void trace_fdmon_io_uring_cqe_handler(void *ctx, void *cqe_handler, int cqe_res)
{
    if (trace_event_get_state(TRACE_FDMON_IO_URING_CQE_HANDLER)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 29 "../util/trace-events"
            qemu_log("fdmon_io_uring_cqe_handler " "ctx %p cqe_handler %p cqe_res %d" "\n", ctx, cqe_handler, cqe_res);
#line 512 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_FILE_MONITOR_ADD_WATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_FILE_MONITOR_ADD_WATCH) || \
    false)

static inline void trace_qemu_file_monitor_add_watch(void *mon, const char *dirpath, const char *filename, void *cb, void *opaque, int64_t id)
{
    if (trace_event_get_state(TRACE_QEMU_FILE_MONITOR_ADD_WATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 32 "../util/trace-events"
            qemu_log("qemu_file_monitor_add_watch " "File monitor %p add watch dir='%s' file='%s' cb=%p opaque=%p id=%" PRId64 "\n", mon, dirpath, filename, cb, opaque, id);
#line 527 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_FILE_MONITOR_REMOVE_WATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_FILE_MONITOR_REMOVE_WATCH) || \
    false)

static inline void trace_qemu_file_monitor_remove_watch(void *mon, const char *dirpath, int64_t id)
{
    if (trace_event_get_state(TRACE_QEMU_FILE_MONITOR_REMOVE_WATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 33 "../util/trace-events"
            qemu_log("qemu_file_monitor_remove_watch " "File monitor %p remove watch dir='%s' id=%" PRId64 "\n", mon, dirpath, id);
#line 542 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_FILE_MONITOR_NEW_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_FILE_MONITOR_NEW) || \
    false)

static inline void trace_qemu_file_monitor_new(void *mon, int fd)
{
    if (trace_event_get_state(TRACE_QEMU_FILE_MONITOR_NEW)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 34 "../util/trace-events"
            qemu_log("qemu_file_monitor_new " "File monitor %p created fd=%d" "\n", mon, fd);
#line 557 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_FILE_MONITOR_ENABLE_WATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_FILE_MONITOR_ENABLE_WATCH) || \
    false)

static inline void trace_qemu_file_monitor_enable_watch(void *mon, const char *dirpath, int id)
{
    if (trace_event_get_state(TRACE_QEMU_FILE_MONITOR_ENABLE_WATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 35 "../util/trace-events"
            qemu_log("qemu_file_monitor_enable_watch " "File monitor %p enable watch dir='%s' id=%u" "\n", mon, dirpath, id);
#line 572 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_FILE_MONITOR_DISABLE_WATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_FILE_MONITOR_DISABLE_WATCH) || \
    false)

static inline void trace_qemu_file_monitor_disable_watch(void *mon, const char *dirpath, int id)
{
    if (trace_event_get_state(TRACE_QEMU_FILE_MONITOR_DISABLE_WATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 36 "../util/trace-events"
            qemu_log("qemu_file_monitor_disable_watch " "File monitor %p disable watch dir='%s' id=%u" "\n", mon, dirpath, id);
#line 587 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_FILE_MONITOR_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_FILE_MONITOR_EVENT) || \
    false)

static inline void trace_qemu_file_monitor_event(void *mon, const char *dirpath, const char *filename, int mask, unsigned int id)
{
    if (trace_event_get_state(TRACE_QEMU_FILE_MONITOR_EVENT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 37 "../util/trace-events"
            qemu_log("qemu_file_monitor_event " "File monitor %p event dir='%s' file='%s' mask=0x%x id=%u" "\n", mon, dirpath, filename, mask, id);
#line 602 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_FILE_MONITOR_DISPATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_FILE_MONITOR_DISPATCH) || \
    false)

static inline void trace_qemu_file_monitor_dispatch(void *mon, const char *dirpath, const char *filename, int ev, void *cb, void *opaque, int64_t id)
{
    if (trace_event_get_state(TRACE_QEMU_FILE_MONITOR_DISPATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 38 "../util/trace-events"
            qemu_log("qemu_file_monitor_dispatch " "File monitor %p dispatch dir='%s' file='%s' ev=%d cb=%p opaque=%p id=%" PRId64 "\n", mon, dirpath, filename, ev, cb, opaque, id);
#line 617 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_AIO_COROUTINE_ENTER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_AIO_COROUTINE_ENTER) || \
    false)

static inline void trace_qemu_aio_coroutine_enter(void *ctx, void *from, void *to, void *opaque)
{
    if (trace_event_get_state(TRACE_QEMU_AIO_COROUTINE_ENTER)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 41 "../util/trace-events"
            qemu_log("qemu_aio_coroutine_enter " "ctx %p from %p to %p opaque %p" "\n", ctx, from, to, opaque);
#line 632 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_COROUTINE_YIELD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_COROUTINE_YIELD) || \
    false)

static inline void trace_qemu_coroutine_yield(void *from, void *to)
{
    if (trace_event_get_state(TRACE_QEMU_COROUTINE_YIELD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 42 "../util/trace-events"
            qemu_log("qemu_coroutine_yield " "from %p to %p" "\n", from, to);
#line 647 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_COROUTINE_TERMINATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_COROUTINE_TERMINATE) || \
    false)

static inline void trace_qemu_coroutine_terminate(void *co)
{
    if (trace_event_get_state(TRACE_QEMU_COROUTINE_TERMINATE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 43 "../util/trace-events"
            qemu_log("qemu_coroutine_terminate " "self %p" "\n", co);
#line 662 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_CO_MUTEX_LOCK_UNCONTENDED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_CO_MUTEX_LOCK_UNCONTENDED) || \
    false)

static inline void trace_qemu_co_mutex_lock_uncontended(void *mutex, void *self)
{
    if (trace_event_get_state(TRACE_QEMU_CO_MUTEX_LOCK_UNCONTENDED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 46 "../util/trace-events"
            qemu_log("qemu_co_mutex_lock_uncontended " "mutex %p self %p" "\n", mutex, self);
#line 677 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_CO_MUTEX_LOCK_ENTRY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_CO_MUTEX_LOCK_ENTRY) || \
    false)

static inline void trace_qemu_co_mutex_lock_entry(void *mutex, void *self)
{
    if (trace_event_get_state(TRACE_QEMU_CO_MUTEX_LOCK_ENTRY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 47 "../util/trace-events"
            qemu_log("qemu_co_mutex_lock_entry " "mutex %p self %p" "\n", mutex, self);
#line 692 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_CO_MUTEX_LOCK_RETURN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_CO_MUTEX_LOCK_RETURN) || \
    false)

static inline void trace_qemu_co_mutex_lock_return(void *mutex, void *self)
{
    if (trace_event_get_state(TRACE_QEMU_CO_MUTEX_LOCK_RETURN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 48 "../util/trace-events"
            qemu_log("qemu_co_mutex_lock_return " "mutex %p self %p" "\n", mutex, self);
#line 707 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_CO_MUTEX_UNLOCK_ENTRY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_CO_MUTEX_UNLOCK_ENTRY) || \
    false)

static inline void trace_qemu_co_mutex_unlock_entry(void *mutex, void *self)
{
    if (trace_event_get_state(TRACE_QEMU_CO_MUTEX_UNLOCK_ENTRY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 49 "../util/trace-events"
            qemu_log("qemu_co_mutex_unlock_entry " "mutex %p self %p" "\n", mutex, self);
#line 722 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_CO_MUTEX_UNLOCK_RETURN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_CO_MUTEX_UNLOCK_RETURN) || \
    false)

static inline void trace_qemu_co_mutex_unlock_return(void *mutex, void *self)
{
    if (trace_event_get_state(TRACE_QEMU_CO_MUTEX_UNLOCK_RETURN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 50 "../util/trace-events"
            qemu_log("qemu_co_mutex_unlock_return " "mutex %p self %p" "\n", mutex, self);
#line 737 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_MEMALIGN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_MEMALIGN) || \
    false)

static inline void trace_qemu_memalign(size_t alignment, size_t size, void *ptr)
{
    if (trace_event_get_state(TRACE_QEMU_MEMALIGN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 54 "../util/trace-events"
            qemu_log("qemu_memalign " "alignment %zu size %zu ptr %p" "\n", alignment, size, ptr);
#line 752 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_ANON_RAM_ALLOC_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_ANON_RAM_ALLOC) || \
    false)

static inline void trace_qemu_anon_ram_alloc(size_t size, void *ptr)
{
    if (trace_event_get_state(TRACE_QEMU_ANON_RAM_ALLOC)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 55 "../util/trace-events"
            qemu_log("qemu_anon_ram_alloc " "size %zu ptr %p" "\n", size, ptr);
#line 767 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFREE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFREE) || \
    false)

static inline void trace_qemu_vfree(void *ptr)
{
    if (trace_event_get_state(TRACE_QEMU_VFREE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 56 "../util/trace-events"
            qemu_log("qemu_vfree " "ptr %p" "\n", ptr);
#line 782 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_ANON_RAM_FREE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_ANON_RAM_FREE) || \
    false)

static inline void trace_qemu_anon_ram_free(void *ptr, size_t size)
{
    if (trace_event_get_state(TRACE_QEMU_ANON_RAM_FREE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 57 "../util/trace-events"
            qemu_log("qemu_anon_ram_free " "ptr %p size %zu" "\n", ptr, size);
#line 797 "trace/trace-util.h"
        }
    }
}

#define TRACE_WIN32_MAP_ALLOC_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_WIN32_MAP_ALLOC) || \
    false)

static inline void trace_win32_map_alloc(size_t size)
{
    if (trace_event_get_state(TRACE_WIN32_MAP_ALLOC)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 60 "../util/trace-events"
            qemu_log("win32_map_alloc " "size:%zd" "\n", size);
#line 812 "trace/trace-util.h"
        }
    }
}

#define TRACE_WIN32_MAP_FREE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_WIN32_MAP_FREE) || \
    false)

static inline void trace_win32_map_free(void *ptr, void *h)
{
    if (trace_event_get_state(TRACE_WIN32_MAP_FREE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 61 "../util/trace-events"
            qemu_log("win32_map_free " "ptr:%p handle:%p" "\n", ptr, h);
#line 827 "trace/trace-util.h"
        }
    }
}

#define TRACE_HBITMAP_ITER_SKIP_WORDS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HBITMAP_ITER_SKIP_WORDS) || \
    false)

static inline void trace_hbitmap_iter_skip_words(const void *hb, void *hbi, uint64_t pos, unsigned long cur)
{
    if (trace_event_get_state(TRACE_HBITMAP_ITER_SKIP_WORDS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 64 "../util/trace-events"
            qemu_log("hbitmap_iter_skip_words " "hb %p hbi %p pos %"PRId64" cur 0x%lx" "\n", hb, hbi, pos, cur);
#line 842 "trace/trace-util.h"
        }
    }
}

#define TRACE_HBITMAP_RESET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HBITMAP_RESET) || \
    false)

static inline void trace_hbitmap_reset(void *hb, uint64_t start, uint64_t count, uint64_t sbit, uint64_t ebit)
{
    if (trace_event_get_state(TRACE_HBITMAP_RESET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 65 "../util/trace-events"
            qemu_log("hbitmap_reset " "hb %p items %"PRIu64",%"PRIu64" bits %"PRIu64"..%"PRIu64 "\n", hb, start, count, sbit, ebit);
#line 857 "trace/trace-util.h"
        }
    }
}

#define TRACE_HBITMAP_SET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HBITMAP_SET) || \
    false)

static inline void trace_hbitmap_set(void *hb, uint64_t start, uint64_t count, uint64_t sbit, uint64_t ebit)
{
    if (trace_event_get_state(TRACE_HBITMAP_SET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 66 "../util/trace-events"
            qemu_log("hbitmap_set " "hb %p items %"PRIu64",%"PRIu64" bits %"PRIu64"..%"PRIu64 "\n", hb, start, count, sbit, ebit);
#line 872 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_FAST_PATH_ATTEMPT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_FAST_PATH_ATTEMPT) || \
    false)

static inline void trace_lockcnt_fast_path_attempt(const void *lockcnt, int expected, int new)
{
    if (trace_event_get_state(TRACE_LOCKCNT_FAST_PATH_ATTEMPT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 69 "../util/trace-events"
            qemu_log("lockcnt_fast_path_attempt " "lockcnt %p fast path %d->%d" "\n", lockcnt, expected, new);
#line 887 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_FAST_PATH_SUCCESS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_FAST_PATH_SUCCESS) || \
    false)

static inline void trace_lockcnt_fast_path_success(const void *lockcnt, int expected, int new)
{
    if (trace_event_get_state(TRACE_LOCKCNT_FAST_PATH_SUCCESS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 70 "../util/trace-events"
            qemu_log("lockcnt_fast_path_success " "lockcnt %p fast path %d->%d succeeded" "\n", lockcnt, expected, new);
#line 902 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_UNLOCK_ATTEMPT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_UNLOCK_ATTEMPT) || \
    false)

static inline void trace_lockcnt_unlock_attempt(const void *lockcnt, int expected, int new)
{
    if (trace_event_get_state(TRACE_LOCKCNT_UNLOCK_ATTEMPT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 71 "../util/trace-events"
            qemu_log("lockcnt_unlock_attempt " "lockcnt %p unlock %d->%d" "\n", lockcnt, expected, new);
#line 917 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_UNLOCK_SUCCESS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_UNLOCK_SUCCESS) || \
    false)

static inline void trace_lockcnt_unlock_success(const void *lockcnt, int expected, int new)
{
    if (trace_event_get_state(TRACE_LOCKCNT_UNLOCK_SUCCESS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 72 "../util/trace-events"
            qemu_log("lockcnt_unlock_success " "lockcnt %p unlock %d->%d succeeded" "\n", lockcnt, expected, new);
#line 932 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_FUTEX_WAIT_PREPARE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_FUTEX_WAIT_PREPARE) || \
    false)

static inline void trace_lockcnt_futex_wait_prepare(const void *lockcnt, int expected, int new)
{
    if (trace_event_get_state(TRACE_LOCKCNT_FUTEX_WAIT_PREPARE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 73 "../util/trace-events"
            qemu_log("lockcnt_futex_wait_prepare " "lockcnt %p preparing slow path %d->%d" "\n", lockcnt, expected, new);
#line 947 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_FUTEX_WAIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_FUTEX_WAIT) || \
    false)

static inline void trace_lockcnt_futex_wait(const void *lockcnt, int val)
{
    if (trace_event_get_state(TRACE_LOCKCNT_FUTEX_WAIT)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 74 "../util/trace-events"
            qemu_log("lockcnt_futex_wait " "lockcnt %p waiting on %d" "\n", lockcnt, val);
#line 962 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_FUTEX_WAIT_RESUME_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_FUTEX_WAIT_RESUME) || \
    false)

static inline void trace_lockcnt_futex_wait_resume(const void *lockcnt, int new)
{
    if (trace_event_get_state(TRACE_LOCKCNT_FUTEX_WAIT_RESUME)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 75 "../util/trace-events"
            qemu_log("lockcnt_futex_wait_resume " "lockcnt %p after wait: %d" "\n", lockcnt, new);
#line 977 "trace/trace-util.h"
        }
    }
}

#define TRACE_LOCKCNT_FUTEX_WAKE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOCKCNT_FUTEX_WAKE) || \
    false)

static inline void trace_lockcnt_futex_wake(const void *lockcnt)
{
    if (trace_event_get_state(TRACE_LOCKCNT_FUTEX_WAKE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 76 "../util/trace-events"
            qemu_log("lockcnt_futex_wake " "lockcnt %p waking up one waiter" "\n", lockcnt);
#line 992 "trace/trace-util.h"
        }
    }
}

#define TRACE_SOCKET_LISTEN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_SOCKET_LISTEN) || \
    false)

static inline void trace_socket_listen(int num)
{
    if (trace_event_get_state(TRACE_SOCKET_LISTEN)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 79 "../util/trace-events"
            qemu_log("socket_listen " "backlog: %d" "\n", num);
#line 1007 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_MUTEX_LOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_MUTEX_LOCK) || \
    false)

static inline void trace_qemu_mutex_lock(void *mutex, const char *file, const int line)
{
    if (trace_event_get_state(TRACE_QEMU_MUTEX_LOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 84 "../util/trace-events"
            qemu_log("qemu_mutex_lock " "waiting on mutex %p (%s:%d)" "\n", mutex, file, line);
#line 1022 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_MUTEX_LOCKED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_MUTEX_LOCKED) || \
    false)

static inline void trace_qemu_mutex_locked(void *mutex, const char *file, const int line)
{
    if (trace_event_get_state(TRACE_QEMU_MUTEX_LOCKED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 85 "../util/trace-events"
            qemu_log("qemu_mutex_locked " "taken mutex %p (%s:%d)" "\n", mutex, file, line);
#line 1037 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_MUTEX_UNLOCK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_MUTEX_UNLOCK) || \
    false)

static inline void trace_qemu_mutex_unlock(void *mutex, const char *file, const int line)
{
    if (trace_event_get_state(TRACE_QEMU_MUTEX_UNLOCK)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 86 "../util/trace-events"
            qemu_log("qemu_mutex_unlock " "released mutex %p (%s:%d)" "\n", mutex, file, line);
#line 1052 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_DMA_RESET_TEMPORARY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_DMA_RESET_TEMPORARY) || \
    false)

static inline void trace_qemu_vfio_dma_reset_temporary(void *s)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_DMA_RESET_TEMPORARY)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 89 "../util/trace-events"
            qemu_log("qemu_vfio_dma_reset_temporary " "s %p" "\n", s);
#line 1067 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_RAM_BLOCK_ADDED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_RAM_BLOCK_ADDED) || \
    false)

static inline void trace_qemu_vfio_ram_block_added(void *s, void *p, size_t size)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_RAM_BLOCK_ADDED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 90 "../util/trace-events"
            qemu_log("qemu_vfio_ram_block_added " "s %p host %p size 0x%zx" "\n", s, p, size);
#line 1082 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_RAM_BLOCK_REMOVED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_RAM_BLOCK_REMOVED) || \
    false)

static inline void trace_qemu_vfio_ram_block_removed(void *s, void *p, size_t size)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_RAM_BLOCK_REMOVED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 91 "../util/trace-events"
            qemu_log("qemu_vfio_ram_block_removed " "s %p host %p size 0x%zx" "\n", s, p, size);
#line 1097 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_DUMP_MAPPING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_DUMP_MAPPING) || \
    false)

static inline void trace_qemu_vfio_dump_mapping(void *host, uint64_t iova, size_t size)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_DUMP_MAPPING)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 92 "../util/trace-events"
            qemu_log("qemu_vfio_dump_mapping " "vfio mapping %p to iova 0x%08" PRIx64 " size 0x%zx" "\n", host, iova, size);
#line 1112 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_FIND_MAPPING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_FIND_MAPPING) || \
    false)

static inline void trace_qemu_vfio_find_mapping(void *s, void *p)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_FIND_MAPPING)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 93 "../util/trace-events"
            qemu_log("qemu_vfio_find_mapping " "s %p host %p" "\n", s, p);
#line 1127 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_NEW_MAPPING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_NEW_MAPPING) || \
    false)

static inline void trace_qemu_vfio_new_mapping(void *s, void *host, size_t size, int index, uint64_t iova)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_NEW_MAPPING)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 94 "../util/trace-events"
            qemu_log("qemu_vfio_new_mapping " "s %p host %p size 0x%zx index %d iova 0x%"PRIx64 "\n", s, host, size, index, iova);
#line 1142 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_DO_MAPPING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_DO_MAPPING) || \
    false)

static inline void trace_qemu_vfio_do_mapping(void *s, void *host, uint64_t iova, size_t size)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_DO_MAPPING)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 95 "../util/trace-events"
            qemu_log("qemu_vfio_do_mapping " "s %p host %p <-> iova 0x%"PRIx64 " size 0x%zx" "\n", s, host, iova, size);
#line 1157 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_DMA_MAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_DMA_MAP) || \
    false)

static inline void trace_qemu_vfio_dma_map(void *s, void *host, size_t size, bool temporary, uint64_t *iova)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_DMA_MAP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 96 "../util/trace-events"
            qemu_log("qemu_vfio_dma_map " "s %p host %p size 0x%zx temporary %d &iova %p" "\n", s, host, size, temporary, iova);
#line 1172 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_DMA_MAPPED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_DMA_MAPPED) || \
    false)

static inline void trace_qemu_vfio_dma_mapped(void *s, void *host, uint64_t iova, size_t size)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_DMA_MAPPED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 97 "../util/trace-events"
            qemu_log("qemu_vfio_dma_mapped " "s %p host %p <-> iova 0x%"PRIx64" size 0x%zx" "\n", s, host, iova, size);
#line 1187 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_DMA_UNMAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_DMA_UNMAP) || \
    false)

static inline void trace_qemu_vfio_dma_unmap(void *s, void *host)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_DMA_UNMAP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 98 "../util/trace-events"
            qemu_log("qemu_vfio_dma_unmap " "s %p host %p" "\n", s, host);
#line 1202 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_PCI_READ_CONFIG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_PCI_READ_CONFIG) || \
    false)

static inline void trace_qemu_vfio_pci_read_config(void *buf, int ofs, int size, uint64_t region_ofs, uint64_t region_size)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_PCI_READ_CONFIG)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 99 "../util/trace-events"
            qemu_log("qemu_vfio_pci_read_config " "read cfg ptr %p ofs 0x%x size 0x%x (region addr 0x%"PRIx64" size 0x%"PRIx64")" "\n", buf, ofs, size, region_ofs, region_size);
#line 1217 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_PCI_WRITE_CONFIG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_PCI_WRITE_CONFIG) || \
    false)

static inline void trace_qemu_vfio_pci_write_config(void *buf, int ofs, int size, uint64_t region_ofs, uint64_t region_size)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_PCI_WRITE_CONFIG)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 100 "../util/trace-events"
            qemu_log("qemu_vfio_pci_write_config " "write cfg ptr %p ofs 0x%x size 0x%x (region addr 0x%"PRIx64" size 0x%"PRIx64")" "\n", buf, ofs, size, region_ofs, region_size);
#line 1232 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_REGION_INFO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_REGION_INFO) || \
    false)

static inline void trace_qemu_vfio_region_info(const char *desc, uint64_t region_ofs, uint64_t region_size, uint32_t cap_offset)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_REGION_INFO)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 101 "../util/trace-events"
            qemu_log("qemu_vfio_region_info " "region '%s' addr 0x%"PRIx64" size 0x%"PRIx64" cap_ofs 0x%"PRIx32 "\n", desc, region_ofs, region_size, cap_offset);
#line 1247 "trace/trace-util.h"
        }
    }
}

#define TRACE_QEMU_VFIO_PCI_MAP_BAR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QEMU_VFIO_PCI_MAP_BAR) || \
    false)

static inline void trace_qemu_vfio_pci_map_bar(int index, uint64_t region_ofs, uint64_t region_size, int ofs, void *host)
{
    if (trace_event_get_state(TRACE_QEMU_VFIO_PCI_MAP_BAR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 102 "../util/trace-events"
            qemu_log("qemu_vfio_pci_map_bar " "map region bar#%d addr 0x%"PRIx64" size 0x%"PRIx64" ofs 0x%x host %p" "\n", index, region_ofs, region_size, ofs, host);
#line 1262 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_DETECT_OPEN_MODE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_DETECT_OPEN_MODE) || \
    false)

static inline void trace_uffd_detect_open_mode(int mode)
{
    if (trace_event_get_state(TRACE_UFFD_DETECT_OPEN_MODE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 105 "../util/trace-events"
            qemu_log("uffd_detect_open_mode " "%d" "\n", mode);
#line 1277 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_QUERY_FEATURES_NOSYS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_QUERY_FEATURES_NOSYS) || \
    false)

static inline void trace_uffd_query_features_nosys(int err)
{
    if (trace_event_get_state(TRACE_UFFD_QUERY_FEATURES_NOSYS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 106 "../util/trace-events"
            qemu_log("uffd_query_features_nosys " "errno: %i" "\n", err);
#line 1292 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_QUERY_FEATURES_API_FAILED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_QUERY_FEATURES_API_FAILED) || \
    false)

static inline void trace_uffd_query_features_api_failed(int err)
{
    if (trace_event_get_state(TRACE_UFFD_QUERY_FEATURES_API_FAILED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 107 "../util/trace-events"
            qemu_log("uffd_query_features_api_failed " "errno: %i" "\n", err);
#line 1307 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_CREATE_FD_NOSYS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_CREATE_FD_NOSYS) || \
    false)

static inline void trace_uffd_create_fd_nosys(int err)
{
    if (trace_event_get_state(TRACE_UFFD_CREATE_FD_NOSYS)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 108 "../util/trace-events"
            qemu_log("uffd_create_fd_nosys " "errno: %i" "\n", err);
#line 1322 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_CREATE_FD_API_FAILED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_CREATE_FD_API_FAILED) || \
    false)

static inline void trace_uffd_create_fd_api_failed(int err)
{
    if (trace_event_get_state(TRACE_UFFD_CREATE_FD_API_FAILED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 109 "../util/trace-events"
            qemu_log("uffd_create_fd_api_failed " "errno: %i" "\n", err);
#line 1337 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_CREATE_FD_API_NOIOCTL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_CREATE_FD_API_NOIOCTL) || \
    false)

static inline void trace_uffd_create_fd_api_noioctl(uint64_t ioctl_req, uint64_t ioctl_supp)
{
    if (trace_event_get_state(TRACE_UFFD_CREATE_FD_API_NOIOCTL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 110 "../util/trace-events"
            qemu_log("uffd_create_fd_api_noioctl " "ioctl_req: 0x%" PRIx64 "ioctl_supp: 0x%" PRIx64 "\n", ioctl_req, ioctl_supp);
#line 1352 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_REGISTER_MEMORY_FAILED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_REGISTER_MEMORY_FAILED) || \
    false)

static inline void trace_uffd_register_memory_failed(void *addr, uint64_t length, uint64_t mode, int err)
{
    if (trace_event_get_state(TRACE_UFFD_REGISTER_MEMORY_FAILED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 111 "../util/trace-events"
            qemu_log("uffd_register_memory_failed " "addr: %p length: %" PRIu64 " mode: 0x%" PRIx64 " errno: %i" "\n", addr, length, mode, err);
#line 1367 "trace/trace-util.h"
        }
    }
}

#define TRACE_UFFD_UNREGISTER_MEMORY_FAILED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_UFFD_UNREGISTER_MEMORY_FAILED) || \
    false)

static inline void trace_uffd_unregister_memory_failed(void *addr, uint64_t length, int err)
{
    if (trace_event_get_state(TRACE_UFFD_UNREGISTER_MEMORY_FAILED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 112 "../util/trace-events"
            qemu_log("uffd_unregister_memory_failed " "addr: %p length: %" PRIu64 " errno: %i" "\n", addr, length, err);
#line 1382 "trace/trace-util.h"
        }
    }
}

#define TRACE_MODULE_LOAD_MODULE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MODULE_LOAD_MODULE) || \
    false)

static inline void trace_module_load_module(const char *name)
{
    if (trace_event_get_state(TRACE_MODULE_LOAD_MODULE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 115 "../util/trace-events"
            qemu_log("module_load_module " "file %s" "\n", name);
#line 1397 "trace/trace-util.h"
        }
    }
}

#define TRACE_MODULE_LOOKUP_OBJECT_TYPE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MODULE_LOOKUP_OBJECT_TYPE) || \
    false)

static inline void trace_module_lookup_object_type(const char *name)
{
    if (trace_event_get_state(TRACE_MODULE_LOOKUP_OBJECT_TYPE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 116 "../util/trace-events"
            qemu_log("module_lookup_object_type " "name %s" "\n", name);
#line 1412 "trace/trace-util.h"
        }
    }
}
#endif /* TRACE_UTIL_GENERATED_TRACERS_H */
