/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI/QMP commands
 *
 * Copyright IBM, Corp. 2011
 * Copyright (C) 2014-2018 Red Hat, Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef QAPI_COMMANDS_MISC_I386_H
#define QAPI_COMMANDS_MISC_I386_H

#include "qapi-types-misc-i386.h"

void qmp_rtc_reset_reinjection(Error **errp);
void qmp_marshal_rtc_reset_reinjection(QDict *args, QObject **ret, Error **errp);
SevInfo *qmp_query_sev(Error **errp);
void qmp_marshal_query_sev(QDict *args, QObject **ret, Error **errp);
SevLaunchMeasureInfo *qmp_query_sev_launch_measure(Error **errp);
void qmp_marshal_query_sev_launch_measure(QDict *args, QObject **ret, Error **errp);
SevCapability *qmp_query_sev_capabilities(Error **errp);
void qmp_marshal_query_sev_capabilities(QDict *args, QObject **ret, Error **errp);
void qmp_sev_inject_launch_secret(const char *packet_header, const char *secret, bool has_gpa, uint64_t gpa, Error **errp);
void qmp_marshal_sev_inject_launch_secret(QDict *args, QObject **ret, Error **errp);
SevAttestationReport *qmp_query_sev_attestation_report(const char *mnonce, Error **errp);
void qmp_marshal_query_sev_attestation_report(QDict *args, QObject **ret, Error **errp);
SgxInfo *qmp_query_sgx(Error **errp);
void qmp_marshal_query_sgx(QDict *args, QObject **ret, Error **errp);
SgxInfo *qmp_query_sgx_capabilities(Error **errp);
void qmp_marshal_query_sgx_capabilities(QDict *args, QObject **ret, Error **errp);
EvtchnInfoList *qmp_xen_event_list(Error **errp);
void qmp_marshal_xen_event_list(QDict *args, QObject **ret, Error **errp);
void qmp_xen_event_inject(uint32_t port, Error **errp);
void qmp_marshal_xen_event_inject(QDict *args, QObject **ret, Error **errp);

#endif /* QAPI_COMMANDS_MISC_I386_H */
